import type { AdVisualBinding, AdVisualDiagram, AdVisualGuideData, AdVisualStep } from "./ad-visual-guide-types";

export const operationsSources = {
  sysvol: "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/dfsrmig",
  rodc: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/ad-ds-installation-and-removal-wizard-page-descriptions",
  levels: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels",
  stage: "https://learn.microsoft.com/en-us/powershell/module/addsdeployment/add-addsreadonlydomaincontrolleraccount?view=windowsserver2025-ps",
  cache: "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-addomaincontrollerpasswordreplicationpolicyusage?view=windowsserver2025-ps",
  inbound: "https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/replication-error-8453",
  delegation: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/delegation-control-wizard",
  gpo: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/group-policy/group-policy-processing",
  scope: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/group-policy/group-policy-scope",
  gpresult: "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/gpresult",
  modeling: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/group-policy/group-policy-modeling-results",
  read: "https://learn.microsoft.com/en-us/troubleshoot/windows-server/group-policy/cannot-apply-user-gpo-when-computer-objects-dont-have-read-permissions",
  preferences: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/group-policy/group-policy-preferences",
  metadata: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/ad-ds-metadata-cleanup",
  backup: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/forest-recovery-guide/ad-forest-recovery-backing-up-system-state",
  recovery: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/forest-recovery-guide/ad-forest-recovery-perform-initial-recovery",
  authoritative: "https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/retore-deleted-accounts-and-groups-in-ad",
  fgpp: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/adac/fine-grained-password-policies",
  pso: "https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/ad735d45-ba6a-42fc-a41c-e91ced8e72d9",
};

function diagram(title: string, labels: string[], edges?: AdVisualDiagram["edges"]): AdVisualDiagram {
  return { title, nodes: labels.map((label, i) => ({ id: `n${i}`, label })), edges: edges ?? labels.slice(1).map((_, i) => ({ from: `n${i}`, to: `n${i + 1}` })) };
}
function step(id: string, title: string, path: string[], instruction: string, source: string, labels: string[], command?: string, edges?: AdVisualDiagram["edges"]): AdVisualStep {
  return { id, title, path, instruction, source, command, diagram: diagram(title, labels, edges), alt: `Explanatory diagram: ${labels.join("; ")}.` };
}
function guide(id: string, title: string, source: string, prerequisites: string, steps: AdVisualStep[]): AdVisualGuideData {
  return { id, title, source, prerequisites, kind: "concept", versionNote: "Self-authored explanatory diagrams for Windows Server 2025 administration, based on the linked Microsoft documentation; these are not screenshots of Windows dialogs. Historical feature minimums are distinct from Server 2025 DC deployment requirements. Menu wording can vary.", steps };
}

const sysvol = guide("ad-sysvol-dfsr", "AD DS · identify SYSVOL replication", operationsSources.sysvol,
  "Read-only checks on an authorized domain controller. SYSVOL file replication and AD database replication are different systems. Do not run dfsrmig /setglobalstate or attempt authoritative SYSVOL recovery from this diagnostic guide.", [
    step("sysvol-service", "Separate directory and policy-file replication", ["Domain controller", "SYSVOL", "DFS Replication"], "Modern domains use DFSR for SYSVOL policy and script files. AD database replication separately distributes directory objects; restarting AD DS is not a SYSVOL repair procedure.", operationsSources.sysvol, ["AD database: directory objects", "SYSVOL: policy and script files", "DFSR: SYSVOL file replication"], undefined, [{ from: "n1", to: "n2", label: "replicated by" }]),
    step("sysvol-state", "Inspect migration state without changing it", ["Elevated command prompt on a DC", "Read global state", "Check all controllers"], "Read both states. Eliminated (3) indicates the domain migration's final DFSR state; confirm all controllers reached it. These commands report migration, not complete file-replication health. Investigate DFS Replication event logs for actual errors.", operationsSources.sysvol, ["Global migration state", "Each DC's migration state", "DFSR event-log evidence"], "dfsrmig /getglobalstate\ndfsrmig /getmigrationstate"),
  ]);

const rodc = guide("ad-rodc-policy-staging", "AD DS · RODC writes, cache policy and staged deployment", operationsSources.rodc,
  "Use an isolated branch lab, AD DS RSAT and a healthy writable DC. Domain Admins perform account staging/PRP changes or delegate the specific rights. A per-RODC allow list is security-sensitive; avoid privileged identities and broad default allow groups. Installing a Windows Server 2025 DC requires forest and domain functional levels of at least Windows Server 2016; also validate network, DNS and AD preparation checks.", [
    step("rodc-direction", "Distinguish replication from originating writes", ["Writable DC", "Inbound directory replication", "RODC"], "An RODC receives directory changes from a writable partner. It cannot originate ordinary client directory updates; such updates need a writable DC. Read-only does not mean that incoming replication is prohibited.", operationsSources.inbound, ["Writable domain controller", "RODC: receives replication", "Client write: writable DC required"], "repadmin /showrepl BRANCH-RODC", [{ from: "n0", to: "n1", label: "inbound replication" }, { from: "n2", to: "n0", label: "originates there" }]),
    step("rodc-cache", "Scope and verify a branch-only password cache", ["AD Users and Computers", "Domain Controllers", "RODC Properties", "Password Replication Policy", "Advanced"], "Allow a group containing only this branch's users/computers on this RODC. Deny takes priority. Permission to cache is not proof that a password is stored: inspect revealed accounts separately. With a writable DC reachable, uncached authentication can be forwarded; plan/prepopulate approved credentials before a WAN outage.", operationsSources.cache, ["Per-RODC allow/deny policy", "Approved and actually cached", "Local authentication during outage", "Uncached: needs writable DC"], "Get-ADDomainControllerPasswordReplicationPolicyUsage -Identity BRANCH-RODC -RevealedAccounts", [{ from: "n0", to: "n1", label: "eligible, then cached" }, { from: "n1", to: "n2" }, { from: "n0", to: "n3", label: "not cached" }]),
    step("rodc-stage", "Pre-create the RODC account before installation", ["Writable DC / AD DS tools", "Pre-create RODC account", "Delegate installation", "Later attach the matching server"], "LAB WRITE: stage an account with the exact future RODC name and a delegated installer. This does not promote a server. The later installation attaches the server to that account. Install-ADDSDomainController has no -PrepareOnly option; do not confuse staging with adprep or DC cloning. Before a Server 2025 promotion, verify forest/domain functional levels are at least 2016.", operationsSources.stage, ["Administrator stages RODC account", "Delegate receives installation rights", "Matching server promoted later"], "Add-ADDSReadOnlyDomainControllerAccount -DomainControllerAccountName BRANCH-RODC -DomainName corp.contoso.com -SiteName Branch -DelegatedAdministratorAccountName 'CONTOSO\\RODC-Installers'"),
  ]);

const delegation = guide("ad-ou-task-delegation", "AD DS · delegate password resets in one OU", operationsSources.delegation,
  "AD Users and Computers/RSAT; an administrator with rights to delegate the selected task. Use a test OU, a help-desk security group and unprivileged test users. Granting delegation changes access. Protected administrator accounts can have different ACL inheritance; do not use them to validate ordinary OU delegation.", [
    step("delegate-select", "Select the exact OU and delegate group", ["AD Users and Computers", "Test OU", "Action → Delegate Control", "Users or Groups → Add"], "Select the OU that owns the target accounts and add the help-desk group. OU scope keeps this task narrower than Domain Admins membership.", operationsSources.delegation, ["Target OU", "Help-desk security group", "Scoped delegation wizard"]),
    step("delegate-task", "Grant the specific reset task", ["Tasks to Delegate", "Reset user passwords and force password change at next logon", "Finish"], "Select the reset task and review the summary before finishing. A custom task can grant selected object-type/property permissions; it does not inherently require full control of the subtree.", operationsSources.delegation, ["Reset Password task", "Inherited rights on eligible users", "No domain-wide administration"]),
    step("delegate-read", "Verify visibility and a scoped test reset", ["OU / user Properties", "Security → Advanced", "Delegate test session"], "Check read/list permissions as well as Reset Password. If custom ACLs hide users, the reset right alone does not make them visible. Test an unprivileged account inside the OU and an account outside it; review inheritance and deny entries if results differ.", operationsSources.delegation, ["Read/list: locate the account", "Reset right: perform the task", "Test inside and outside the OU"]),
  ]);

const inheritance = guide("ad-gpo-scope-precedence", "AD DS · trace GPO scope and precedence", operationsSources.gpo,
  "GPMC/RSAT with read access. Review an existing lab GPO before changing links, inheritance or enforcement; broad links can affect many users/computers. Diagrams simplify conflicting settings, not every extension's merging behavior.", [
    step("gpo-domain", "Review the domain-root blast radius", ["GPMC", "Forest → Domains", "Domain", "Linked Group Policy Objects / Scope"], "A domain link can reach many descendant users and computers. Inspect filtering, disabled sections and inheritance exceptions, and test in a small OU before broad rollout.", operationsSources.scope, ["Domain GPO link", "Descendant OUs", "Eligible users and computers"]),
    step("gpo-order", "Trace normal processing order", ["GPMC", "Target OU", "Group Policy Inheritance"], "Normal order is Local, Site, Domain, then parent-to-child OUs. Later applicable settings normally take precedence when the same setting conflicts; at one container, link order 1 is highest priority.", operationsSources.gpo, ["Local", "Site", "Domain", "Parent OU → child OU"]),
    step("gpo-block", "Check the OU's Block Inheritance setting", ["GPMC", "Domain or OU", "Block Inheritance / Group Policy Inheritance"], "Block Inheritance stops ordinary inherited site/domain/parent-OU links. It does not delete GPOs or stop locally linked GPOs. Enforced ancestor links pass this boundary; local policy remains a separate source.", operationsSources.gpo, ["Ordinary ancestor link", "Block Inheritance on OU", "Enforced ancestor still applies"], undefined, [{ from: "n0", to: "n1", label: "blocked" }, { from: "n2", to: "n1", label: "passes boundary" }]),
    step("gpo-enforced", "Identify an enforced ancestor link", ["GPMC", "Ancestor container", "GPO link → Enforced", "Target OU → Group Policy Inheritance"], "An enforced ancestor link prevents conflicting descendant settings from overriding it and survives Block Inheritance. Enforcement is a link property; it does not bypass security/WMI filtering or enable disabled settings.", operationsSources.gpo, ["Enforced ancestor link", "Conflicting child-OU setting", "Ancestor setting has precedence"], undefined, [{ from: "n0", to: "n2", label: "wins conflict" }, { from: "n1", to: "n2", label: "cannot override" }]),
  ]);

const diagnostics = guide("ad-gpo-result-diagnostics", "AD DS · inspect Group Policy results and permissions", operationsSources.modeling,
  "Authorized test computer/user and GPMC. Reading computer results may need elevation/delegated access; remote Results needs connectivity and access to target RSoP data. Reports can expose configuration details: keep them in the lab and use a new output filename.", [
    step("gpo-report", "Collect actual results on the client", ["Target Windows computer", "Command prompt", "gpresult", "Open the HTML report"], "Collect the actual computer/user result and inspect applied/denied GPOs. The HTML command writes a report in the current directory; it does not update policy. Select the relevant user context and elevate for computer details if necessary.", operationsSources.gpresult, ["Actual target session", "gpresult collects RSoP", "Applied and denied GPO report"], "gpresult /r\ngpresult /h policy-results.html"),
    step("gpo-model", "Choose simulation or observed Results", ["GPMC", "Group Policy Modeling or Group Policy Results", "Wizard", "Settings → Winning GPO"], "Modeling simulates a proposed user/computer scenario on a DC. Results retrieves what applied on the real target. Modeling excludes local GPO evaluation and cannot replace a real-client check.", operationsSources.modeling, ["Modeling: planned scenario", "Results: actual target", "Compare the winning GPO"], undefined, [{ from: "n0", to: "n2", label: "simulation" }, { from: "n1", to: "n2", label: "observed result" }]),
    step("gpo-filter", "Inspect Read and Apply permissions", ["GPMC", "GPO → Scope → Security Filtering", "Delegation → Advanced"], "Intended users/computers need Read and Apply Group Policy. Since MS16-072, computers also need Read to retrieve user policy. Authenticated Users normally has both permissions; if removed from filtering, restore necessary computer Read access separately. Check explicit denies and WMI filters.", operationsSources.read, ["User: Read + Apply", "Computer: reads user policy", "Deny/WMI can exclude the GPO"], undefined, [{ from: "n0", to: "n2" }, { from: "n1", to: "n2" }]),
  ]);

const targeted = guide("ad-loopback-preference-targeting", "AD DS · loopback modes and preference-item targeting", operationsSources.gpo,
  "Use a lab computer OU and test GPO. Loopback changes user settings for everyone signing into affected computers. Preference-item targeting narrows an individual preference item, while security/WMI filtering scopes the GPO itself.", [
    step("loopback-enable", "Configure user policy based on the computer", ["GPMC", "Computer-scoped GPO → Edit", "Computer Configuration → Policies → Administrative Templates → System → Group Policy", "Configure user Group Policy loopback processing mode"], "Enable loopback only on the intended kiosk/shared-computer scope. It selects user settings through the computer's GPO scope; it does not speed up SYSVOL or reset passwords.", operationsSources.gpo, ["Computer's OU / role", "Loopback policy enabled", "User settings selected by computer"]),
    step("loopback-modes", "Compare Merge and Replace", ["Loopback processing policy", "Merge or Replace", "Test next user sign-in"], "Merge processes the normal user list then adds the computer-based user list, which wins ordinary conflicts. Replace skips the normal user list and uses only the computer-based user list. Validate with actual Group Policy Results.", operationsSources.gpo, ["Normal user's GPO list", "Computer-based user GPO list", "Merge: both; computer list last", "Replace: computer list only"], undefined, [{ from: "n0", to: "n2" }, { from: "n1", to: "n2" }, { from: "n1", to: "n3" }]),
    step("preference-registry", "Target one preference item by registry existence", ["GPO editor", "User or Computer Configuration → Preferences", "Preference item → Properties → Common", "Item-level targeting → Targeting → New Item → Registry Match"], "Specify the hive, key and value whose existence controls this lab item. A false combined condition skips that item, not the entire GPO. Choose user/computer context deliberately and test both a matching and nonmatching account/computer.", operationsSources.preferences, ["Registry value exists?", "True: apply this preference item", "False: skip this item"], undefined, [{ from: "n0", to: "n1", label: "yes" }, { from: "n0", to: "n2", label: "no" }]),
  ]);

const metadata = guide("ad-failed-controller-metadata", "AD DS · clean up a permanently failed controller", operationsSources.metadata,
  "Destructive lab reference. Use Domain Admin/equivalent rights and a surviving replication partner in the failed DC's domain. Confirm the failed DC is permanently offline, will not be returned unchanged, and remaining DNS/GC/FSMO services and backups are viable. Gracefully demote a reachable healthy DC instead.", [
    step("metadata-select", "Confirm the permanent failure and exact identity", ["AD Users and Computers", "Change Domain Controller → surviving partner", "Domain Controllers OU", "Failed DC object"], "Match the retired server name and domain. Inventory its GC/DNS/FSMO impact. Do not delete an active controller or use ordinary computer-account deletion as normal demotion.", operationsSources.metadata, ["Permanently offline DC", "Healthy same-domain partner", "Exact failed DC object selected"]),
    step("metadata-delete", "Use the DC-specific cleanup confirmation", ["Failed DC object → Delete", "Confirm exact name", "This Domain Controller is permanently offline", "Review GC / FSMO warnings"], "LAB DELETE: modern ADUC performs metadata cleanup through this DC-specific dialog. Confirm only the retired object. Then inspect Sites and Services, stale DNS references and replication; do not assume every DNS record is removed automatically.", operationsSources.metadata, ["DC-specific permanent-offline dialog", "Metadata cleanup", "Verify remaining replication and DNS"]),
  ]);

const recovery = guide("ad-system-state-authoritative-object", "AD DS · system-state backup and authoritative object recovery", operationsSources.authoritative,
  "Recovery planning and isolated-lab practice only. Have a supported, verified backup containing the object, DSRM credentials, Windows Server Backup/tools and a documented replication isolation/reconnection plan. Restores overwrite directory state and can roll back passwords/memberships. System state alone is not bare-metal OS recovery; use full-server/BMR recovery when needed. Prefer Recycle Bin for eligible recent deletions.", [
step("backup-system-state", "Capture and validate AD DS system state", ["Windows Server Backup", "Backup Once → Different options → Custom", "Add Items → System State", "Separate backup target"], "System state includes AD DS and other critical system components. Use the lab's dedicated F: backup volume after checking capacity; the command writes a backup. Secure the copies and test a supported recovery, not merely successful job status.", operationsSources.backup, ["DC: AD DS + system state", "Separate secured backup", "Tested recovery plan"], "wbadmin start systemstatebackup -backupTarget:F:\nwbadmin get versions"),
    step("recover-dsrm", "Restore a suitable backup in the recovery plan", ["Isolate recovery DC as planned", "Boot Directory Services Restore Mode", "Windows Server Backup recovery", "Do not resume replication yet"], "Use a supported same-server/full-server recovery path and a backup from before deletion. Restore system state nonauthoritatively before marking the selected object authoritative. This diagram is a planning sequence, not a complete forest-recovery runbook.", operationsSources.recovery, ["Verified pre-deletion backup", "Isolated DC in DSRM", "Restore directory backup", "Keep recovery replication controlled"]),
    step("recover-authoritative", "Mark only the chosen object authoritative", ["DSRM after backup restore", "ntdsutil → activate instance ntds", "authoritative restore → restore object <exact DN>", "Review generated membership recovery files"], "LAB WRITE/RESTORE: the example marks one restored test object authoritative, preserving its backed-up identity. Check the exact DN and restore missing parents first. Follow Microsoft's generated link/LDIF instructions for memberships and the planned reconnection procedure; never mark the entire directory for this single-user scenario.", operationsSources.authoritative, ["Selected restored object", "Authoritative version increase", "Membership/link recovery", "Controlled replication + verification"], 'ntdsutil\nactivate instance ntds\nauthoritative restore\nrestore object "CN=LabUser,OU=Lab,DC=corp,DC=contoso,DC=com"\nquit\nquit'),
  ]);

const fgpp = guide("ad-fgpp-scope-conflicts", "AD DS · diagnose PSO scope and equal precedence", operationsSources.fgpp,
  "Read-only lab diagnostics with ADAC/ActiveDirectory tools and access to a test domain user. PSOs target domain users/global security groups, not local accounts, computer objects or OUs. Current GUI guidance assumes domain functional level Windows Server 2012 or higher.", [
    step("pso-scope", "Confirm a supported principal and effective PSO", ["ADAC", "Live domain user", "View resultant password settings"], "Verify that the account is a domain user and the PSO targets the user or an applicable global security group. A member server's local account uses local account policy; changing an AD PSO cannot alter its password requirements.", operationsSources.fgpp, ["Domain user / global security group", "PSO assignment in AD DS", "Local account: outside PSO scope"], "Get-ADUserResultantPasswordPolicy -Identity test1", [{ from: "n0", to: "n1" }]),
    step("pso-tie", "Resolve precedence within the applicable set", ["Direct user assignments first", "Otherwise group assignments", "Lower Precedence", "Equal Precedence → smaller objectGUID"], "Direct user PSOs are considered before group PSOs. Within the applicable set, lower numeric precedence wins; ties use the smaller objectGUID. This is not GPO link order and there is no PSO Enforced-link switch. Prefer distinct values and confirm the computed resultant PSO.", operationsSources.pso, ["Direct PSOs, else group PSOs", "Lowest numeric precedence", "Tie: smaller objectGUID", "Resultant PSO"], "Get-ADFineGrainedPasswordPolicy -Filter * | Select-Object Name,Precedence,ObjectGUID\nGet-ADUserResultantPasswordPolicy -Identity test1"),
  ]);

function bind(guide: AdVisualGuideData, startStep: string, context: string): AdVisualBinding { return { guide, startStep, context }; }
export const operationsGuideBindings: Record<string, AdVisualBinding> = {
  "az802-q-012": bind(sysvol, "sysvol-service", "Identify the SYSVOL file-replication service, then inspect DFSR migration state without changing it."),
  "az802-q-015": bind(rodc, "rodc-cache", "Configure branch-only eligibility on this RODC; an allow entry does not immediately populate its cache."),
  "az802-q-043": bind(rodc, "rodc-stage", "This corrected question concerns pre-staging an RODC account, a separate step from server promotion or cloning."),
  "az802-q-047": bind(metadata, "metadata-select", "Metadata cleanup applies to a permanently lost controller; review the destructive confirmation and surviving services."),
  "az802-q-050": bind(recovery, "recover-authoritative", "This is backup-based authoritative recovery of a selected original object, not a Recycle Bin screenshot sequence."),
  "az802-q-054": bind(delegation, "delegate-task", "Delegate the Reset Password task on the selected OU rather than granting domain-wide membership."),
  "az802-q-055": bind(inheritance, "gpo-domain", "Review the large set of descendant objects potentially affected by a domain-root link."),
  "az802-q-056": bind(inheritance, "gpo-order", "Trace normal Local → Site → Domain → OU processing, including nested OUs."),
  "az802-q-057": bind(inheritance, "gpo-order", "A child OU normally processes after its parent; inspect enforced links before assuming its setting wins."),
  "az802-q-058": bind(inheritance, "gpo-block", "Block Inheritance excludes ordinary ancestor links; enforced links are the important exception."),
  "az802-q-059": bind(inheritance, "gpo-enforced", "Enforced ancestor links preserve conflicting settings across descendant OUs and Block Inheritance."),
  "az802-q-060": bind(diagnostics, "gpo-report", "gpresult inspects actual applied/denied policy; writing its report does not refresh policy."),
  "az802-q-061": bind(diagnostics, "gpo-model", "Group Policy Modeling simulates a plan; Group Policy Results reports a real target."),
  "az802-q-062": bind(diagnostics, "gpo-filter", "Inspect Read/Apply security filtering and the computer Read permission needed to retrieve user policy."),
  "az802-q-063": bind(targeted, "loopback-enable", "Loopback uses the computer's location to select user settings on shared computers."),
  "az802-q-064": bind(targeted, "loopback-modes", "Replace excludes the normal user GPO list; Merge retains it and appends computer-based user policy."),
  "az802-q-065": bind(targeted, "preference-registry", "Registry Match is item-level targeting for one preference item, separate from filtering the entire GPO."),
  "az802-q-302": bind(rodc, "rodc-direction", "An RODC cannot originate ordinary directory writes, but it does receive inbound replication."),
  "az802-q-303": bind(rodc, "rodc-cache", "The corrected scenario is local cached authentication during a WAN outage, not all authentication passing through an RODC."),
  "az802-q-304": bind(delegation, "delegate-select", "Start ADUC's Delegation of Control Wizard on the target OU and grant the reset task."),
  "az802-q-305": bind(delegation, "delegate-read", "Visibility/read/list permissions and the Reset Password control-access right are separate checks."),
  "az802-q-308": bind(fgpp, "pso-scope", "A local member-server account is outside AD DS fine-grained password-policy scope."),
  "az802-q-309": bind(fgpp, "pso-tie", "The corrected tie scenario compares two directly assigned PSOs with equal precedence; the smaller objectGUID wins."),
  "az802-q-314": bind(recovery, "backup-system-state", "System state captures AD DS recovery data; losing the OS or disks also requires an appropriate full-server recovery plan."),
};
