import type { AdVisualBinding, AdVisualGuideData, AdVisualDiagram } from "./ad-visual-guide-types";

const replicationSource = "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/replication/active-directory-replication-concepts";
const gcSource = "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/planning-global-catalog-server-placement";
const siteSource = "https://learn.microsoft.com/en-us/windows-server/remote/remote-access/ras/multisite/configure/step-2-configure-the-multisite-infrastructure";
const linkSource = "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adreplicationsitelink?view=windowsserver2025-ps";
const trustSource = "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/netdom-trust";
const levelSource = "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/raise-domain-forest-functional-levels";
const server2025Book = "https://ptgmedia.pearsoncmg.com/images/9780135345894/samplepages/9780135345894_Sample.pdf";

// Authored explanatory diagrams, not screenshots or captured command output.
function diagram(title: string, nodes: AdVisualDiagram["nodes"], edges: AdVisualDiagram["edges"]): AdVisualDiagram {
  return { title: `Explanatory diagram · ${title}`, nodes, edges };
}
const versionNote = "Self-authored explanatory diagrams based on the linked Microsoft documentation, not Windows screenshots. Paths apply to AD DS on Windows Server 2016–2025; names and displayed options depend on the lab.";
const prerequisites = "Use an isolated, healthy AD lab with AD DS RSAT tools and appropriate delegated access. Replace example domains, site names and DC names with lab values. Commands are examples to review; no domain operation has been performed.";

const gcGuide: AdVisualGuideData = {
  id: "ad-global-catalog-network", title: "AD DS · global catalog contents and placement", source: gcSource, kind: "concept", versionNote: "Includes an original Microsoft screenshot whose capture OS version is unknown; the source procedure applies to Windows Server 2016–2025. Remaining visuals are authored explanatory diagrams. Paths and lab names depend on the environment.", prerequisites,
  steps: [
    { id: "contents", title: "Separate full and partial domain replicas", path: ["PowerShell", "ActiveDirectory module", "Get-ADForest", "GlobalCatalogs"], command: "Get-ADForest | Select-Object -ExpandProperty GlobalCatalogs", source: replicationSource, instruction: "List designated GC servers. A writable GC keeps its own domain in full and adds partial, read-only replicas of other domains. A partial replica includes every object but only selected attributes; this is not an application-partition inventory.", alt: "A GC has a full local domain replica and selected attributes of objects from another domain.", diagram: diagram("GC contents", [{ id: "local", label: "Own domain", detail: "Full replica; writable on a writable DC" }, { id: "remote", label: "Other domains", detail: "Every object; selected attributes only" }, { id: "gc", label: "Global catalog", detail: "Forest-wide directory searches" }], [{ from: "local", to: "gc", label: "full" }, { from: "remote", to: "gc", label: "partial" }]) },
    { id: "logon", title: "Trace universal group lookup at logon", path: ["Active Directory Sites and Services", "Sites", "Site", "Servers", "DC", "NTDS Settings", "Properties", "Global Catalog"], instruction: "Inspect the GC checkbox on the intended DC. In a multidomain forest, the authenticating DC uses GC information to build universal group membership into the user's token. A DC can cache that membership with UGMC; it is not stored exclusively on GC servers.", alt: "An authenticating DC obtains universal group information from a GC, then builds a logon token.", diagram: diagram("Logon membership lookup", [{ id: "dc", label: "Authenticating DC", detail: "Processes the user's domain logon" }, { id: "gc", label: "GC or valid UGMC cache", detail: "Universal group membership information" }, { id: "token", label: "User access token", detail: "Contains membership SIDs" }], [{ from: "gc", to: "dc", label: "membership" }, { from: "dc", to: "token", label: "builds" }]), source: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/forest-recovery-guide/ad-forest-recovery-add-gc" },
    { id: "placement", title: "Choose GC placement or membership caching", path: ["Active Directory Sites and Services", "Sites", "Branch site", "NTDS Site Settings", "Properties", "Enable Universal Group Membership Caching"], instruction: "Review branch connectivity and GC-dependent applications before choosing a local GC or UGMC. A local GC improves searches and logon availability. UGMC can reduce repeated WAN membership lookups, but needs an initial GC contact and does not serve GC queries. GC data is not automatically replicated to every DC in the site.", alt: "A branch uses either a local GC for searches and logon or a membership cache refreshed from a remote GC.", diagram: diagram("Branch GC decision", [{ id: "branch", label: "Branch site", detail: "Logon, searches, bandwidth and resilience" }, { id: "local", label: "Local GC", detail: "GC queries plus membership lookup" }, { id: "cache", label: "UGMC on branch DC", detail: "Membership caching; no GC query service" }, { id: "hub", label: "Reachable hub GC", detail: "Initial lookup and cache refresh" }], [{ from: "branch", to: "local", label: "option" }, { from: "branch", to: "cache", label: "option" }, { from: "hub", to: "cache", label: "refresh" }]) },
  ].map(step => step.id === "logon" ? {
    ...step,
    image: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/forest-recovery-guide/media/removegc1.png",
    alt: "Active Directory Sites and Services with DC1 NTDS Settings Properties open on General; the Global Catalog checkbox is cleared and highlighted.",
    screenshotLabel: "Microsoft original screenshot · capture OS version unknown",
    screenshotSource: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/forest-recovery-guide/ad-forest-recovery-remove-gc",
    screenshotCredit: "Microsoft Learn · Active Directory Forest Recovery",
    imageNote: "The source illustrates removing the GC and shows the checkbox CLEARED. Use it to locate and inspect the control; clearing it is not part of this logon exercise. The article applies to Windows Server 2016–2025, but does not identify the screenshot's OS version. The image shows neither universal group lookup nor token construction.",
  } : step),
};

const sitesGuide: AdVisualGuideData = {
  id: "ad-sites-subnet-mapping", title: "AD DS · map a branch subnet to its site", source: siteSource, kind: "concept", versionNote: "Includes an original Microsoft Windows Server 2012 screenshot, explicitly identified by its author. Remaining visuals are authored explanatory diagrams. AD DS paths also apply to Windows Server 2016–2025; names and displayed options depend on the lab.", prerequisites,
  steps: [
    { id: "site", title: "Represent a well-connected network location", path: ["Active Directory Sites and Services", "Sites", "New Site", "Name", "Link Name"], instruction: "In a lab, create Branch and choose its site link. Sites describe physical connectivity; they do not replace OUs or define domain boundaries. A site can host DCs from several domains.", alt: "Two well-connected subnets belong to one branch site, independently of the domain hierarchy.", diagram: diagram("Site scope", [{ id: "s1", label: "10.20.0.0/24", detail: "Well-connected branch subnet" }, { id: "s2", label: "10.21.0.0/24", detail: "Another well-connected subnet" }, { id: "site", label: "Branch site", detail: "Network location, not an OU or domain" }], [{ from: "s1", to: "site", label: "assigned" }, { from: "s2", to: "site", label: "assigned" }]) },
    { id: "subnet", title: "Associate the exact IP prefix with Branch", path: ["Active Directory Sites and Services", "Sites", "Subnets", "New Subnet", "Prefix: 10.20.0.0/24", "Select a site object: Branch", "OK"], source: `${server2025Book}#page=61`, instruction: "Create the subnet object with the real network prefix and select Branch. For an existing subnet, inspect Properties → Site. Each subnet object names one site. Optional external screenshot reference: Microsoft Press's Windows Server 2025 edition sample, Figure 4-17 (printed page 144 / PDF page 61), illustrates this dialog. The book edition is 2025; the screenshot's OS version is not independently established. Images remain on the publisher's page.", alt: "The client's address matches a subnet object, which maps it to the Branch site and local DCs.", diagram: diagram("Subnet to client site", [{ id: "client", label: "Client 10.20.0.42", detail: "Address inside the branch prefix" }, { id: "subnet", label: "10.20.0.0/24", detail: "Subnet object: Site = Branch" }, { id: "site", label: "Branch", detail: "Site-specific DC discovery" }], [{ from: "client", to: "subnet", label: "matches" }, { from: "subnet", to: "site", label: "maps to" }]) },
    { id: "client-check", title: "Verify client site and subnet inventory", path: ["Branch domain-joined client", "Command Prompt", "nltest /dsgetsite"], command: "nltest /dsgetsite\nGet-ADReplicationSubnet -Filter * | Select-Object Name,Site", source: "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adreplicationsubnet?view=windowsserver2025-ps", instruction: "Check the client site with nltest. Run the subnet inventory from a machine with the ActiveDirectory module. Compare the address, mapped prefix and selected site; an unmapped client may use a distant DC, but that symptom alone does not prove a replication failure.", alt: "Compare the site reported by a client with the site assigned to its matching subnet.", diagram: diagram("Verify the mapping", [{ id: "client", label: "nltest /dsgetsite", detail: "Client's current site result" }, { id: "inventory", label: "Subnet inventory", detail: "Name and Site from AD DS" }], [{ from: "inventory", to: "client", label: "compare" }]) },
  ].map(step => step.id === "subnet" ? {
    ...step,
    source: "https://techcommunity.microsoft.com/blog/coreinfrastructureandsecurityblog/how-to-create-an-active-directory-subnetsite-with-32-or-128-and-why/256105",
    image: "https://techcommunity.microsoft.com/t5/s/gxcuf89792/images/bS0yNTYxMDUtNTA3NjVpMzI3QTk0OUE0QTQ5QzFDMw?image-dimensions=469x576&revision=5",
    alt: "Windows Server 2012 New Object - Subnet dialog with an empty Prefix field and site choices Corp and DR; no site has been selected.",
    screenshotLabel: "Microsoft original screenshot · Windows Server 2012",
    screenshotSource: "https://techcommunity.microsoft.com/blog/coreinfrastructureandsecurityblog/how-to-create-an-active-directory-subnetsite-with-32-or-128-and-why/256105",
    screenshotCredit: "Rod Fournier · Microsoft Core Infrastructure and Security Blog",
    instruction: "Create the subnet object with the real network prefix and select Branch. For an existing subnet, inspect Properties → Site. Each subnet object names one site. The original Microsoft screenshot locates the Prefix field and site selection; use your own prefix and Branch rather than the source's Corp/DR lab names.",
    imageNote: "The author explicitly identifies Windows Server 2012. The source discusses /32 and /128 host prefixes for particular lab scenarios; this branch exercise still uses the real network prefix, for example 10.20.0.0/24. The displayed field is blank and no site is selected, so this is not evidence of a saved subnet mapping.",
  } : step),
};

const replicationGuide: AdVisualGuideData = {
  id: "ad-replication-links", title: "AD DS · site links and replication timing", source: replicationSource, kind: "concept", versionNote, prerequisites,
  steps: [
    { id: "link", title: "Review link membership and cost", path: ["Active Directory Sites and Services", "Sites", "Inter-Site Transports", "IP", "Site link", "Properties"], command: "Get-ADReplicationSiteLink -Filter * | Select-Object Name,SitesIncluded,Cost,ReplicationFrequencyInMinutes", source: linkSource, instruction: "Inspect sites included and cost. The KCC uses these logical paths to choose replication topology; lower summed cost is preferred. A site link is not a physical cable or packet route. Bridge all site links provides default transitivity on a routed network.", alt: "Two sites are connected by a logical link with cost and interval settings used by the KCC.", diagram: diagram("Site link policy", [{ id: "hq", label: "Headquarters site" }, { id: "link", label: "HQ–Branch site link", detail: "Sites included, cost and interval" }, { id: "branch", label: "Branch site" }], [{ from: "hq", to: "link", label: "included" }, { from: "link", to: "branch", label: "included" }]) },
    { id: "notification", title: "Understand change notification within a site", path: ["Active Directory Sites and Services", "Sites", "Site", "Servers", "Destination DC", "NTDS Settings", "Inbound connection"], command: "repadmin /notifyopt DC01 dc=corp,dc=contoso,dc=com", instruction: "Inspect automatically generated inbound connections. Within a site, a changed DC notifies its partners, which pull updates. The normal initial notification delay is 15 seconds, followed by 3 seconds between partners. The command reads timing settings without changing them; urgent replication and configured intersite notification are exceptions.", source: "https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/modify-default-intra-site-dc-replication-interval", alt: "A source DC notifies an intrasite partner, which requests and receives directory changes.", diagram: diagram("Intrasite notification", [{ id: "source", label: "Changed source DC", detail: "Normal notification delay: 15 seconds" }, { id: "partner", label: "Intrasite partner", detail: "Pulls changes after notification" }], [{ from: "source", to: "partner", label: "notifies" }, { from: "partner", to: "source", label: "requests changes" }]) },
    { id: "schedule", title: "Match the replication window to WAN availability", path: ["Active Directory Sites and Services", "Sites", "Inter-Site Transports", "IP", "Site link", "Properties", "Change Schedule"], command: "Get-ADReplicationSiteLink -Identity 'HQ-Branch' -Properties ReplicationSchedule | Select-Object Name,Cost,ReplicationFrequencyInMinutes,ReplicationSchedule", source: linkSource, instruction: "Inspect permitted hours and Replicate every separately. The interval applies within available windows; default is 180 minutes and minimum is 15. For a night-only WAN, inspect whether the link schedule overlaps that connectivity. A daytime backlog may reflect the closed window; verify actual replication results as well.", alt: "WAN availability and the allowed replication schedule must overlap before an interval can trigger replication.", diagram: diagram("Schedule and interval", [{ id: "wan", label: "WAN available at night", detail: "Physical network connectivity" }, { id: "window", label: "Allowed replication window", detail: "Site-link schedule must overlap WAN" }, { id: "interval", label: "Replication interval", detail: "Frequency within the open window" }], [{ from: "wan", to: "window", label: "overlap" }, { from: "window", to: "interval", label: "permits" }]) },
  ],
};

const diagnosticsGuide: AdVisualGuideData = {
  id: "ad-replication-health-commands", title: "AD DS · inspect replication and DC health", source: "https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/diagnose-replication-failures", kind: "command", versionNote, prerequisites,
  steps: [
    { id: "partners", title: "Read inbound partners and last results", path: ["RSAT AD DS tools", "Elevated Command Prompt", "repadmin /showrepl"], command: "repadmin /showrepl\nrepadmin /replsummary", instruction: "Read each naming context's inbound partners, last attempt, last success and failure status. Use the summary to locate failing DCs and large deltas. These commands report replication; they do not force synchronization or repair it.", alt: "Repadmin reads per-partition partner results and summarizes replication failures across DCs.", diagram: diagram("Replication evidence", [{ id: "dc", label: "DC replication state", detail: "Inbound partners for each partition" }, { id: "details", label: "repadmin /showrepl", detail: "Attempts, success and error codes" }, { id: "summary", label: "repadmin /replsummary", detail: "Failures and replication deltas" }], [{ from: "dc", to: "details", label: "reports" }, { from: "dc", to: "summary", label: "summarizes" }]) },
    { id: "health", title: "Run DC diagnostics and explicit DNS tests", path: ["RSAT AD DS tools", "Elevated Command Prompt", "dcdiag /s:DC01 /v"], command: "dcdiag /s:DC01 /v\ndcdiag /s:DC01 /test:DNS /v", source: "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/dcdiag", instruction: "Replace DC01 with a lab controller. Review failed tests and their evidence. DNS tests require an explicit /test:DNS or /c; they are not part of every default run. Avoid repair switches while collecting evidence.", alt: "Dcdiag performs default DC checks, while an explicit DNS command adds DNS-specific diagnostics.", diagram: diagram("DC diagnostic scope", [{ id: "dc", label: "Target DC01" }, { id: "default", label: "dcdiag /s:DC01 /v", detail: "Verbose default controller tests" }, { id: "dns", label: "dcdiag /test:DNS", detail: "Explicit DNS diagnostics" }], [{ from: "dc", to: "default", label: "default checks" }, { from: "dc", to: "dns", label: "additional scope" }]) },
  ],
};

const trustGuide: AdVisualGuideData = {
  id: "ad-trust-scope-direction", title: "AD DS · trust scope, direction and authentication", source: trustSource, kind: "concept", versionNote, prerequisites,
  steps: [
    { id: "parent-child", title: "Inspect the automatic parent-child trust", path: ["Active Directory Domains and Trusts", "Child domain", "Properties", "Trusts"], command: "Get-ADTrust -Filter * | Select-Object Name,Direction,TrustType,IntraForest,ForestTransitive", source: "https://learn.microsoft.com/en-us/project/supported-active-directory-topologies-for-project-server-2013-enterprise-resourc", instruction: "Inspect the trust created when a child domain joins the forest. Parent-child trusts are two-way and transitive. Authentication across that trust still requires permission on the resource; trust alone does not grant access.", alt: "A parent and child domain share a two-way transitive trust within one forest.", diagram: diagram("Parent-child trust", [{ id: "parent", label: "corp.contoso.com", detail: "Parent domain" }, { id: "child", label: "branch.corp.contoso.com", detail: "Child in the same forest" }], [{ from: "parent", to: "child", label: "trusts" }, { from: "child", to: "parent", label: "trusts" }]) },
    { id: "external", title: "Choose a domain-scoped external trust", path: ["Active Directory Domains and Trusts", "Resource domain", "Properties", "Trusts", "New Trust", "Partner domain", "External trust"], instruction: "For an approved lab relationship between two specified domains in different forests, choose External trust and the required direction. It is non-transitive; duration alone does not determine trust type. /Realm creates a non-Windows Kerberos realm trust, not an external AD domain trust.", alt: "An external trust connects two named domains and does not extend to another domain in the partner forest.", diagram: diagram("External trust scope", [{ id: "resource", label: "Resource domain", detail: "Trusting domain" }, { id: "account", label: "Partner account domain", detail: "Trusted domain" }, { id: "other", label: "Other partner domain", detail: "Not included by this external trust" }], [{ from: "resource", to: "account", label: "domain-scoped trust" }]) },
    { id: "forest", title: "Choose a trust between forest roots", path: ["Active Directory Domains and Trusts", "Forest root domain", "Properties", "Trusts", "New Trust", "Partner forest root", "Forest trust"], instruction: "Create a forest trust only in an authorized lab with suitable functional levels, DNS and connectivity. It links the forest roots and covers their domains in the configured direction. It does not automatically extend to a third forest or grant resource permissions. netdom trust cannot create an AD forest trust.", alt: "A forest trust connects root domains and covers domains within the two participating forests.", diagram: diagram("Forest trust scope", [{ id: "a", label: "Resource forest root", detail: "Forest A" }, { id: "ac", label: "A child domains" }, { id: "b", label: "Account forest root", detail: "Forest B" }, { id: "bc", label: "B child domains" }], [{ from: "ac", to: "a", label: "same forest" }, { from: "a", to: "b", label: "forest trust" }, { from: "b", to: "bc", label: "same forest" }]) },
    { id: "direction", title: "Read direction from the resource side", path: ["Active Directory Domains and Trusts", "Resource forest root", "Properties", "Trusts", "Domains trusted by this domain (outgoing trusts)"], command: "Get-ADTrust -Filter * | Select-Object Source,Target,Direction,ForestTransitive,SelectiveAuthentication", source: "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adtrust?view=windowsserver2025-ps", instruction: "For partner users to authenticate to resource-forest servers, the resource forest trusts the account forest: outgoing from the resource side, incoming from the account side. Direction is relative to the observer. Record Source and Target before interpreting Direction.", alt: "The resource forest has an outgoing trust to the account forest; account users authenticate toward resources.", diagram: diagram("Trust versus user access", [{ id: "resource", label: "Resource / trusting forest", detail: "Outgoing trust viewed from here" }, { id: "account", label: "Account / trusted forest", detail: "Incoming trust viewed from here" }], [{ from: "resource", to: "account", label: "trusts identities" }, { from: "account", to: "resource", label: "users access resources" }]) },
    { id: "selective", title: "Require approval on each target server", path: ["Active Directory Domains and Trusts", "Resource domain", "Properties", "Trusts", "Outgoing trust", "Properties", "Authentication", "Selective authentication"], command: "netdom trust resources.contoso.com /Domain:accounts.fabrikam.com /SelectiveAuth:yes", instruction: "After approved lab configuration, grant the partner group Allowed to authenticate on each intended target computer in AD Users and Computers (View → Advanced Features → computer Properties → Security → Advanced → Add). Also grant the application's resource permissions. The trust option alone grants neither right.", alt: "Partner users need both Allowed to authenticate on the server and permission on the requested resource.", diagram: diagram("Two access checks", [{ id: "user", label: "Partner user/group" }, { id: "auth", label: "Approved target computer", detail: "Allowed to authenticate permission" }, { id: "resource", label: "Application or share", detail: "Separate resource authorization" }], [{ from: "user", to: "auth", label: "authentication gate" }, { from: "auth", to: "resource", label: "resource permission" }]) },
  ],
};

const levelsGuide: AdVisualGuideData = {
  id: "ad-functional-level-planning", title: "AD DS · inspect and plan functional levels", source: levelSource, kind: "command", versionNote, prerequisites,
  steps: [
    { id: "recycle-prerequisite", title: "Inspect a forest-wide optional feature", path: ["RSAT", "PowerShell", "Get-ADOptionalFeature", "Recycle Bin Feature"], command: "Get-ADOptionalFeature -Filter 'Name -eq \"Recycle Bin Feature\"' | Select-Object Name,RequiredForestMode,EnabledScopes", source: "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adoptionalfeature?view=windowsserver2025-ps", instruction: "Read the Recycle Bin feature's required forest mode and enabled scopes. Its historical minimum is Windows Server 2008 R2; a forest containing 2025 DCs already needs at least 2016. Meeting a level requirement does not enable the feature automatically. Enabling Recycle Bin is a separate irreversible action, not performed here.", alt: "The Recycle Bin feature has a minimum forest level and a separate enabled state.", diagram: diagram("Recycle Bin prerequisite", [{ id: "forest", label: "Forest functional level", detail: "Feature minimum: Windows Server 2008 R2" }, { id: "feature", label: "AD Recycle Bin", detail: "Forest-wide optional feature" }, { id: "enabled", label: "EnabledScopes", detail: "Separate enablement; cannot be disabled" }], [{ from: "forest", to: "feature", label: "prerequisite" }, { from: "feature", to: "enabled", label: "inspect separately" }]) },
    { id: "scope", title: "Compare domain and forest capability scope", path: ["Active Directory Domains and Trusts", "Domain node", "Properties"], command: "Get-ADDomain | Select-Object Name,DomainMode\nGet-ADForest | Select-Object Name,ForestMode", instruction: "Read both levels. Domain mode governs domain capabilities; forest mode governs forest-wide capabilities. They also constrain DC operating systems, not client OS versions. A domain's level cannot be below its forest's level. These settings do not divide directory partitions into level-specific sets.", alt: "One forest functional level applies across the forest, with a separate domain functional level for each domain.", diagram: diagram("Functional level scope", [{ id: "forest", label: "Forest mode", detail: "Forest-wide capabilities and DC compatibility" }, { id: "d1", label: "Domain A mode", detail: "Capabilities within Domain A" }, { id: "d2", label: "Domain B mode", detail: "Capabilities within Domain B" }], [{ from: "forest", to: "d1", label: "minimum level" }, { from: "forest", to: "d2", label: "minimum level" }]) },
    { id: "inventory", title: "Inventory every domain's controllers", path: ["RSAT", "PowerShell", "Get-ADForest.Domains", "Get-ADDomainController"], command: "(Get-ADForest).Domains | ForEach-Object { Get-ADDomainController -Filter * -Server $_ } | Select-Object HostName,Domain,OperatingSystem,OperatingSystemVersion", instruction: "Check every DC against the target level's supported versions, then verify replication and backups. Inventorying only the current domain is insufficient for a forest change. Windows Server 2019/2022 use the 2016 level; Windows Server 2025 adds a 2025 level and needs 2016 or higher to join an existing domain.", alt: "Each domain's DC inventory feeds the compatibility decision for the planned functional level.", diagram: diagram("Compatibility inventory", [{ id: "a", label: "Domain A controllers", detail: "Check each DC OS version" }, { id: "b", label: "Domain B controllers", detail: "Check each DC OS version" }, { id: "target", label: "Target functional level", detail: "All relevant DCs must support it" }], [{ from: "a", to: "target", label: "must qualify" }, { from: "b", to: "target", label: "must qualify" }]) },
    { id: "raise", title: "Review supported changes and rollback limits", path: ["Active Directory Domains and Trusts", "Domain node", "Raise Domain Functional Level", "Select an available level", "Raise"], command: "Set-ADDomainMode -Identity corp.contoso.com -DomainMode Windows2016Domain\nGet-ADDomain -Identity corp.contoso.com | Select-Object DomainMode", source: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/lower-domain-forest-functional-levels", instruction: "This is a lab change example, not an instruction to choose the highest value blindly. Verify prerequisites before raising. Microsoft documents lowering supported levels only when OS compatibility and enabled-feature restrictions permit it; it is not an unrestricted undo. In an all-2025 forest, raising the forest to 2025 also raises its domain levels.", alt: "A planned level change requires compatible DCs and healthy replication; rollback is conditional on supported levels and features.", diagram: diagram("Level change conditions", [{ id: "ready", label: "Compatible, healthy DCs", detail: "Validated backups and permissions" }, { id: "change", label: "Planned level change", detail: "Enables required capabilities" }, { id: "rollback", label: "Conditional rollback", detail: "Supported OS levels and feature restrictions" }], [{ from: "ready", to: "change", label: "prerequisite" }, { from: "change", to: "rollback", label: "check support" }]) },
  ],
};

export const networkGuideBindings: Record<string, AdVisualBinding> = {
  "az802-q-030": { guide: gcGuide, startStep: "contents", context: "Inspect the global catalog's full own-domain replica and partial replicas of other domains." },
  "az802-q-031": { guide: gcGuide, startStep: "logon", context: "Follow universal group lookup by the authenticating domain controller." },
  "az802-q-032": { guide: sitesGuide, startStep: "site", context: "Sites model well-connected subnets and drive network-aware discovery and replication." },
  "az802-q-033": { guide: sitesGuide, startStep: "subnet", context: "Map the branch prefix, then compare nltest's site result with AD subnet inventory." },
  "az802-q-034": { guide: replicationGuide, startStep: "link", context: "Inspect site-link membership, cost and interval used by the KCC." },
  "az802-q-035": { guide: replicationGuide, startStep: "notification", context: "Intrasite partners are notified and pull changes rather than waiting for a WAN site-link interval." },
  "az802-q-036": { guide: diagnosticsGuide, startStep: "partners", context: "Read repadmin's inbound replication partners and last-success evidence." },
  "az802-q-037": { guide: diagnosticsGuide, startStep: "health", context: "Use dcdiag for controller health, with an explicit DNS-test command when needed." },
  "az802-q-038": { guide: replicationGuide, startStep: "schedule", context: "Compare the permitted replication window with night-only WAN availability; interval and schedule are distinct." },
  "az802-q-039": { guide: trustGuide, startStep: "parent-child", context: "Inspect the automatically created two-way transitive parent-child relationship." },
  "az802-q-040": { guide: trustGuide, startStep: "external", context: "An external trust scopes a relationship to two named domains rather than all domains in two forests." },
  "az802-q-041": { guide: trustGuide, startStep: "forest", context: "A forest trust connects roots and covers domains inside the two forests in the configured direction." },
  "az802-q-042": { guide: trustGuide, startStep: "selective", context: "Selective authentication adds an Allowed to authenticate gate on approved target computers." },
  "az802-q-052": { guide: levelsGuide, startStep: "inventory", context: "Verify the OS compatibility of every controller involved before a level change." },
  "az802-q-053": { guide: levelsGuide, startStep: "scope", context: "Compare domain-scoped and forest-scoped capabilities and the required ordering of their levels." },
  "az802-q-310": { guide: gcGuide, startStep: "logon", context: "A GC supplies forest-wide universal group information to the authenticating DC." },
  "az802-q-311": { guide: gcGuide, startStep: "placement", context: "A local GC improves branch performance; UGMC is a conditional alternative for membership lookups." },
  "az802-q-312": { guide: levelsGuide, startStep: "recycle-prerequisite", context: "Read the required forest mode and enabled state of AD Recycle Bin. Functional levels are not a partition classification." },
  "az802-q-313": { guide: levelsGuide, startStep: "raise", context: "A level sets capabilities and DC compatibility. Lowering is supported only under documented restrictions." },
  "az802-q-315": { guide: trustGuide, startStep: "direction", context: "Read trust direction from the resource forest: outgoing trust to the account forest permits partner-user authentication." },
};
