import type { AdVisualBinding, AdVisualDiagram, AdVisualGuideData } from "./ad-visual-guide-types";

const learn = "https://learn.microsoft.com/en-us/";
const roles = `${learn}windows-server/identity/ad-ds/manage/understand-fsmo-roles`;
const move = `${learn}troubleshoot/windows-server/active-directory/transfer-or-seize-operation-master-roles-in-ad-ds`;
const groups = `${learn}windows-server/identity/ad-ds/manage/understand-security-groups`;
const msa = `${learn}windows-server/identity/ad-ds/manage/group-managed-service-accounts/group-managed-service-accounts/group-managed-service-accounts-overview`;
const secure = `${learn}powershell/module/microsoft.powershell.management/test-computersecurechannel?view=powershell-5.1`;
const partitions = `${learn}windows/win32/ad/naming-contexts-and-partitions`;
const identifiers = `${learn}windows-server/identity/ad-ds/manage/understand-security-identifiers`;
const ps = (name: string) => `${learn}powershell/module/activedirectory/${name}?view=windowsserver2025-ps`;
const note = "Authored explanatory diagrams for Windows Server 2025 AD DS, not Windows UI screenshots. Commands use Windows PowerShell and current Microsoft documentation; AD module references select the Windows Server 2025 view.";
const diagram = (title: string, nodes: AdVisualDiagram["nodes"], edges: AdVisualDiagram["edges"]): AdVisualDiagram => ({ title, nodes, edges });

const fsmoGuide: AdVisualGuideData = {
  id: "ad-fsmo-ownership-and-recovery", title: "AD DS · locate and manage FSMO ownership", kind: "command", source: roles, versionNote: note,
  prerequisites: "Use an existing lab domain and RSAT. Inventory commands read state. Role moves require appropriate administrative rights and a healthy writable destination DC; displayed -WhatIf commands preview changes. Seizure is recovery after transfer is impossible, not routine maintenance.",
  steps: [
    { id: "owners", title: "Locate the five role owners", path: ["Domain-joined management host", "Terminal", "FSMO inventory"], instruction: "Read all five owners. Two roles serve the forest; three serve each domain.", command: "netdom query fsmo", source: `${learn}windows-server/administration/windows-commands/netdom-query`, diagram: diagram("Role ownership", [{ id: "query", label: "netdom query fsmo" }, { id: "forest", label: "Forest", detail: "Schema Master · Domain Naming Master" }, { id: "domain", label: "Each domain", detail: "RID Master · PDC Emulator · Infrastructure Master" }], [{ from: "query", to: "forest", label: "lists" }, { from: "query", to: "domain", label: "lists" }]), alt: "Explanatory diagram: netdom query fsmo lists two forest roles and three domain roles." },
    { id: "rid", title: "Trace RID allocation and exhaustion", path: ["RID Master", "DC RID pool", "New security principal"], instruction: "A DC consumes its local RID pool. Losing the RID Master blocks new principals only after available RIDs run out; existing logons do not need a new RID.", command: "Get-ADDomain | Select-Object RIDMaster", diagram: diagram("RID allocation", [{ id: "master", label: "RID Master" }, { id: "pool", label: "DC's remaining RID pool" }, { id: "sid", label: "New account SID", detail: "Domain identifier + allocated RID" }, { id: "empty", label: "Pool exhausted", detail: "No new principals without replenishment" }], [{ from: "master", to: "pool", label: "allocates" }, { from: "pool", to: "sid", label: "consumed to create" }, { from: "pool", to: "empty", label: "when unavailable RIDs run out" }]), alt: "Explanatory diagram: RID Master replenishes a DC pool used for account SIDs; exhaustion stops new principal creation." },
    { id: "forest-roles", title: "Separate schema from forest namespace", path: ["Forest", "Schema or domain-name change", "Responsible master"], instruction: "Schema Master controls class and attribute definitions. Domain Naming Master controls domain and application-partition additions/removals. Current Windows Server does not require the latter to be a global catalog.", command: "Get-ADForest | Select-Object SchemaMaster, DomainNamingMaster", source: `${learn}troubleshoot/windows-server/active-directory/fsmo-placement-and-optimization-on-ad-dcs`, diagram: diagram("Forest-wide roles", [{ id: "forest", label: "One forest" }, { id: "schema", label: "Schema Master", detail: "Object classes and attributes" }, { id: "names", label: "Domain Naming Master", detail: "Domains and application partitions" }], [{ from: "forest", to: "schema", label: "one owner" }, { from: "forest", to: "names", label: "one owner" }]), alt: "Explanatory diagram: one forest has a Schema Master for definitions and a Domain Naming Master for its namespace." },
    { id: "pdc", title: "Follow an urgent password check", path: ["Password change", "Priority replication", "Domain PDC Emulator"], instruction: "Other DCs preferentially replicate password changes to the PDC Emulator and consult it for a bad-password check before rejecting authentication.", command: "Get-ADDomain | Select-Object PDCEmulator", diagram: diagram("Latest password check", [{ id: "change", label: "Password changed on a DC" }, { id: "pdc", label: "PDC Emulator", detail: "Preferential password updates" }, { id: "login", label: "Another DC: bad-password attempt" }], [{ from: "change", to: "pdc", label: "priority replication" }, { from: "login", to: "pdc", label: "checks latest password" }]), alt: "Explanatory diagram: password changes reach the PDC Emulator preferentially, and another DC consults it after a bad-password attempt." },
    { id: "infrastructure", title: "Track references across domains", path: ["Domain group", "Member from another domain", "Reference maintenance"], instruction: "Infrastructure Master maintains cross-domain references. It has no reference-update work when every DC is a GC or AD Recycle Bin is enabled.", command: "Get-ADDomain | Select-Object InfrastructureMaster", source: move, diagram: diagram("Cross-domain reference", [{ id: "group", label: "Group in domain A" }, { id: "im", label: "Infrastructure Master A" }, { id: "user", label: "Renamed object in domain B" }], [{ from: "user", to: "im", label: "changed reference" }, { from: "im", to: "group", label: "updates reference" }]), alt: "Explanatory diagram: a domain's Infrastructure Master maintains a group reference to a changed object in another domain." },
    { id: "move", title: "Choose transfer or recovery seizure", path: ["Check original holder", "Healthy destination DC", "Transfer or seize", "Verify owners and replication"], instruction: "Transfer when the owner is reachable. Seize only when transfer is impossible and the former holder will not return in its old DC state. -Force attempts transfer first, then seizure; rebuild or forcibly demote and clean up the former holder before reuse. These commands only preview.", command: "# Reachable owner: preview transfer\nMove-ADDirectoryServerOperationMasterRole -Identity DC02 -OperationMasterRole RIDMaster -WhatIf\n# Permanent failure: preview forest-role recovery\nMove-ADDirectoryServerOperationMasterRole -Identity DC02 -OperationMasterRole SchemaMaster -Force -WhatIf", source: ps("move-addirectoryserveroperationmasterrole"), diagram: diagram("Role movement decision", [{ id: "live", label: "Owner reachable" }, { id: "transfer", label: "Transfer", detail: "Graceful handoff" }, { id: "failed", label: "Transfer impossible", detail: "Owner permanently unavailable" }, { id: "seize", label: "Seize", detail: "Recovery; clean up former DC" }], [{ from: "live", to: "transfer", label: "normal choice" }, { from: "failed", to: "seize", label: "recovery choice" }]), alt: "Explanatory decision diagram: reachable holders permit transfer; permanent failure requires recovery seizure and former-DC cleanup." },
  ],
};

const agdlpGuide: AdVisualGuideData = {
  id: "ad-group-based-resource-access", title: "AD DS · grant access through group nesting", kind: "concept", source: groups, versionNote: note,
  prerequisites: "Use an existing lab user and correctly scoped security groups. Membership and ACL edits change access. Examples assume alice, global group GG-Finance and domain local group DL-Finance-Read already exist; preview membership writes before applying.",
  steps: [
    { id: "chain", title: "Read the AGDLP chain", path: ["Accounts", "Global groups", "Domain Local groups", "Permissions"], instruction: "Accounts represent people; global groups represent roles; domain local groups receive resource permissions. The final DLP means Domain Local groups assigned Permissions, not local computer groups.", diagram: diagram("AGDLP", [{ id: "a", label: "A · Accounts" }, { id: "g", label: "G · Global role group" }, { id: "dl", label: "DL · Domain Local resource group" }, { id: "p", label: "P · Resource permission" }], [{ from: "a", to: "g", label: "member of" }, { from: "g", to: "dl", label: "nested in" }, { from: "dl", to: "p", label: "assigned" }]), alt: "Explanatory diagram: Accounts join Global groups, which join Domain Local groups assigned resource Permissions." },
    { id: "nest", title: "Nest the role group in the resource group", path: ["Role group membership", "Resource group membership", "Preview changes"], instruction: "Add alice to GG-Finance, then nest GG-Finance in DL-Finance-Read. -Identity is the receiving group; -Members identifies what goes into it. Remove -WhatIf only to apply the reviewed lab change.", command: "Add-ADGroupMember -Identity GG-Finance -Members alice -WhatIf\nAdd-ADGroupMember -Identity DL-Finance-Read -Members GG-Finance -WhatIf", source: ps("add-adgroupmember"), diagram: diagram("Group nesting direction", [{ id: "user", label: "alice" }, { id: "role", label: "GG-Finance" }, { id: "resource", label: "DL-Finance-Read" }], [{ from: "user", to: "role", label: "member of" }, { from: "role", to: "resource", label: "member of" }]), alt: "Explanatory diagram: alice is a member of GG-Finance, itself a member of DL-Finance-Read." },
    { id: "acl", title: "Assign the resource permission to the group", path: ["Shared folder Properties", "Security", "Edit", "Add resource group", "Required permission"], instruction: "Grant the required NTFS access to DL-Finance-Read and check share permissions too. Avoid direct per-user ACL entries. Test the user's effective access after refreshing the logon token.", diagram: diagram("Access evaluation", [{ id: "token", label: "User's group SIDs" }, { id: "acl", label: "Folder ACL", detail: "DL-Finance-Read: Allow Read" }, { id: "share", label: "Share permission" }, { id: "access", label: "Effective access", detail: "Both permission layers must allow access" }], [{ from: "token", to: "acl", label: "matched against" }, { from: "acl", to: "access", label: "NTFS limit" }, { from: "share", to: "access", label: "share limit" }]), alt: "Explanatory diagram: a user's group SIDs match the folder ACL; both NTFS and share permissions determine network access." },
  ],
};

const serviceGuide: AdVisualGuideData = {
  id: "ad-managed-service-identity", title: "AD DS · choose and prepare a managed service identity", kind: "command", source: msa, versionNote: note,
  prerequisites: "Use a compatible application and isolated AD lab. gMSA requires suitable DCs, KDS and authorized hosts. A service also needs its application-specific permissions and Log on as a service where required. Preview creation commands; install only on the intended authorized host.",
  steps: [
    { id: "choose", title: "Choose the supported account type", path: ["Application support", "Single host or multiple hosts", "Managed identity"], instruction: "Use a gMSA when supported for a service on multiple authorized hosts. An sMSA supports one computer. Inability to use a gMSA does not by itself prove the service supports an sMSA.", diagram: diagram("Managed account choice", [{ id: "app", label: "Check application support" }, { id: "single", label: "sMSA", detail: "One computer; managed password" }, { id: "multi", label: "gMSA", detail: "Multiple authorized hosts; managed password" }], [{ from: "app", to: "single", label: "single host, supported" }, { from: "app", to: "multi", label: "multi-host, supported" }]), alt: "Explanatory diagram: application support and host count determine whether a single-computer sMSA or multi-host gMSA fits." },
    { id: "kds", title: "Check KDS before creating a gMSA", path: ["Domain controller", "KDS root key", "Replication readiness"], instruction: "Check for an existing root key. If absent, follow Microsoft's creation procedure and allow the documented replication delay, up to ten hours. Do not backdate a key in production or repeatedly recreate it.", command: "Get-KdsRootKey", source: `${learn}windows-server/security/group-managed-service-accounts/create-the-key-distribution-services-kds-root-key`, diagram: diagram("Password generation readiness", [{ id: "key", label: "KDS root key" }, { id: "dcs", label: "DCs have replicated key" }, { id: "password", label: "gMSA password generation" }], [{ from: "key", to: "dcs", label: "replication delay" }, { from: "dcs", to: "password", label: "ready" }]), alt: "Explanatory diagram: a KDS root key must replicate to domain controllers before reliable gMSA password generation." },
    { id: "gmsa", title: "Restrict password retrieval to service hosts", path: ["Authorized computer group", "New-ADServiceAccount", "PrincipalsAllowedToRetrieveManagedPassword"], instruction: "APP-HOSTS must be an existing security group containing only the authorized computer accounts. Preview creation, then apply the reviewed lab command. The retrieval list is distinct from application resource permissions.", command: "New-ADServiceAccount -Name svc-app -DNSHostName svc-app.contoso.com -PrincipalsAllowedToRetrieveManagedPassword APP-HOSTS -WhatIf", source: ps("new-adserviceaccount"), diagram: diagram("gMSA host authorization", [{ id: "group", label: "APP-HOSTS", detail: "Authorized computer accounts" }, { id: "gmsa", label: "svc-app gMSA" }, { id: "host", label: "Authorized service host" }], [{ from: "group", to: "gmsa", label: "allowed to retrieve password" }, { from: "gmsa", to: "host", label: "managed credential" }]), alt: "Explanatory diagram: APP-HOSTS authorizes selected computer accounts to retrieve the svc-app gMSA password." },
    { id: "host", title: "Install and test on the authorized host", path: ["Service host", "Elevated Windows PowerShell", "Install", "Test", "Configure application"], instruction: "After provisioning and host authorization, install on each intended host and test readiness. True confirms account readiness, not the application's configuration or access rights. Configure the supported service separately.", command: "Install-ADServiceAccount -Identity svc-app\nTest-ADServiceAccount -Identity svc-app", source: ps("install-adserviceaccount"), diagram: diagram("Host readiness", [{ id: "install", label: "Install-ADServiceAccount" }, { id: "test", label: "Test-ADServiceAccount", detail: "Expect True on authorized host" }, { id: "app", label: "Configure service identity", detail: "Application support and rights still required" }], [{ from: "install", to: "test", label: "then validate" }, { from: "test", to: "app", label: "then configure" }]), alt: "Explanatory diagram: install the managed account, test local readiness, then configure the application and its rights." },
    { id: "standalone", title: "Prepare an sMSA for one supported host", path: ["Create sMSA", "Associate one computer", "Install and test there"], instruction: "RestrictToSingleComputer selects the sMSA parameter set; do not combine it with ManagedPasswordIntervalInDays. After creation, associate APP01 using Add-ADComputerServiceAccount, then install and test svc-legacy on APP01.", command: "# Preview creation; apply before attempting association\nNew-ADServiceAccount -Name svc-legacy -RestrictToSingleComputer -WhatIf\n# Preview association after the account exists\nAdd-ADComputerServiceAccount -Identity APP01 -ServiceAccount svc-legacy -WhatIf", source: ps("new-adserviceaccount"), diagram: diagram("Single-computer association", [{ id: "msa", label: "svc-legacy sMSA" }, { id: "computer", label: "APP01 computer account" }, { id: "host", label: "APP01 host", detail: "Install and test the sMSA here" }], [{ from: "msa", to: "computer", label: "associate once" }, { from: "computer", to: "host", label: "one supported host" }]), alt: "Explanatory diagram: an sMSA is associated with one computer account and installed on that host." },
    { id: "privilege", title: "Keep service rights limited", path: ["Service identity", "Required resource rights", "Service execution"], instruction: "A compromised service inherits its account's privileges. Use a dedicated managed identity with only the rights it needs; Domain Admin membership exposes far more than the application's resources.", diagram: diagram("Privilege exposure", [{ id: "service", label: "Application service" }, { id: "identity", label: "Dedicated managed identity" }, { id: "resources", label: "Only required resources" }], [{ from: "service", to: "identity", label: "runs as" }, { from: "identity", to: "resources", label: "least privilege" }]), alt: "Explanatory diagram: an application runs as a dedicated service identity with access only to required resources." },
  ],
};

const secureGuide: AdVisualGuideData = {
  id: "ad-member-secure-channel", title: "AD DS · check and repair a member computer's trust", kind: "command", source: secure, versionNote: note,
  prerequisites: "For domain member workstations or servers, not domain controllers. Use local administrator access and working internal DNS/DC connectivity. Repair needs a domain credential authorized to reset this computer's account. -WhatIf previews; it does not repair.",
  steps: [
    { id: "account", title: "Locate the machine's domain identity", path: ["Member computer", "AD computer account", "Netlogon secure channel"], instruction: "The machine and AD hold a shared computer-account password. A mismatch, missing account or connectivity failure can break trust; cached user sign-in may still work.", source: `${learn}troubleshoot/windows-server/windows-security/broken-trust-relationship-domain-joined-device-its-domain-secure-channel-issues`, diagram: diagram("Computer identity", [{ id: "member", label: "Member computer", detail: "Local machine-account secret" }, { id: "account", label: "AD computer account", detail: "Corresponding machine-account password" }, { id: "channel", label: "Netlogon secure channel" }], [{ from: "member", to: "channel", label: "authenticates using secret" }, { from: "account", to: "channel", label: "domain validates" }]), alt: "Explanatory diagram: a member computer's secret and its AD computer-account password establish its Netlogon secure channel." },
    { id: "test", title: "Test on the affected member", path: ["Affected member computer", "Elevated Windows PowerShell", "Test-ComputerSecureChannel"], instruction: "True means the check passed; False needs diagnosis. Check internal DNS and DC reachability. This cmdlet can produce misleading errors on domain controllers; use their documented netdom or nltest procedures instead.", command: "Test-ComputerSecureChannel -Verbose", diagram: diagram("Trust check", [{ id: "member", label: "Affected domain member" }, { id: "test", label: "Test-ComputerSecureChannel" }, { id: "result", label: "True or False", detail: "False: diagnose DNS, connectivity and account state" }], [{ from: "member", to: "test", label: "run locally" }, { from: "test", to: "result", label: "returns" }]), alt: "Explanatory diagram: the local member-computer secure-channel test returns True or False, with failures requiring diagnosis." },
    { id: "repair", title: "Repair and verify without deleting the account", path: ["Confirm account and connectivity", "Authorized domain credential", "Repair", "Repeat test"], instruction: "Preview the repair. In the reviewed lab, remove -WhatIf to restore the channel, then repeat the test. An absent computer account requires recreation or rejoin; account deletion is not a mandatory step for every trust failure.", command: "Test-ComputerSecureChannel -Repair -Credential (Get-Credential) -WhatIf\n# After applying the reviewed repair:\nTest-ComputerSecureChannel -Verbose", diagram: diagram("Targeted trust repair", [{ id: "credential", label: "Authorized domain credential" }, { id: "repair", label: "Repair machine trust" }, { id: "test", label: "Retest locally", detail: "Expect True; verify domain access" }], [{ from: "credential", to: "repair", label: "permits reset" }, { from: "repair", to: "test", label: "verify" }]), alt: "Explanatory diagram: an authorized domain credential permits secure-channel repair, followed by a local test." },
  ],
};

const partitionGuide: AdVisualGuideData = {
  id: "ad-directory-partition-scope", title: "AD DS · compare directory partition scopes", kind: "concept", source: partitions, versionNote: note,
  prerequisites: "Use an existing forest. These diagrams describe replication scope; the RootDSE command reads the selected DC. Application replica membership is configured explicitly, and creating a partition is a separate administrative change.",
  steps: [
    { id: "configuration", title: "Identify forest-wide configuration", path: ["Forest", "Configuration naming context", "Every forest DC"], instruction: "Configuration stores forest topology, sites and services. Schema stores definitions. Both replicate throughout the forest; each domain partition stores its domain objects.", diagram: diagram("Core naming contexts", [{ id: "forest", label: "Forest DCs" }, { id: "config", label: "Configuration", detail: "Forest topology and services" }, { id: "schema", label: "Schema", detail: "Object classes and attributes" }, { id: "domain", label: "Domain partition", detail: "Objects for one domain" }], [{ from: "config", to: "forest", label: "forest-wide replicas" }, { from: "schema", to: "forest", label: "forest-wide replicas" }, { from: "domain", to: "forest", label: "full copy on its domain DCs" }]), alt: "Explanatory diagram: configuration and schema replicate forest-wide, while a domain partition has full replicas on its own domain's DCs." },
    { id: "application", title: "Choose application data replicas", path: ["Application directory partition", "Configured replica set", "Selected domain controllers"], instruction: "An application partition stores service-specific directory data on its configured replicas. AD-integrated DNS uses examples such as DomainDnsZones and ForestDnsZones. Application-partition data is not part of the global catalog.", source: `${learn}windows/win32/ad/about-application-directory-partitions`, diagram: diagram("Selected replica set", [{ id: "app", label: "Application partition", detail: "For example, DNS directory data" }, { id: "dc1", label: "Selected DC1" }, { id: "dc2", label: "Selected DC2" }, { id: "dc3", label: "Unselected DC3", detail: "Does not host this partition" }], [{ from: "app", to: "dc1", label: "replica" }, { from: "app", to: "dc2", label: "replica" }]), alt: "Explanatory diagram: an application partition replicates to selected DC1 and DC2, with no replica on unselected DC3." },
    { id: "inspect", title: "Read naming contexts hosted by a DC", path: ["AD PowerShell", "Get-ADRootDSE -Server DC01", "namingContexts"], instruction: "Read the naming contexts actually hosted by DC01. This lists that server's partitions, not every application partition in the forest. Forest-wide enumeration instead inspects crossRef objects under CN=Partitions and filters their systemFlags and nCName.", command: "Get-ADRootDSE -Server DC01 | Select-Object -ExpandProperty namingContexts", source: ps("get-adrootdse"), diagram: diagram("RootDSE inventory scope", [{ id: "query", label: "Get-ADRootDSE -Server DC01" }, { id: "dc", label: "DC01" }, { id: "contexts", label: "Hosted naming contexts", detail: "Only this server's replicas" }], [{ from: "query", to: "dc", label: "reads" }, { from: "dc", to: "contexts", label: "reports" }]), alt: "Explanatory diagram: a RootDSE query to DC01 returns naming contexts hosted by that server only." },
  ],
};

const identifierGuide: AdVisualGuideData = {
  id: "ad-security-and-logon-identifiers", title: "AD DS · distinguish SIDs, GUIDs and logon names", kind: "concept", source: identifiers, versionNote: note,
  prerequisites: "Use an existing lab account. Diagrams explain identity and authorization; no rename, migration or SIDHistory change is performed. Query commands require AD RSAT and permission to read the object.",
  steps: [
    { id: "sid", title: "Use the SID for Windows authorization", path: ["Security principal", "Access token SIDs", "Resource ACL"], instruction: "A security principal receives a unique SID. Windows compares token SIDs with ACL entries; display names and sAMAccountName are not substitutes for security identifiers.", diagram: diagram("Authorization identity", [{ id: "principal", label: "User or security group" }, { id: "sid", label: "Security identifier (SID)" }, { id: "token", label: "User's access token", detail: "User and group SIDs" }, { id: "acl", label: "Resource ACL", detail: "Permissions refer to principal SIDs" }], [{ from: "principal", to: "sid", label: "assigned" }, { from: "sid", to: "token", label: "included" }, { from: "token", to: "acl", label: "access check" }]), alt: "Explanatory diagram: security-principal SIDs appear in a user's token and are compared with resource ACL entries." },
    { id: "migration", title: "Separate rename from cross-domain movement", path: ["Rename in same domain", "Cross-domain user move", "objectSid / objectGUID / sIDHistory"], instruction: "A same-domain rename retains the SID. Moving a user to another domain creates a new SID; the old SID can be retained in SIDHistory. The same directory object's objectGUID stays stable for its lifetime.", source: `${learn}windows/win32/ad/naming-properties`, diagram: diagram("Cross-domain user identity", [{ id: "old", label: "Old-domain objectSid" }, { id: "new", label: "New-domain objectSid" }, { id: "history", label: "sIDHistory", detail: "Previous SID, subject to migration/security rules" }, { id: "guid", label: "objectGUID", detail: "Stable for the same object's lifetime" }], [{ from: "old", to: "new", label: "new SID on domain move" }, { from: "old", to: "history", label: "previous value retained" }]), alt: "Explanatory diagram: a cross-domain user move creates a new SID and can retain the old one in SIDHistory; the object's GUID stays stable." },
    { id: "sam", title: "Resolve the legacy name within its domain", path: ["Domain-qualified logon", "sAMAccountName", "Directory identity"], instruction: "sAMAccountName must be unique among security principals within a domain. The same name may exist in another domain; domain qualification resolves the ambiguity. Changing the account name does not replace its SID.", source: `${learn}windows/win32/ad/naming-properties`, diagram: diagram("Domain-qualified account names", [{ id: "a", label: "CONTOSO\\alice" }, { id: "b", label: "FABRIKAM\\alice" }, { id: "sam", label: "sAMAccountName: alice", detail: "Unique within each domain, not across the forest" }], [{ from: "a", to: "sam", label: "domain A name" }, { from: "b", to: "sam", label: "domain B name" }]), alt: "Explanatory diagram: two domains can each contain sAMAccountName alice; qualified names distinguish their principals." },
  ],
};

const bind = (guide: AdVisualGuideData, startStep: string, context: string): AdVisualBinding => ({ guide, startStep, context });
export const identityGuideBindings: Record<string, AdVisualBinding> = {
  "az802-q-001": bind(fsmoGuide, "rid", "RID Master replenishes each DC's RID pool; this is the identifier-allocation role."),
  "az802-q-002": bind(fsmoGuide, "forest-roles", "Schema Master authorizes forest-wide class and attribute definition changes."),
  "az802-q-003": bind(fsmoGuide, "forest-roles", "Domain Naming Master manages additions and removals of domains and application partitions."),
  "az802-q-004": bind(fsmoGuide, "pdc", "The PDC Emulator receives priority password updates and is consulted for an urgent bad-password check."),
  "az802-q-005": bind(fsmoGuide, "infrastructure", "Infrastructure Master maintains references to objects from other domains; it does not allocate addresses or configure DNS."),
  "az802-q-006": bind(fsmoGuide, "rid", "Follow the remaining RID pool to exhaustion: loss of the RID Master does not immediately stop existing-user authentication."),
  "az802-q-007": bind(fsmoGuide, "owners", "netdom query fsmo directly lists the current operation-master role owners."),
  "az802-q-008": bind(fsmoGuide, "move", "For the permanently failed forest-role holder in this question, follow the seizure branch and former-DC cleanup precautions."),
  "az802-q-009": bind(fsmoGuide, "move", "For an online, reachable owner, follow the graceful transfer branch; seizure is the recovery alternative."),
  "az802-q-020": bind(agdlpGuide, "chain", "The final DLP refers to Domain Local groups receiving Permissions at the resource end of AGDLP."),
  "az802-q-021": bind(agdlpGuide, "nest", "Nest the user's role group into the resource-permission group, then grant that resource group access on the folder."),
  "az802-q-022": bind(serviceGuide, "gmsa", "A gMSA provides a managed password to multiple authorized hosts; the password-retrieval list determines eligible computers."),
  "az802-q-023": bind(serviceGuide, "standalone", "An sMSA fits a single-host service only when the application supports that account type; associate it with that computer."),
  "az802-q-024": bind(serviceGuide, "privilege", "Service compromise exposes its identity's rights, so a domain administrator service identity creates excessive privilege."),
  "az802-q-027": bind(secureGuide, "account", "The AD computer account supplies the domain identity paired with the member machine's local secret."),
  "az802-q-028": bind(secureGuide, "test", "Run Test-ComputerSecureChannel locally on a domain member to check trust; it is not a domain-controller diagnostic."),
  "az802-q-029": bind(secureGuide, "repair", "After checking DNS, connectivity and the account, repair this member's channel with a credential authorized to reset its computer account."),
  "az802-q-048": bind(partitionGuide, "configuration", "Configuration contains forest-wide topology and services, separately from Schema and each Domain partition."),
  "az802-q-049": bind(partitionGuide, "application", "Application-specific data replicates to the partition's selected replica set, rather than replacing the domain partition."),
  "az802-q-306": bind(identifierGuide, "sid", "The SID is the Windows security-principal identifier used in authorization; see the next step for cross-domain SID changes."),
  "az802-q-307": bind(identifierGuide, "sam", "Legacy account resolution needs sAMAccountName uniqueness within one domain; domain-qualified names distinguish identical names in different domains."),
};
