import type { Question } from "./questions";

const replication = "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/replication/active-directory-replication-concepts";
const gcPlacement = "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/planning-global-catalog-server-placement";
const trust = "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/netdom-trust";
const trustTypes = "https://learn.microsoft.com/en-us/project/supported-active-directory-topologies-for-project-server-2013-enterprise-resourc";
const trustQuery = "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adtrust?view=windowsserver2025-ps";
const levels = "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels";
const raise = "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/raise-domain-forest-functional-levels";
const lower = "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/lower-domain-forest-functional-levels";
const siteLink = "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adreplicationsitelink?view=windowsserver2025-ps";
const diagnostic = "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/dcdiag";
const repDiagnostic = "https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/diagnose-replication-failures";
const notification = "https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/modify-default-intra-site-dc-replication-interval";
const inventory = "(Get-ADForest).Domains | ForEach-Object { Get-ADDomainController -Filter * -Server $_ } | Select-Object HostName,Domain,OperatingSystem,OperatingSystemVersion";

// Preserved from the original audits of all 20 assigned rows, not newly certified
// by this source/answer review. Main merges corrections into those same identities.
const preservedAuditFlags = { originalityVerified: true, translationVerified: true, distractorsReviewed: true };

function reviewed(refs: string[], rationale: Question["rationale"], keyPoints: string[], whyOthers: string[], requirements: string, commandPath: NonNullable<Question["commandPath"]> = []): Partial<Question> {
  return {
    source: refs[0], sourceRefs: refs, rationale, keyPoints, whyOthers, requirements, commandPath,
    reviewStatus: "technical-approved",
    audit: { ...preservedAuditFlags, sourceRefs: refs, sourceVerified: true, answerVerified: true, reviewer: "Microsoft source and answer verification; original originality, translation and distractor audit flags preserved", reviewedAt: "2026-10-09T19:09:53Z" },
  };
}

/** Main applies these exact-ID corrections to the bank once, preserving order and progress. */
export const networkQuestionCorrections: Record<string, Partial<Question>> = {
  "az802-q-030": reviewed([replication, gcPlacement, "https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/fsmo-placement-and-optimization-on-ad-dcs"], {
    en: "A global catalog supports forest-wide searches. A writable GC holds its own domain in full and partial, read-only replicas of the other domains, containing all their objects but only selected attributes.",
    fa: "کاتالوگ سراسری جست‌وجو در کل جنگل را ممکن می‌کند. GC قابل‌نوشتن، دامنهٔ خودش را کامل و دامنه‌های دیگر را به‌صورت نسخهٔ جزئی و فقط‌خواندنی نگه می‌دارد؛ همهٔ اشیا ولی تنها بعضی ویژگی‌ها موجودند.",
    de: "Ein Global Catalog ermöglicht forestweite Suchen. Ein beschreibbarer GC hält seine eigene Domäne vollständig und andere Domänen als schreibgeschützte Teilreplikate mit allen Objekten, aber ausgewählten Attributen.",
  }, ["A GC supports searches across all domains in its forest.", "A writable GC has a full own-domain replica and partial, read-only replicas of other domains.", "The partial attribute set controls which attributes appear in partial domain replicas."], ["SYSVOL stores policy and script files, not the forest-wide directory catalog.", "A site link defines replication policy between sites.", "", "RID pools provide identifiers for new security principals."], "Applies to Windows Server 2025 AD DS and supported earlier releases. A GC is a capability of a DC; an RODC can also be a GC while its own-domain replica remains read-only. The Domain Naming Master has not required GC placement since Windows Server 2003.", [{ label: "List designated GC servers", command: "Get-ADForest | Select-Object -ExpandProperty GlobalCatalogs" }]),

  "az802-q-031": reviewed([gcPlacement, replication], {
    en: "In a multidomain forest, the authenticating DC obtains forest-wide universal group membership information from a GC, or uses an available universal group membership cache, to build the user's logon token.",
    fa: "در جنگل چنددامنه‌ای، کنترل‌کنندهٔ احراز هویت اطلاعات عضویت گروه‌های Universal را از GC یا کش معتبر این عضویت دریافت می‌کند تا توکن ورود کاربر ساخته شود.",
    de: "In einem Forest mit mehreren Domänen verwendet der authentifizierende DC einen GC oder einen vorhandenen Universal-Group-Membership-Cache, um die universellen Gruppen im Anmeldetoken zu berücksichtigen.",
  }, ["GC information supports universal group membership evaluation at logon.", "Universal group objects and membership also exist in their owning domain; they are not stored only on GCs.", "UGMC can reduce repeated GC lookups, but initial lookup and refresh still require GC connectivity."], ["DHCP scope hosting is unrelated to GC membership lookup.", "A GC does not store every file share.", "", "Address leasing is DHCP's task."], "Windows Server 2025 AD DS. Plan multidomain logon availability around GC reachability or valid cached membership; do not assume that the dependency exists only when an administrator knowingly uses universal groups."),

  "az802-q-032": reviewed([replication], {
    en: "An AD site models well-connected IP subnets. AD DS uses site information for network-aware DC discovery and replication topology, independently of the OU and domain hierarchy.",
    fa: "سایت AD زیرشبکه‌های IP با ارتباط مناسب را مدل می‌کند. AD DS از سایت برای یافتن کنترل‌کننده‌های مناسب و طراحی توپولوژی تکثیر استفاده می‌کند؛ سایت مستقل از ساختار OU و دامنه است.",
    de: "Ein AD-Site modelliert gut verbundene IP-Subnetze. AD DS nutzt Sites für standortbezogene DC-Suche und Replikation, unabhängig von OU- und Domänenhierarchien.",
  }, ["A site represents one or more well-connected IP subnets.", "A site can contain DCs from multiple domains, and a domain can span multiple sites.", "Subnet objects associate address ranges with a site for client discovery."], ["", "OUs organize directory objects and delegated administration; sites model connectivity.", "Sites do not store passwords in plaintext.", "Share quotas belong to file-service configuration."], "Windows Server 2025 AD DS. Each subnet object references one site. Missing or incorrectly overlapping subnet definitions can impair client site identification; a subnet object cannot be assigned simultaneously to two sites."),

  "az802-q-033": reviewed([replication, "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adreplicationsubnet?view=windowsserver2025-ps"], {
    en: "If the branch address range is not mapped to its AD site, clients may fail to select the intended local DC and use a distant one. Check the subnet mapping and the client's reported site before diagnosing other causes.",
    fa: "اگر محدودهٔ آدرس شعبه به سایت درست نگاشت نشده باشد، ممکن است کلاینت به‌جای کنترل‌کنندهٔ محلی از کنترل‌کنندهٔ دور استفاده کند. نگاشت زیرشبکه و سایت گزارش‌شدهٔ کلاینت را بررسی کنید.",
    de: "Fehlt die Zuordnung des Zweigstellen-Subnetzes, können Clients einen entfernten statt des vorgesehenen lokalen DC auswählen. Prüfe Subnetzzuteilung und gemeldeten Client-Site.",
  }, ["Subnet-to-site mapping helps DC Locator identify the client site.", "A missing mapping can cause remote-DC selection and extra WAN traffic.", "DC server-site placement and site-link policies should be checked separately from client subnet mapping."], ["Subnet mapping does not erase NTFS permissions.", "A missing client subnet does not invalidate the AD schema.", "It does not immediately stop RID allocation.", ""], "Windows Server 2025 AD DS. Missing subnet mapping can explain distant-controller use; the exact DC selection also depends on DNS, discovery state and available controllers.", [{ label: "Read client site", command: "nltest /dsgetsite" }, { label: "Read subnet-to-site mappings", command: "Get-ADReplicationSubnet -Filter * | Select-Object Name,Site" }]),

  "az802-q-034": reviewed([replication, siteLink], {
    en: "A site link defines a logical replication relationship among sites, including cost, permitted schedule and replication interval. The KCC uses these policies to build connections between DCs.",
    fa: "پیوند سایت رابطهٔ منطقی تکثیر بین سایت‌ها را با هزینه، زمان‌بندی مجاز و فاصلهٔ تکثیر مشخص می‌کند. KCC از این سیاست‌ها برای ساخت اتصال بین کنترل‌کننده‌ها استفاده می‌کند.",
    de: "Ein Site-Link beschreibt eine logische Replikationsbeziehung zwischen Sites mit Kosten, Zeitplan und Intervall. Daraus erstellt der KCC Verbindungen zwischen DCs.",
  }, ["Site links include two or more sites and influence intersite topology.", "Cost and schedule express replication policy, not a physical network route.", "Bridge all site links gives implicit transitivity by default; explicit bridge objects are not mandatory on a fully routed network."], ["DHCP reservations assign addresses, not replication topology.", "SMB encryption is unrelated to site-link policy.", "", "Home folders are configured on user accounts or through policy."], "Windows Server 2025 AD DS. Default automatic bridging has no corresponding explicit AD bridge object. A site link does not create network connectivity.", [{ label: "Inspect link policy", command: "Get-ADReplicationSiteLink -Filter * | Select-Object Name,SitesIncluded,Cost,ReplicationFrequencyInMinutes" }]),

  "az802-q-035": reviewed([notification, replication], {
    en: "Intrasite replication normally uses change notification. After notification, partners request changes. The usual initial delay is 15 seconds, with 3 seconds between subsequent partner notifications.",
    fa: "تکثیر داخل سایت معمولاً از اعلان تغییر استفاده می‌کند و شریک پس از اعلان تغییرات را درخواست می‌کند. تأخیر اولیهٔ عادی ۱۵ ثانیه و فاصلهٔ اعلان به شریک‌های بعدی ۳ ثانیه است.",
    de: "Replikation innerhalb eines Sites nutzt normalerweise Änderungsbenachrichtigungen; Partner rufen anschließend die Änderungen ab. Üblich sind 15 Sekunden bis zur ersten und 3 Sekunden zwischen weiteren Benachrichtigungen.",
  }, ["Change notification reduces normal intrasite propagation latency.", "The initial default notification delay is 15 seconds; subsequent partner notifications are spaced 3 seconds apart.", "Normal intersite replication uses its separate schedule and interval; notification can be configured there too."], ["DNS zone transfers are not the AD directory replication model.", "", "Manual export is not normal intrasite replication.", "Tape transfer is unrelated to normal AD replication."], "Windows Server 2025 AD DS. These are normal configurable notification delays, not a guarantee that all replication completes in 15 seconds; urgent replication has different behavior.", [{ label: "Read notification settings without changing them", command: "repadmin /notifyopt DC01 dc=corp,dc=contoso,dc=com" }]),

  "az802-q-036": reviewed([repDiagnostic], {
    en: "repadmin /showrepl displays inbound partners and per-partition replication results, including the last successful replication. /replsummary provides a summary of failures and deltas.",
    fa: "دستور repadmin /showrepl شریک‌های ورودی و نتیجهٔ تکثیر هر پارتیشن، از جمله آخرین تکثیر موفق، را نشان می‌دهد. ‎/replsummary خلاصهٔ خطاها و فاصلهٔ تکثیر را ارائه می‌کند.",
    de: "repadmin /showrepl zeigt eingehende Partner und Replikationsergebnisse je Partition einschließlich des letzten Erfolgs. /replsummary fasst Fehler und Zeitdifferenzen zusammen.",
  }, ["/showrepl reports inbound replication by naming context.", "/replsummary helps locate failures and large deltas.", "Reporting commands provide evidence; they do not repair replication."], ["", "diskpart manages disks and partitions, not AD replication partners.", "ipconfig displays network configuration, not per-partition replication results.", "Event logs can help, but wevtutil alone is not the dedicated replication-partner tool."], "Windows Server 2025 AD DS. Install AD DS RSAT tools and use appropriate access to query target controllers.", [{ label: "Read inbound replication results", command: "repadmin /showrepl" }, { label: "Summarize replication health", command: "repadmin /replsummary" }]),

  "az802-q-037": reviewed([diagnostic], {
    en: "dcdiag runs diagnostic tests against domain controllers. /v adds detail; DNS testing must be requested with /test:DNS or included using /c rather than assumed in the default test set.",
    fa: "dcdiag آزمون‌های تشخیصی کنترل‌کنندهٔ دامنه را اجرا می‌کند. ‎/v جزئیات را افزایش می‌دهد؛ برای آزمون DNS باید ‎/test:DNS یا ‎/c را مشخص کرد و نباید آن را جزء همهٔ اجراهای پیش‌فرض فرض کرد.",
    de: "dcdiag führt DC-Diagnosetests aus. /v liefert Details; DNS-Tests müssen mit /test:DNS oder /c angefordert werden und gehören nicht zum üblichen Standardsatz.",
  }, ["dcdiag reports DC health through named tests.", "/s selects a target server and /v enables detailed output.", "DNS tests are explicitly selected with /test:DNS or /c."], ["nslookup queries DNS rather than running broad DC diagnostics.", "robocopy copies files.", "mstsc opens Remote Desktop sessions.", ""], "Windows Server 2025 AD DS. Use RSAT AD DS tools and appropriate permissions. Avoid repair options while collecting diagnostic evidence.", [{ label: "Run detailed default tests on a lab DC", command: "dcdiag /s:DC01 /v" }, { label: "Run DNS diagnostics explicitly", command: "dcdiag /s:DC01 /test:DNS /v" }]),

  "az802-q-038": reviewed([siteLink, "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/determining-the-interval"], {
    en: "The site-link schedule must overlap the hours when the WAN is usable. The replication interval specifies frequency within the permitted window; inspect both rather than reading interval alone as the schedule.",
    fa: "زمان‌بندی پیوند سایت باید با ساعات دسترسی WAN هم‌پوشانی داشته باشد. فاصلهٔ تکثیر تعداد دفعات اجرا در پنجرهٔ مجاز را تعیین می‌کند؛ هر دو تنظیم را بررسی کنید.",
    de: "Der Site-Link-Zeitplan muss sich mit der WAN-Verfügbarkeit überschneiden. Das Intervall bestimmt die Häufigkeit innerhalb dieses Fensters; beide Einstellungen sind getrennt zu prüfen.",
  }, ["The schedule determines permitted replication windows.", "The interval applies while the window is open; default is 180 minutes and minimum is 15.", "Closed windows can explain delayed changes, but replication errors and connectivity must also be checked."], ["NTFS compression does not set the replication window.", "DHCP lease duration does not configure replication hours.", "", "A logon script does not determine site-link replication timing."], "Windows Server 2025 AD DS. Retrieve the extended ReplicationSchedule property explicitly, or inspect Change Schedule in the site-link properties.", [{ label: "Read the actual schedule as well as interval", command: "Get-ADReplicationSiteLink -Identity 'HQ-Branch' -Properties ReplicationSchedule | Select-Object Name,ReplicationFrequencyInMinutes,ReplicationSchedule" }]),

  "az802-q-039": reviewed([trustTypes, "https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-pac/55fc19f2-55ba-4251-8a6a-103dd7c66280"], {
    en: "Adding a child domain creates a two-way transitive parent-child trust inside the forest. Transitivity follows the forest trust path, while resource authorization remains separate.",
    fa: "با افزودن دامنهٔ فرزند، اعتماد دوطرفه و انتقال‌پذیر میان والد و فرزند در جنگل ایجاد می‌شود. مجوز استفاده از منابع همچنان جداگانه بررسی می‌شود.",
    de: "Eine neue untergeordnete Domäne erhält automatisch einen bidirektionalen, transitiven Parent-Child-Trust. Ressourcenberechtigungen bleiben eine separate Prüfung.",
  }, ["Parent-child trusts are automatically created within a forest.", "They are two-way and transitive by default.", "A trust enables an authentication path, not automatic permission to resources."], ["A child domain does receive an automatic trust.", "", "An external trust joins named domains across a forest boundary.", "Realm trusts serve interoperable Kerberos realms."], "Windows Server 2025 AD DS. SID filtering rules vary by trust boundary and quarantine settings; it is incorrect to claim that filtering applies only across forests.", [{ label: "Inspect trust properties", command: "Get-ADTrust -Filter * | Select-Object Name,Direction,IntraForest,ForestTransitive" }]),

  "az802-q-040": {
    ...reviewed([trust, trustTypes], { en: "An external trust is non-transitive and connects the specified domains in different forests. Select it for domain-scoped access, not simply because a relationship is temporary. /Realm creates a different, non-Windows Kerberos trust.", fa: "اعتماد خارجی فقط دامنه‌های مشخص در جنگل‌های متفاوت را به‌صورت غیرانتقال‌پذیر متصل می‌کند. معیار انتخاب، محدودبودن دامنهٔ دسترسی است، نه صرفاً مدت رابطه. ‎/Realm نوع دیگری از اعتماد Kerberos را می‌سازد.", de: "Ein externer Trust verbindet die benannten Domänen verschiedener Forests nichttransitiv. Entscheidend ist der begrenzte Domänenumfang, nicht die Dauer. /Realm erstellt einen anderen Kerberos-Realm-Trust." }, ["An external trust is scoped to the two named domains.", "It does not automatically include other domains in either forest.", "Use prompted credentials for an authorized lab change; do not embed passwords."], ["", "A parent-child trust connects domains in the same forest.", "Intrasite is a replication scope, not a trust type.", "Local trust is not the appropriate AD cross-forest trust type."], "Windows Server 2025 AD DS. Plan DNS, network connectivity, trust direction and resource permissions. This example creates an external domain trust; it does not create an AD forest trust.", [{ label: "Create an authorized lab external trust with credential prompts", command: "netdom trust resources.contoso.com /Domain:accounts.fabrikam.com /Add /UserO:admin@resources.contoso.com /PasswordO:* /UserD:admin@accounts.fabrikam.com /PasswordD:*" }, { label: "Read trust properties", command: "Get-ADTrust -Filter *" }]),
    text: "Which trust type connects only two specified domains in different forests without extending to their other domains?",
    textFa: "کدام نوع اعتماد فقط دو دامنهٔ مشخص در جنگل‌های متفاوت را متصل می‌کند و به دامنه‌های دیگر آن‌ها گسترش نمی‌یابد؟",
  },

  "az802-q-041": reviewed([trustTypes, trust], { en: "A forest trust connects the roots of two forests and provides an authentication path for their domains in the configured direction. It does not automatically extend through a third forest or grant resource access.", fa: "اعتماد جنگل ریشه‌های دو جنگل را متصل و در جهت تنظیم‌شده مسیر احراز هویت دامنه‌های آن‌ها را فراهم می‌کند. این اعتماد خودکار به جنگل سوم گسترش نمی‌یابد و مجوز منابع نمی‌دهد.", de: "Ein Forest-Trust verbindet zwei Forest-Wurzeln und ermöglicht Authentifizierung zwischen deren Domänen in der festgelegten Richtung. Er erweitert sich nicht automatisch auf einen dritten Forest und erteilt keine Ressourcenrechte." }, ["The relationship is established between forest root domains.", "It covers domains inside the two participating forests in the configured direction.", "Authentication mode and resource permissions remain separate controls."], ["DNS resolution is still required.", "A trust is not a local workstation group.", "A trust does not replicate file contents.", ""], "Windows Server 2025 AD DS. Both forests need forest-trust support, working DNS and connectivity. Use Active Directory Domains and Trusts to create an AD forest trust; netdom trust cannot create one."),

  "az802-q-042": reviewed([trust], { en: "Selective authentication requires approved partner users or groups to have Allowed to authenticate on the intended target computer. They must separately hold the permissions needed for the resource or application.", fa: "احراز هویت انتخابی نیازمند مجوز Allowed to authenticate برای کاربران یا گروه‌های شریک روی رایانهٔ هدف است. مجوز استفاده از منبع یا برنامه نیز جداگانه لازم است.", de: "Bei selektiver Authentifizierung benötigen zugelassene Partnerbenutzer Allowed to authenticate am Zielcomputer. Zusätzlich müssen die Ressourcen- oder Anwendungsrechte vorliegen." }, ["Selective authentication limits which computers partner identities can authenticate to.", "Allowed to authenticate is granted on the intended computer objects.", "Authentication approval does not grant file, application or administrative permissions."], ["Guest-only access is unrelated to approved cross-forest authentication.", "Automatic logon does not implement this trust gate.", "", "Anonymous access does not approve trusted identities."], "Windows Server 2025 AD DS. Configure selective authentication on the outbound forest or external trust viewed from the resource domain. Then approve target computers and grant resource access separately.", [{ label: "Configure an authorized lab outbound trust", command: "netdom trust resources.contoso.com /Domain:accounts.fabrikam.com /SelectiveAuth:yes" }]),

  "az802-q-052": reviewed([raise, levels, lower], { en: "Every DC in the domain must support the target domain functional level. Check OS inventory, replication and backups first. Supported lowering exists, but only within Microsoft's OS and enabled-feature restrictions.", fa: "همهٔ کنترل‌کننده‌های دامنه باید سطح عملکردی هدف را پشتیبانی کنند. ابتدا نسخهٔ سیستم‌عامل، تکثیر و پشتیبان‌ها را بررسی کنید. پایین‌آوردن سطح فقط تحت محدودیت‌های مستند Microsoft ممکن است.", de: "Jeder DC der Domäne muss die Ziel-Funktionsebene unterstützen. Prüfe Betriebssysteme, Replikation und Sicherungen. Ein Absenken ist nur unter Microsofts Versions- und Funktionsbedingungen möglich." }, ["Inventory all controllers in the domain against the target level.", "Verify healthy replication and backups before changing the level.", "Do not describe level changes as universally irreversible or freely reversible."], ["", "Deleting GCs is not a prerequisite.", "Replication must be healthy, not disabled.", "Existing trusts need not all be removed."], "Windows Server 2025 DCs support the 2016 and 2025 levels, not 2012 R2. A forest level cannot exceed its domain levels; raising an all-2025 forest to 2025 also raises its domains automatically.", [{ label: "Inventory controllers across domains", command: inventory }, { label: "Read levels", command: "Get-ADDomain | Select-Object DomainMode; Get-ADForest | Select-Object ForestMode" }]),

  "az802-q-053": reviewed([levels, raise], { en: "Domain functional level governs capabilities in one domain; forest functional level governs forest-wide capabilities. A domain level may be higher than its forest level but cannot be lower.", fa: "سطح عملکردی دامنه قابلیت‌های یک دامنه و سطح عملکردی جنگل قابلیت‌های کل جنگل را تعیین می‌کند. سطح دامنه می‌تواند از سطح جنگل بالاتر باشد ولی نمی‌تواند پایین‌تر باشد.", de: "Die Domänen-Funktionsebene steuert Fähigkeiten einer Domäne, die Forest-Funktionsebene forestweite Fähigkeiten. Eine Domänenebene darf höher, aber nicht niedriger als die Forest-Ebene sein." }, ["Domain and forest levels have different feature scopes.", "Both affect supported DC operating systems, not member-server or workstation OS requirements.", "The forest level cannot exceed the lowest domain level."], ["These levels are not DHCP versus DNS settings.", "They are not client versus printer settings.", "They are separate settings with different scopes.", ""], "Windows Server 2025 AD DS. Server 2019 and 2022 use the 2016 functional level; Server 2025 adds a 2025 level.", [{ label: "Compare current level scopes", command: "Get-ADDomain | Select-Object Name,DomainMode; Get-ADForest | Select-Object Name,ForestMode" }]),

  "az802-q-310": {
    ...reviewed([gcPlacement, replication], { en: "A GC lets the authenticating DC obtain universal group membership spanning the forest. The GC includes partial replicas of other domains; owning-domain DCs still hold their own universal group objects and memberships.", fa: "GC به کنترل‌کنندهٔ احراز هویت امکان دریافت عضویت گروه‌های Universal در سراسر جنگل را می‌دهد. GC نسخهٔ جزئی دامنه‌های دیگر را دارد؛ کنترل‌کننده‌های دامنهٔ مالک نیز اشیا و عضویت گروه‌های خود را نگه می‌دارند.", de: "Ein GC liefert dem authentifizierenden DC universelle Gruppenmitgliedschaften aus dem Forest. Andere Domänen liegen dort als Teilreplikate vor; die DCs der besitzenden Domäne halten ihre eigenen Gruppen und Mitgliedschaften weiterhin." }, ["Universal group membership can span domains in a forest.", "The authenticating DC uses GC information or an available UGMC cache.", "GCs do not automatically hold all application-directory partitions."], ["", "Universal group objects also replicate to DCs in the group's own domain.", "The Infrastructure Master is not the forest-wide membership lookup service.", "A normal DC can read groups and membership in its own domain."], "Windows Server 2025 AD DS. The DC, rather than the signing-in client, performs the group lookup needed for token construction. UGMC can reduce repeated remote GC access."),
    text: "Why is forest-wide universal group information in a global catalog useful during logon?",
    options: ["The authenticating domain controller can obtain universal group memberships that span the forest", "Universal groups replicate only to global catalogs and never to their own domain controllers", "The Infrastructure Master exclusively stores universal group memberships", "A normal domain controller cannot read universal groups in its own domain"],
    textFa: "چرا اطلاعات عضویت گروه‌های Universal سراسر جنگل در GC هنگام ورود مفید است؟",
    optionsFa: ["کنترل‌کنندهٔ احراز هویت می‌تواند عضویت گروه‌های Universal سراسر جنگل را دریافت کند", "گروه‌های Universal فقط به GC و هرگز به کنترل‌کننده‌های دامنهٔ خود تکثیر نمی‌شوند", "فقط Infrastructure Master عضویت گروه‌های Universal را نگه می‌دارد", "کنترل‌کنندهٔ عادی نمی‌تواند گروه‌های Universal دامنهٔ خودش را بخواند"],
  },

  "az802-q-311": {
    ...reviewed([gcPlacement, replication, "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adforest?view=windowsserver2025-ps"], { en: "A local GC improves forest-wide search and multidomain logon performance when WAN access is slow or unreliable. UGMC can be an alternative for membership lookups, so a GC is not mandatory in every site.", fa: "GC محلی در شرایط WAN کند یا نامطمئن، جست‌وجوی جنگل و ورود چنددامنه‌ای را بهبود می‌دهد. UGMC می‌تواند جایگزینی برای جست‌وجوی عضویت باشد؛ پس وجود GC در هر سایت الزامی نیست.", de: "Ein lokaler GC verbessert forestweite Suchen und multidomänige Anmeldungen bei langsamen oder unzuverlässigen WAN-Verbindungen. UGMC kann Mitgliedschaftsabfragen abdecken; deshalb ist ein GC nicht in jedem Site zwingend erforderlich." }, ["Only designated GC servers provide GC query service.", "A local GC reduces dependence on the WAN for GC-dependent operations.", "UGMC caches membership information but does not serve GC searches."], ["A GC can answer queries from other sites when reachable.", "", "A forest can contain many GC servers.", "Functional level does not automatically place GCs in sites."], "Windows Server 2025 AD DS. Choose placement based on application needs, users, bandwidth and resilience. UGMC needs initial lookup and cache refresh from a reachable GC.", [{ label: "List designated GC servers", command: "Get-ADForest | Select-Object -ExpandProperty GlobalCatalogs" }, { label: "Inspect a known DC", command: "Get-ADDomainController -Identity DC01 | Select-Object HostName,Site,IsGlobalCatalog" }]),
    text: "Why might an administrator place a global catalog in a remote site in a multidomain forest?",
    textFa: "چرا مدیر ممکن است در یک سایت دورافتادهٔ جنگل چنددامنه‌ای GC قرار دهد؟",
    options: ["A global catalog is read-only, so it can only serve clients in its own site", "To reduce WAN dependence for GC-dependent searches and multidomain logons", "A domain can hold only one global catalog across the whole forest", "Global catalog placement is decided by the Forest Functional Level"],
    optionsFa: ["چون GC فقط‌خواندنی است، فقط به کلاینت‌های سایت خودش خدمت می‌دهد", "برای کاهش وابستگی به WAN در جست‌وجوهای وابسته به GC و ورود چنددامنه‌ای", "یک دامنه در کل جنگل فقط می‌تواند یک GC داشته باشد", "محل GC توسط Forest Functional Level تعیین می‌شود"],
  },

  "az802-q-312": {
    ...reviewed(["https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/adac/advanced-ad-ds-management-using-active-directory-administrative-center--level-200-", levels, "https://learn.microsoft.com/en-us/powershell/module/activedirectory/get-adoptionalfeature?view=windowsserver2025-ps"], { en: "AD Recycle Bin is a forest-wide optional feature whose minimum forest functional level is Windows Server 2008 R2. Meeting the level does not enable it automatically, and enabling it is irreversible.", fa: "سطل بازیافت AD قابلیتی اختیاری در سطح جنگل است که حداقل سطح عملکردی Windows Server 2008 R2 را نیاز دارد. رسیدن به این سطح آن را خودکار فعال نمی‌کند و فعال‌سازی برگشت‌ناپذیر است.", de: "Der AD-Papierkorb ist ein optionales forestweites Feature mit mindestens Windows-Server-2008-R2-Forest-Ebene. Die Ebene aktiviert es nicht automatisch; das Einschalten ist irreversibel." }, ["AD Recycle Bin is controlled at forest scope.", "The minimum feature requirement is the Windows Server 2008 R2 forest functional level.", "A level change and enabling the optional feature are separate actions."], ["Domain level alone is not the feature's forest-wide prerequisite.", "Client OS version is not the feature scope.", "", "A site-link schedule controls replication timing, not Recycle Bin eligibility."], "Windows Server 2025 AD DS. Existing 2025 DCs require at least the 2016 functional level, which exceeds this feature's historical minimum. Enabling AD Recycle Bin requires Enterprise Admin permissions and cannot be undone.", [{ label: "Inspect feature state without enabling it", command: "Get-ADOptionalFeature -Filter 'Name -eq \"Recycle Bin Feature\"' | Select-Object Name,RequiredForestMode,EnabledScopes" }, { label: "Read current forest mode", command: "Get-ADForest | Select-Object Name,ForestMode" }]),
    text: "An administrator plans to enable AD Recycle Bin. Which functional-level setting supplies its forest-wide prerequisite?",
    options: ["Only the domain functional level of the root domain", "The operating system version of domain-joined workstations", "The forest functional level", "The site-link replication schedule"], correct: 2,
    textFa: "مدیر قصد دارد سطل بازیافت AD را فعال کند. کدام تنظیم سطح عملکردی پیش‌نیاز آن را در کل جنگل تعیین می‌کند؟",
    optionsFa: ["فقط سطح عملکردی دامنهٔ ریشه", "نسخهٔ سیستم‌عامل ایستگاه‌های کاری عضو دامنه", "سطح عملکردی جنگل", "زمان‌بندی تکثیر پیوند سایت"],
  },

  "az802-q-313": reviewed([levels, raise, lower], { en: "Functional level determines AD DS capabilities and DC operating-system compatibility. It does not choose the PDC role holder or restrict workstation operating systems. Supported lowering is conditional on enabled features and version compatibility.", fa: "سطح عملکردی قابلیت‌های AD DS و سازگاری سیستم‌عامل کنترل‌کننده‌ها را تعیین می‌کند؛ دارندهٔ PDC یا سیستم‌عامل کلاینت‌ها را انتخاب نمی‌کند. پایین‌آوردن سطح به سازگاری نسخه و ویژگی‌های فعال وابسته است.", de: "Die Funktionsebene bestimmt AD-DS-Fähigkeiten und die Betriebssystemkompatibilität der DCs. Sie wählt weder den PDC-Inhaber noch Client-Betriebssysteme aus. Ein Absenken unterliegt Funktions- und Versionsbedingungen." }, ["A minimum level in feature documentation identifies required AD DS capabilities.", "The level constrains supported DC versions, not workstation or member-server versions.", "Use Set-ADDomainMode for a domain-level change; supported rollback is conditional."], ["", "Workstation and member-server OS compatibility is not determined by this level.", "The PDC role holder is selected independently through FSMO role management.", "The level is not a general application connection allowlist."], "Windows Server 2025 DCs require at least the 2016 functional level. Documented lowering requires supported target levels, no incompatible enabled features and a target domain mode not below the forest mode.", [{ label: "Read domain mode", command: "Get-ADDomain | Select-Object Name,DomainMode" }, { label: "Example authorized lab level change", command: "Set-ADDomainMode -Identity corp.contoso.com -DomainMode Windows2016Domain" }]),

  "az802-q-315": {
    ...reviewed([trust, trustQuery], { en: "Viewed from the resource forest, an outgoing trust means it trusts identities from the account forest. The account forest sees the same relationship as incoming. Authentication follows toward resources, with authorization checked separately.", fa: "از دید جنگل منابع، اعتماد خروجی یعنی هویت‌های جنگل حساب‌ها مورد اعتمادند. جنگل حساب‌ها همین رابطه را ورودی می‌بیند. احراز هویت به‌سوی منابع انجام می‌شود و مجوز دسترسی جداگانه بررسی می‌شود.", de: "Aus Sicht des Ressourcen-Forests vertraut ein ausgehender Trust den Identitäten des Konten-Forests. Dort erscheint dieselbe Beziehung als eingehend. Die Ressourcenberechtigung wird separat geprüft." }, ["Trust direction is relative to the side from which it is viewed.", "The resource forest is trusting; the account forest is trusted.", "Selective authentication and resource ACLs control additional access conditions; they do not reverse the direction."], ["Selective authentication adds target approval; it does not specify trust direction.", "Transitivity specifies scope, not the required one-way direction.", "", "A firewall does not determine the trust's authentication direction."], "Windows Server 2025 AD DS. Record Source and Target when interpreting Direction. Selective authentication must also approve target computers when enabled.", [{ label: "Read trust direction from the current domain", command: "Get-ADTrust -Filter * | Select-Object Source,Target,Direction,ForestTransitive,SelectiveAuthentication" }]),
    text: "Viewed from the resource forest, which one-way trust permits users in the account forest to authenticate to its resources?",
    options: ["Selective authentication without a trust", "Transitivity without a direction", "An outgoing trust from the resource forest to the account forest", "A firewall rule without a trust"], correct: 2,
    textFa: "از دید جنگل منابع، کدام اعتماد یک‌طرفه به کاربران جنگل حساب‌ها اجازه می‌دهد برای منابع آن احراز هویت شوند؟",
    optionsFa: ["احراز هویت انتخابی بدون اعتماد", "انتقال‌پذیری بدون جهت", "اعتماد خروجی از جنگل منابع به جنگل حساب‌ها", "قانون فایروال بدون اعتماد"],
  },
};
