export type Az900Text = { fa: string; en: string; de: string };

export type Az900Question = {
  id: string;
  courseId: "az900";
  domain: string;
  objectiveGroupId: string;
  objectiveId: string;
  text: string;
  options: string[];
  correct: number;
  source: string;
  rationale: Az900Text;
  skillId: string;
  reviewStatus: "draft" | "audited" | "technical-approved" | "published" | "rejected";
  isOriginal: true;
};

const GUIDE = "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-900";
const CERTIFICATION = "https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/";
const sources = {
  cloud: "https://learn.microsoft.com/en-us/training/modules/describe-cloud-compute/",
  benefits: "https://learn.microsoft.com/en-us/training/modules/describe-benefits-use-cloud-services/",
  serviceTypes: "https://learn.microsoft.com/en-us/training/modules/describe-cloud-service-types/",
  architecture: "https://learn.microsoft.com/en-us/training/modules/describe-core-architectural-components-of-azure/",
  compute: "https://learn.microsoft.com/en-us/training/modules/describe-azure-compute-networking-services/",
  storage: "https://learn.microsoft.com/en-us/training/modules/describe-azure-storage-services/",
  identity: "https://learn.microsoft.com/en-us/training/modules/describe-azure-identity-access-security/",
  cost: "https://learn.microsoft.com/en-us/training/modules/describe-cost-management-azure/",
  governance: "https://learn.microsoft.com/en-us/training/modules/describe-features-tools-azure-for-governance-compliance/",
  management: "https://learn.microsoft.com/en-us/training/modules/describe-features-tools-manage-deploy-azure-resources/",
  monitoring: "https://learn.microsoft.com/en-us/training/modules/describe-monitoring-tools-azure/",
} as const;

export const az900Domains = [
  "Describe cloud concepts",
  "Describe Azure architecture and services",
  "Describe Azure management and governance",
] as const;

type Topic = {
  key: string;
  group: string;
  domain: typeof az900Domains[number];
  term: string;
  definition: string;
  scenario: string;
  statement: string;
  distractors: [string, string, string];
  misconceptions: [string, string, string];
  source: string;
};

const D1 = az900Domains[0];
const D2 = az900Domains[1];
const D3 = az900Domains[2];

const topics: Topic[] = [
  { key:"cloud-definition", group:"cloud-computing", domain:D1, term:"Cloud computing", definition:"Delivery of computing services over the internet using on-demand resources", scenario:"obtain compute and storage on demand without first owning the physical datacenter", statement:"Cloud computing makes shared technology resources available on demand through a network.", distractors:["Colocation only","Local virtualization only","Offline batch processing"], misconceptions:["It always requires buying the underlying hardware","It can operate only as a public cloud","It removes every operational responsibility from the customer"], source:sources.cloud },
  { key:"shared-responsibility", group:"cloud-computing", domain:D1, term:"Shared responsibility model", definition:"Allocation of security and operational duties between a cloud provider and its customer", scenario:"determine whether Microsoft or the customer patches a guest operating system", statement:"Customer responsibilities generally increase as a service provides more customer control.", distractors:["Consumption model","Defense in depth","Economies of scale"], misconceptions:["The provider is responsible for all customer data classifications","The customer is responsible for physical Azure datacenter security","Responsibilities never change across IaaS, PaaS, and SaaS"], source:sources.cloud },
  { key:"cloud-models", group:"cloud-computing", domain:D1, term:"Public cloud", definition:"Cloud services offered over public networks on infrastructure owned by a cloud provider", scenario:"start quickly without purchasing a private datacenter and share provider infrastructure securely with other tenants", statement:"A public cloud uses provider-owned infrastructure while logically isolating customer workloads.", distractors:["Private cloud","Hybrid cloud","On-premises colocation"], misconceptions:["Every customer can access every other customer's data","The customer owns the provider datacenter","It cannot support enterprise governance"], source:sources.cloud },
  { key:"cloud-model-use-cases", group:"cloud-computing", domain:D1, term:"Private cloud", definition:"A cloud environment dedicated to a single organization", scenario:"retain dedicated infrastructure under one organization's exclusive control", statement:"A private cloud provides cloud characteristics on resources dedicated to one organization.", distractors:["Public cloud","Hybrid cloud","Community CDN"], misconceptions:["It must be hosted by Microsoft Azure","It has no management overhead","It always costs less than public cloud"], source:sources.cloud },
  { key:"cloud-model-use-cases", group:"cloud-computing", domain:D1, term:"Hybrid cloud", definition:"An environment that connects public cloud and private or on-premises resources", scenario:"keep regulated data on-premises while bursting selected workloads into Azure", statement:"Hybrid cloud combines environments and enables data or applications to move between them where appropriate.", distractors:["Public cloud only","Private cloud only","SaaS only"], misconceptions:["It requires every workload to run twice","It eliminates network planning","It is another name for multitenancy"], source:sources.cloud },
  { key:"consumption-model", group:"cloud-computing", domain:D1, term:"Consumption-based model", definition:"Paying for resources according to actual usage", scenario:"align monthly cost with the amount of compute consumed", statement:"Consumption pricing can turn large upfront capital spending into usage-based operational spending.", distractors:["Perpetual licensing only","Fixed-capacity procurement","Physical asset depreciation"], misconceptions:["Charges never change with usage","All services have one identical meter","Unused resources can never create cost"], source:sources.cloud },
  { key:"pricing-models", group:"cloud-computing", domain:D1, term:"Reserved pricing", definition:"A pricing option that can lower cost when a predictable level of use is committed in advance", scenario:"reduce cost for a stable, long-running workload with predictable capacity", statement:"Commitment-based pricing can be economical for predictable workloads, while pay-as-you-go favors flexibility.", distractors:["Pay-as-you-go only","Spot pricing only","Capital expenditure only"], misconceptions:["It is always best for temporary experiments","It removes the need to right-size resources","It guarantees that every Azure service is free"], source:sources.cloud },
  { key:"serverless", group:"cloud-computing", domain:D1, term:"Serverless computing", definition:"Running application code without managing the underlying server infrastructure", scenario:"execute event-driven code and pay primarily for executions without administering virtual machines", statement:"Serverless platforms abstract server management and can scale execution in response to events.", distractors:["Dedicated physical host","Traditional colocation","Manual VM cluster"], misconceptions:["No servers exist anywhere","The customer must patch the host operating system","It can never scale to zero"], source:sources.cloud },

  { key:"availability-scalability", group:"cloud-benefits", domain:D1, term:"High availability", definition:"Keeping a service accessible despite component failures", scenario:"design an application to remain reachable when a single instance fails", statement:"High availability uses redundancy and resilient design to reduce service interruption.", distractors:["Vertical scaling","Capital expenditure","Data classification"], misconceptions:["It guarantees that failures never happen","It is identical to adding CPU to one server","It removes the need to plan recovery"], source:sources.benefits },
  { key:"availability-scalability", group:"cloud-benefits", domain:D1, term:"Scalability", definition:"Adjusting resources to meet changing demand", scenario:"add or remove application capacity as traffic changes", statement:"Scaling out adds instances, while scaling up increases the capacity of an existing instance.", distractors:["Data sovereignty","Resource locking","Availability zoning"], misconceptions:["It only means buying a larger server","It prevents every outage","It requires permanently running peak capacity"], source:sources.benefits },
  { key:"reliability-predictability", group:"cloud-benefits", domain:D1, term:"Reliability and predictability", definition:"Designing repeatable performance and recovery behavior with resilient cloud services", scenario:"use documented service capabilities and monitoring to plan expected performance and recovery", statement:"Cloud reliability combines resilient architecture with measurable, predictable operational behavior.", distractors:["Unmanaged elasticity","Single-instance hosting","Unlimited best effort"], misconceptions:["Predictability means the bill can never vary","Reliability needs no redundancy","A service-level agreement is a personal guarantee of zero downtime"], source:sources.benefits },
  { key:"security-governance-benefits", group:"cloud-benefits", domain:D1, term:"Cloud security and governance", definition:"Central controls and provider capabilities that help protect and standardize cloud resources", scenario:"apply consistent policy and security recommendations across many subscriptions", statement:"Cloud platforms provide controls that support security, compliance, and consistent governance at scale.", distractors:["Local-only administration","Uncontrolled self-service","Hardware ownership"], misconceptions:["Governance prevents all authorized change","Security becomes solely the provider's job","Policies replace identity and access controls"], source:sources.benefits },
  { key:"manageability", group:"cloud-benefits", domain:D1, term:"Cloud manageability", definition:"Managing resources through portals, APIs, command-line tools, templates, and automation", scenario:"deploy the same approved configuration repeatedly and manage it remotely", statement:"Cloud resources can be administered programmatically and through centralized management interfaces.", distractors:["Manual hardware procurement","Paper-based change control","Physical console access only"], misconceptions:["Automation is unavailable in public cloud","Every resource must be configured individually","Remote management always requires a site visit"], source:sources.benefits },

  { key:"iaas", group:"service-models", domain:D1, term:"Infrastructure as a service (IaaS)", definition:"Cloud-hosted compute, networking, and storage where the customer manages operating systems and applications", scenario:"migrate a custom server application while retaining control of the guest operating system", statement:"IaaS gives customers substantial control but also responsibility for guest operating systems and applications.", distractors:["Platform as a service (PaaS)","Software as a service (SaaS)","Business process as a service"], misconceptions:["The provider manages every installed application","Customers manage physical datacenter security","It cannot use virtual machines"], source:sources.serviceTypes },
  { key:"paas", group:"service-models", domain:D1, term:"Platform as a service (PaaS)", definition:"A managed application platform where the provider operates the underlying infrastructure and runtime", scenario:"deploy web code without patching the operating system or web server", statement:"PaaS reduces infrastructure administration while leaving the customer responsible for application code and data.", distractors:["Infrastructure as a service (IaaS)","Software as a service (SaaS)","Private datacenter"], misconceptions:["The customer patches the physical hosts","No application development is required","It provides less abstraction than IaaS"], source:sources.serviceTypes },
  { key:"saas", group:"service-models", domain:D1, term:"Software as a service (SaaS)", definition:"A complete provider-hosted application consumed by users", scenario:"use email and collaboration software without deploying or maintaining the application", statement:"With SaaS, customers configure and use an application while the provider operates most of the stack.", distractors:["Infrastructure as a service (IaaS)","Platform as a service (PaaS)","Bare-metal hosting"], misconceptions:["Customers maintain the application binaries","The provider has no security responsibility","SaaS always requires customer-managed virtual machines"], source:sources.serviceTypes },
  { key:"service-model-choice", group:"service-models", domain:D1, term:"Service-model selection", definition:"Choosing IaaS, PaaS, or SaaS according to the control and management responsibility required", scenario:"match a workload to the least operational responsibility that still provides required control", statement:"The appropriate service model balances customization needs against the amount of management the customer accepts.", distractors:["Region pairing","Resource tagging","Network peering"], misconceptions:["One service model is best for every workload","SaaS always offers the most operating-system control","IaaS always has the least customer responsibility"], source:sources.serviceTypes },

  { key:"regions-pairs-sovereign", group:"azure-architecture", domain:D2, term:"Azure region", definition:"A geographic area containing one or more nearby Azure datacenters", scenario:"choose the broad Azure location in which to deploy resources for latency or residency requirements", statement:"Regions provide geographic locations for Azure resources, subject to service availability and residency requirements.", distractors:["Availability zone","Resource group","Management group"], misconceptions:["A region is a single rack","Every Azure service is available in every region","Regions exist only for billing"], source:sources.architecture },
  { key:"regions-pairs-sovereign", group:"azure-architecture", domain:D2, term:"Region pairs and sovereign regions", definition:"Regional relationships for resilience and specialized isolated regions for legal or compliance needs", scenario:"distinguish paired recovery geography from a region built for a specific government or jurisdiction", statement:"Region pairs can support resilience planning, while sovereign regions address specific regulatory boundaries.", distractors:["Availability sets","Resource groups","Virtual networks"], misconceptions:["Sovereign regions are public subnets","Every region pair guarantees automatic application failover","Region pairs and availability zones are identical"], source:sources.architecture },
  { key:"availability-zones", group:"azure-architecture", domain:D2, term:"Availability zones", definition:"Physically separate datacenter locations within an Azure region with independent power, cooling, and networking", scenario:"protect a regional workload from the failure of one datacenter location", statement:"Zonal design can improve resilience against a datacenter-level failure within a supported region.", distractors:["Management groups","Subscriptions","Resource tags"], misconceptions:["Zones are separate Azure tenants","Every service is automatically zone redundant","A zone spans multiple regions"], source:sources.architecture },
  { key:"datacenters", group:"azure-architecture", domain:D2, term:"Azure datacenters", definition:"Physical facilities containing networked compute, storage, and infrastructure used to deliver Azure services", scenario:"identify the physical facility layer beneath regions and availability zones", statement:"Datacenters house the physical systems that deliver Azure services.", distractors:["Resource groups","Subscriptions","ARM templates"], misconceptions:["Customers normally rack their own Azure hardware there","A datacenter is a billing boundary","Each subscription owns a dedicated datacenter"], source:sources.architecture },
  { key:"resources-groups", group:"azure-architecture", domain:D2, term:"Resource group", definition:"A logical container for Azure resources that are managed together", scenario:"organize lifecycle-related resources so they can be deployed, monitored, and removed as a unit", statement:"Every Azure resource belongs to one resource group, and a resource group can contain resources from different regions.", distractors:["Management group","Availability zone","Tenant domain"], misconceptions:["A resource can belong to multiple resource groups simultaneously","Resource groups are physical datacenters","A resource group can contain subscriptions"], source:sources.architecture },
  { key:"subscriptions", group:"azure-architecture", domain:D2, term:"Azure subscription", definition:"A management, billing, and access boundary for Azure resources", scenario:"separate billing and access for production and development environments", statement:"Subscriptions provide boundaries for billing, quotas, and access management.", distractors:["Resource group","Availability set","Network security group"], misconceptions:["A subscription is a single virtual machine","Subscriptions cannot share a Microsoft Entra tenant","A subscription contains management groups"], source:sources.architecture },
  { key:"management-groups", group:"azure-architecture", domain:D2, term:"Management group", definition:"A governance scope above subscriptions used to apply policy and access consistently", scenario:"apply governance to many subscriptions in a hierarchy", statement:"Management groups organize subscriptions so governance can inherit down the hierarchy.", distractors:["Resource group","Availability zone","Storage account"], misconceptions:["Management groups contain individual virtual machine disks","They are below resource groups in the hierarchy","They replace Microsoft Entra ID"], source:sources.architecture },
  { key:"scope-hierarchy", group:"azure-architecture", domain:D2, term:"Management hierarchy", definition:"The relationship management group → subscription → resource group → resource", scenario:"choose the correct scope at which a policy should inherit to all child subscriptions", statement:"Azure governance can be assigned at higher scopes and inherited by lower scopes.", distractors:["Zone → region → tenant → resource","Resource → group → datacenter → cloud","VNet → subnet → subscription → tenant"], misconceptions:["Resource groups contain subscriptions","Resources are above management groups","Hierarchy has no effect on policy scope"], source:sources.architecture },

  { key:"compute-types", group:"compute-networking", domain:D2, term:"Compute type selection", definition:"Choosing virtual machines, containers, or functions based on control, portability, and execution pattern", scenario:"compare full operating-system control, packaged applications, and event-driven code", statement:"Virtual machines expose an OS, containers package applications, and functions suit event-driven serverless execution.", distractors:["Storage tier selection","Identity federation","Cost tagging"], misconceptions:["Containers always require one VM per container","Functions require customer-managed guest patching","Virtual machines contain no operating system"], source:sources.compute },
  { key:"vm-options", group:"compute-networking", domain:D2, term:"Azure virtual machine options", definition:"VMs, scale sets, availability sets, and Azure Virtual Desktop for different compute and desktop needs", scenario:"select between one VM, an automatically scaled VM fleet, fault-domain grouping, and hosted desktops", statement:"VM Scale Sets manage groups of similar VMs, while Azure Virtual Desktop delivers remote desktop and app experiences.", distractors:["Storage accounts","Azure Policy","Microsoft Purview"], misconceptions:["Availability sets automatically scale VM count","Azure Virtual Desktop is a storage redundancy option","Scale sets can contain only one VM"], source:sources.compute },
  { key:"vm-resources", group:"compute-networking", domain:D2, term:"Virtual machine dependencies", definition:"Compute size, disks, network interfaces, virtual networks, and related resources needed by an Azure VM", scenario:"plan all resources required before deploying a VM", statement:"An Azure VM commonly depends on disks and networking resources in addition to its selected size and image.", distractors:["Only a resource tag","Only a DNS label","Only a subscription name"], misconceptions:["A VM never needs storage","A network interface cannot connect to a subnet","VM size has no effect on capacity or cost"], source:sources.compute },
  { key:"app-hosting", group:"compute-networking", domain:D2, term:"Application hosting choice", definition:"Selecting Web Apps, containers, or VMs according to application and administration needs", scenario:"host a web application using the most managed platform that still meets runtime requirements", statement:"Azure App Service offers managed web hosting, while containers and VMs provide different levels of portability and control.", distractors:["Azure Policy assignment","Storage lifecycle rule","Management group"], misconceptions:["Web Apps require customer-managed physical servers","Containers are a governance scope","VMs always require less administration than PaaS"], source:sources.compute },
  { key:"virtual-networking", group:"compute-networking", domain:D2, term:"Azure virtual networking", definition:"VNets, subnets, peering, DNS, VPN Gateway, and ExpressRoute used to connect and segment workloads", scenario:"design private address spaces, subnets, name resolution, and connectivity between networks", statement:"A VNet provides private networking; peering connects VNets, while VPN Gateway and ExpressRoute support hybrid connectivity.", distractors:["Azure Files","Microsoft Purview","Cost Management"], misconceptions:["Subnets can span unrelated VNets","Peering encrypts traffic through the public internet by definition","Azure DNS is a virtual machine scale service"], source:sources.compute },
  { key:"endpoints", group:"compute-networking", domain:D2, term:"Public and private endpoints", definition:"Network access points that expose a service through public addressing or privately inside a VNet", scenario:"keep access to a supported Azure service on private addressing from a virtual network", statement:"A private endpoint assigns a private IP in a VNet for supported services; a public endpoint is reachable through public addressing subject to controls.", distractors:["Resource lock","Management group","Availability set"], misconceptions:["Private endpoints create public IP addresses","Public endpoints bypass all authentication","An endpoint is a cost-management tag"], source:sources.compute },

  { key:"storage-services", group:"storage-services", domain:D2, term:"Azure Storage service selection", definition:"Choosing Blob, Files, Queue, Table, or managed disks according to the data pattern", scenario:"match object, shared-file, message, key-value, or VM-disk data to the appropriate service", statement:"Azure Storage provides distinct services optimized for objects, file shares, queues, NoSQL key-value data, and disks.", distractors:["Azure Policy","Azure Functions","Microsoft Entra ID"], misconceptions:["Blob Storage is an SMB file share by definition","Queue Storage is a relational database","Managed disks are used for email distribution lists"], source:sources.storage },
  { key:"storage-tiers", group:"storage-services", domain:D2, term:"Blob access tiers", definition:"Hot, cool, cold, and archive choices that trade access cost against storage cost and retrieval characteristics", scenario:"lower storage cost for infrequently accessed data while considering retrieval time and charges", statement:"Choose an access tier from the expected access frequency, retention, retrieval time, and cost pattern.", distractors:["Availability zones","RBAC roles","Management groups"], misconceptions:["Archive data is intended for frequent low-latency access","Every tier has identical retrieval behavior","Changing access patterns never affects cost"], source:sources.storage },
  { key:"storage-redundancy", group:"storage-services", domain:D2, term:"Storage redundancy", definition:"Replication choices such as LRS, ZRS, GRS, and GZRS that protect copies across different scopes", scenario:"select local, zonal, or geographic replication according to durability and availability requirements", statement:"Redundancy options differ in whether copies stay in one datacenter, span zones, or replicate to a secondary region.", distractors:["Storage Explorer","AzCopy","Azure File Sync"], misconceptions:["LRS replicates to a second region","ZRS stores only one copy","Geo-redundancy automatically meets every application recovery requirement"], source:sources.storage },
  { key:"storage-accounts", group:"storage-services", domain:D2, term:"Storage account", definition:"The Azure resource that provides a namespace, configuration, and access boundary for storage services", scenario:"configure performance, redundancy, and supported storage services under one Azure resource", statement:"Storage account type and configuration determine supported services, performance, redundancy, and features.", distractors:["Management group","Availability set","Microsoft Entra tenant"], misconceptions:["Storage accounts contain subscriptions","Every storage account has identical capabilities","A storage account is a physical tape library"], source:sources.storage },
  { key:"file-movement", group:"storage-services", domain:D2, term:"Azure file movement tools", definition:"AzCopy, Storage Explorer, and Azure File Sync for command-line transfer, graphical management, and synchronized file shares", scenario:"choose a command-line copy tool, graphical storage tool, or hybrid file synchronization service", statement:"AzCopy handles scripted transfers, Storage Explorer offers a GUI, and Azure File Sync caches and synchronizes Azure file shares with Windows Server.", distractors:["Azure Policy","Azure Advisor","Microsoft Purview"], misconceptions:["AzCopy is a governance hierarchy","Storage Explorer is a physical appliance","Azure File Sync is only a billing calculator"], source:sources.storage },
  { key:"migration-options", group:"storage-services", domain:D2, term:"Azure migration options", definition:"Azure Migrate for assessment and migration, and Azure Data Box for transferring large datasets with an appliance", scenario:"assess servers for migration or move very large data when network transfer is impractical", statement:"Azure Migrate helps discover and assess workloads; Data Box supports offline transfer of large data volumes.", distractors:["Azure Monitor","Microsoft Entra ID","Azure Policy"], misconceptions:["Data Box is an identity provider","Azure Migrate is only a cost tag","Data Box requires all data to cross the internet in real time"], source:sources.storage },

  { key:"directory-services", group:"identity-security", domain:D2, term:"Microsoft Entra directory services", definition:"Microsoft Entra ID for cloud identity and Microsoft Entra Domain Services for managed domain capabilities", scenario:"choose cloud identity or managed domain join, LDAP, Kerberos, and NTLM capabilities", statement:"Microsoft Entra ID is a cloud identity service; Domain Services adds managed traditional domain capabilities without customer-managed domain controllers.", distractors:["Azure DNS","Azure Files","Azure Monitor"], misconceptions:["Microsoft Entra ID is a customer-managed Windows domain controller","Domain Services requires customers to patch domain controllers","Directory services are storage access tiers"], source:sources.identity },
  { key:"authentication", group:"identity-security", domain:D2, term:"Azure authentication methods", definition:"SSO, MFA, and passwordless methods used to verify identities", scenario:"reduce password dependence and require more than one factor for sensitive access", statement:"MFA combines factors, SSO reduces repeated sign-ins, and passwordless methods can remove passwords from the sign-in flow.", distractors:["Storage redundancy","Resource tagging","Network peering"], misconceptions:["SSO means no authentication occurs","MFA uses two passwords as two independent factors","Passwordless always means anonymous access"], source:sources.identity },
  { key:"external-identities", group:"identity-security", domain:D2, term:"External identities", definition:"Capabilities for securely collaborating with users outside an organization", scenario:"invite a partner user to access selected applications without creating a full internal employee identity", statement:"External identities support controlled collaboration and customer or partner access scenarios.", distractors:["Availability zones","Storage tiers","Resource locks"], misconceptions:["External users automatically become global administrators","Guest access bypasses Conditional Access","External identity is a disk encryption method"], source:sources.identity },
  { key:"conditional-access", group:"identity-security", domain:D2, term:"Microsoft Entra Conditional Access", definition:"Policy-based access decisions using signals such as user, device, location, risk, and application", scenario:"require MFA for risky sign-ins or block access from an untrusted context", statement:"Conditional Access evaluates signals and enforces access controls after first-factor authentication.", distractors:["Azure Data Box","Azure Files","Availability set"], misconceptions:["It is a physical firewall appliance","It replaces all authentication","It controls storage redundancy"], source:sources.identity },
  { key:"rbac", group:"identity-security", domain:D2, term:"Azure role-based access control (RBAC)", definition:"Authorization that grants allowed actions to security principals at an Azure scope", scenario:"allow an operations group to restart VMs in one resource group without managing unrelated resources", statement:"RBAC assignments combine a security principal, role definition, and scope to enforce least privilege.", distractors:["Azure Policy","Resource lock","Availability zone"], misconceptions:["RBAC evaluates whether resource configuration is compliant","RBAC protects against accidental deletion without permissions","Every role assignment must apply to the entire tenant"], source:sources.identity },
  { key:"zero-trust", group:"identity-security", domain:D2, term:"Zero Trust", definition:"A security model that explicitly verifies, uses least privilege, and assumes breach", scenario:"continuously validate access instead of trusting traffic solely because it originates inside a network", statement:"Zero Trust follows verify explicitly, use least privilege, and assume breach principles.", distractors:["Trust every internal device","Perimeter-only security","Anonymous administration"], misconceptions:["It means block every request","It trusts all corporate-network traffic automatically","It removes the need for monitoring"], source:sources.identity },
  { key:"defense-depth", group:"identity-security", domain:D2, term:"Defense in depth", definition:"Layering controls across physical security, identity, perimeter, network, compute, applications, and data", scenario:"ensure that failure of one security control does not leave a workload unprotected", statement:"Layered security controls reduce reliance on any single defensive measure.", distractors:["Single perimeter firewall","One shared administrator account","One backup copy"], misconceptions:["Only the network layer matters","Each layer must use the same control","It eliminates the shared responsibility model"], source:sources.identity },
  { key:"defender-cloud", group:"identity-security", domain:D2, term:"Microsoft Defender for Cloud", definition:"Cloud security posture management and workload protection recommendations across supported environments", scenario:"review security recommendations and improve the posture of Azure and connected resources", statement:"Defender for Cloud assesses security posture and provides recommendations and workload protection capabilities.", distractors:["Azure Pricing Calculator","Azure Data Box","Azure DNS"], misconceptions:["It is a file synchronization tool","It replaces Microsoft Entra authentication","It is only a monthly invoice viewer"], source:sources.identity },

  { key:"cost-factors", group:"cost-management", domain:D3, term:"Azure cost factors", definition:"Resource type, usage, region, data transfer, purchasing option, and other choices that influence cost", scenario:"explain why two deployments of a similar workload can have different monthly cost", statement:"Azure cost depends on configuration and consumption factors, not only the resource name.", distractors:["Only the tenant name","Only the administrator count","Only the resource-group color"], misconceptions:["Region can never affect price","Stopped and deallocated are always billed identically for compute","Outbound data transfer can never affect cost"], source:sources.cost },
  { key:"pricing-calculator", group:"cost-management", domain:D3, term:"Azure Pricing Calculator", definition:"A planning tool for estimating Azure service costs before deployment", scenario:"compare estimated monthly costs for candidate architectures", statement:"The pricing calculator creates estimates from selected services, regions, sizes, and expected usage.", distractors:["Azure Service Health","Azure Policy","Application Insights"], misconceptions:["It is the final legal invoice","It deploys every selected resource","It diagnoses application exceptions"], source:sources.cost },
  { key:"cost-management", group:"cost-management", domain:D3, term:"Microsoft Cost Management", definition:"Capabilities for analyzing spending, creating budgets, allocating costs, and configuring alerts", scenario:"track actual cloud spend and notify owners when a budget threshold is approached", statement:"Cost Management supports analysis, budgets, alerts, and cost allocation views.", distractors:["Azure DNS","Azure Virtual Desktop","Microsoft Entra Domain Services"], misconceptions:["A budget automatically stops every resource","It is used to create VNets","It replaces invoices and billing accounts"], source:sources.cost },
  { key:"tags", group:"cost-management", domain:D3, term:"Resource tags", definition:"Name-value metadata attached to Azure resources for organization, reporting, automation, and cost allocation", scenario:"label resources by owner, environment, and cost center", statement:"Tags add metadata but do not by themselves enforce access control or inherit automatically in every situation.", distractors:["Availability zones","RBAC roles","Storage tiers"], misconceptions:["A tag grants administrator permissions","Every child resource always inherits tags automatically","Tags move resources between regions"], source:sources.cost },

  { key:"purview", group:"governance-compliance", domain:D3, term:"Microsoft Purview", definition:"Solutions for data governance, risk, and compliance across an organization's data estate", scenario:"discover, classify, and govern data across supported sources", statement:"Microsoft Purview helps organizations understand, govern, and protect data.", distractors:["Azure VPN Gateway","VM Scale Sets","Azure DNS"], misconceptions:["It is a VM autoscaler","It creates private endpoints automatically","It is only a storage copy command"], source:sources.governance },
  { key:"policy", group:"governance-compliance", domain:D3, term:"Azure Policy", definition:"A governance service that evaluates resources against rules and can audit, deny, modify, or remediate according to policy effects", scenario:"require allowed regions or audit resources missing a required configuration", statement:"Azure Policy evaluates resource state for organizational standards and compliance.", distractors:["Azure RBAC","Resource lock","Azure Advisor"], misconceptions:["It grants users permission to restart VMs","It is only a billing report","Policies can evaluate only newly created resources"], source:sources.governance },
  { key:"resource-locks", group:"governance-compliance", domain:D3, term:"Resource locks", definition:"CanNotDelete or ReadOnly protections applied at a scope to help prevent accidental changes", scenario:"protect a critical resource from accidental deletion even by an otherwise authorized user", statement:"Locks provide an extra control against deletion or modification but do not replace authorization.", distractors:["Azure Policy initiative","RBAC custom role","Availability set"], misconceptions:["A lock encrypts stored data","Locks are inherited upward to parent scopes","A ReadOnly lock grants write permission"], source:sources.governance },

  { key:"portal", group:"management-deployment", domain:D3, term:"Azure portal", definition:"A web-based graphical interface for creating, configuring, and monitoring Azure resources", scenario:"manage Azure resources through a browser-based graphical experience", statement:"The Azure portal offers a graphical management experience while using the same Azure control plane as other tools.", distractors:["AzCopy","Data Box","Application Insights SDK"], misconceptions:["It is the only way to manage Azure","It works only from inside an Azure VNet","It cannot show monitoring information"], source:sources.management },
  { key:"shell-cli-powershell", group:"management-deployment", domain:D3, term:"Cloud Shell, Azure CLI, and Azure PowerShell", definition:"Command-line and scripting tools for managing Azure resources, with Cloud Shell providing a browser-hosted shell", scenario:"run repeatable commands from Bash or PowerShell without installing tools on the current device", statement:"Cloud Shell provides managed shell access with Azure CLI and Azure PowerShell available for automation.", distractors:["Azure Files only","Pricing Calculator","Microsoft Purview"], misconceptions:["Azure CLI can run only in the portal","Azure PowerShell cannot automate deployments","Cloud Shell is a physical server shipped to customers"], source:sources.management },
  { key:"azure-arc", group:"management-deployment", domain:D3, term:"Azure Arc", definition:"Azure management and governance capabilities extended to supported resources outside Azure", scenario:"inventory and govern on-premises or multicloud servers through Azure", statement:"Azure Arc projects supported non-Azure resources into Azure management for consistent governance and operations.", distractors:["Azure Data Box","Azure DNS","Blob archive tier"], misconceptions:["It automatically moves every server into an Azure datacenter","It is only a pricing calculator","It replaces all local operating systems"], source:sources.management },
  { key:"iac", group:"management-deployment", domain:D3, term:"Infrastructure as code (IaC)", definition:"Defining infrastructure in versioned, repeatable machine-readable files", scenario:"review, reproduce, and automate an environment instead of configuring every resource manually", statement:"IaC improves repeatability, reviewability, and consistency of infrastructure deployments.", distractors:["Manual portal-only deployment","Physical asset inventory","Interactive remote desktop only"], misconceptions:["IaC files cannot be version controlled","IaC guarantees every design is secure","IaC can deploy only virtual machines"], source:sources.management },
  { key:"arm", group:"management-deployment", domain:D3, term:"Azure Resource Manager and ARM templates", definition:"The Azure deployment and management layer plus declarative JSON templates for resource deployments", scenario:"deploy interdependent Azure resources consistently as one declarative operation", statement:"Azure Resource Manager processes requests and ARM templates declaratively describe the desired resources.", distractors:["Azure Service Health","Storage Explorer","Microsoft Entra SSO"], misconceptions:["ARM templates are imperative shell scripts only","Resource Manager is a physical datacenter","Templates cannot include dependencies or parameters"], source:sources.management },

  { key:"advisor", group:"monitoring-tools", domain:D3, term:"Azure Advisor", definition:"Personalized recommendations for reliability, security, performance, operational excellence, and cost", scenario:"review recommendations to improve deployed Azure resources", statement:"Azure Advisor analyzes supported resource configurations and usage to provide optimization recommendations.", distractors:["Azure Service Health","Azure Monitor alert","Microsoft Purview"], misconceptions:["It reports only platform outages","It automatically applies every recommendation","It is the Azure invoice"], source:sources.monitoring },
  { key:"service-health", group:"monitoring-tools", domain:D3, term:"Azure Service Health", definition:"Personalized information about Azure service incidents, planned maintenance, health advisories, and security advisories", scenario:"determine whether an Azure platform issue affects services and regions used by your subscription", statement:"Service Health communicates relevant platform events and planned maintenance affecting Azure customers.", distractors:["Application Insights","Log Analytics","Azure Pricing Calculator"], misconceptions:["It traces every line of application code","It creates resource tags","It is only a VM performance counter"], source:sources.monitoring },
  { key:"azure-monitor", group:"monitoring-tools", domain:D3, term:"Azure Monitor", definition:"A monitoring platform including metrics, logs, Log Analytics, alerts, and Application Insights", scenario:"collect telemetry, query logs, trigger alerts, and analyze application performance", statement:"Azure Monitor centralizes telemetry; Log Analytics queries log data and Application Insights monitors application behavior.", distractors:["Azure Data Box","Azure Policy","Microsoft Entra Domain Services"], misconceptions:["It is only for billing data","Application Insights is a storage redundancy mode","Log Analytics cannot query collected logs"], source:sources.monitoring },
];

function placeAnswer(correct: string, distractors: [string, string, string], seed: number) {
  const position = seed % 4;
  const options = [...distractors];
  options.splice(position, 0, correct);
  return { options, correct: position };
}

function makeQuestion(idNumber: number, topic: Topic, variant: 0 | 1 | 2 | 3): Az900Question {
  const correctText = variant >= 2 ? topic.statement : topic.term;
  const wrong = variant >= 2 ? topic.misconceptions : topic.distractors;
  const placed = placeAnswer(correctText, wrong, idNumber);
  const text = variant === 0
    ? `Which Azure or cloud concept is best described as: ${topic.definition}?`
    : variant === 1
      ? `An organization needs to ${topic.scenario}. Which choice best meets the requirement?`
      : variant === 2
        ? `Which statement about ${topic.term} is accurate?`
        : `A team is reviewing its use of ${topic.term}. Which recommendation follows Microsoft Learn guidance?`;
  const rationale = variant >= 2 ? topic.statement : `${topic.term} is the best match because it is ${topic.definition.toLowerCase()}.`;
  return {
    id: `az900-q-${String(idNumber).padStart(3, "0")}`,
    courseId: "az900",
    domain: topic.domain,
    objectiveGroupId: topic.group,
    objectiveId: topic.key,
    text,
    options: placed.options,
    correct: placed.correct,
    source: topic.source,
    rationale: { en: rationale, fa: rationale, de: rationale },
    skillId: topic.group,
    reviewStatus: "audited",
    isOriginal: true,
  };
}

const generatedQuestions: Az900Question[] = [];
for (const topic of topics) {
  const domainIndex = topics.filter((candidate) => candidate.domain === topic.domain).indexOf(topic);
  const variants: Array<0 | 1 | 2 | 3> = topic.domain === D1
    ? (domainIndex < 11 ? [0, 1, 2] : [0, 1])
    : topic.domain === D2
      ? (domainIndex < 8 ? [0, 1, 2] : [0, 1])
      : [0, 1, 2, 3];
  for (const variant of variants) generatedQuestions.push(makeQuestion(generatedQuestions.length + 1, topic, variant));
}

type ExtraQuestion = Omit<Az900Question, "id" | "courseId" | "objectiveGroupId" | "reviewStatus" | "isOriginal" | "rationale"> & { rationale: string };
const extras: ExtraQuestion[] = [
  { domain:D1, objectiveId:"cloud-computing", skillId:"cloud-computing", text:"A company keeps regulated databases in its own datacenter but runs its public web tier in Azure. Which cloud model is this?", options:["Hybrid cloud","Private cloud only","Public cloud only","SaaS"], correct:0, rationale:"Hybrid cloud combines on-premises or private resources with public-cloud services.", source:sources.cloud },
  { domain:D1, objectiveId:"service-models", skillId:"service-models", text:"Which ordering moves from the greatest customer infrastructure responsibility to the least?", options:["IaaS → PaaS → SaaS","SaaS → PaaS → IaaS","PaaS → IaaS → SaaS","IaaS → SaaS → PaaS"], correct:0, rationale:"IaaS exposes the most customer-managed stack, PaaS abstracts the platform, and SaaS provides the complete application.", source:sources.serviceTypes },
  { domain:D1, objectiveId:"cloud-benefits", skillId:"cloud-benefits", text:"Which action is horizontal scaling?", options:["Adding more application instances","Adding CPU to one existing VM","Moving data to an archive tier","Applying a resource lock"], correct:0, rationale:"Horizontal scaling changes instance count; vertical scaling changes the capacity of an existing instance.", source:sources.benefits },
  { domain:D1, objectiveId:"cloud-computing", skillId:"cloud-computing", text:"Under the shared responsibility model, who normally protects the physical hosts in an Azure datacenter?", options:["Microsoft","The customer","The customer's internet provider","The application end user"], correct:0, rationale:"Microsoft is responsible for physical datacenter infrastructure, while customer responsibilities depend on the service model.", source:sources.cloud },
  { domain:D1, objectiveId:"service-models", skillId:"service-models", text:"A development team wants to deploy its code while the provider manages the operating system and application runtime. Which service model fits?", options:["PaaS","IaaS","SaaS for end users only","Private colocation"], correct:0, rationale:"PaaS provides a managed application platform while the customer owns its code and data.", source:sources.serviceTypes },
  { domain:D2, objectiveId:"azure-architecture", skillId:"azure-architecture", text:"Which design protects against a datacenter-level failure while keeping resources in one supported Azure region?", options:["Deploy across availability zones","Use two resource groups","Apply two tags","Create two management groups"], correct:0, rationale:"Availability zones are separate physical locations within a supported region.", source:sources.architecture },
  { domain:D2, objectiveId:"compute-networking", skillId:"compute-networking", text:"A stateless web tier needs many identical VMs and automatic scaling. Which Azure option is the best fit?", options:["Virtual Machine Scale Sets","Azure Virtual Desktop","A single availability set","Azure Files"], correct:0, rationale:"Virtual Machine Scale Sets manage and scale a group of similar virtual machines.", source:sources.compute },
  { domain:D2, objectiveId:"compute-networking", skillId:"compute-networking", text:"Which hybrid connectivity option provides a private dedicated connection through a connectivity provider rather than an internet VPN?", options:["ExpressRoute","VNet peering","Public endpoint","Azure DNS"], correct:0, rationale:"ExpressRoute provides private connectivity to Microsoft cloud services through a connectivity provider.", source:sources.compute },
  { domain:D2, objectiveId:"storage-services", skillId:"storage-services", text:"Which redundancy option keeps copies across availability zones in the primary region without geographic replication?", options:["ZRS","LRS","GRS","GZRS"], correct:0, rationale:"Zone-redundant storage replicates data synchronously across availability zones in the primary region.", source:sources.storage },
  { domain:D3, objectiveId:"governance-compliance", skillId:"governance-compliance", text:"Which statement correctly distinguishes Azure RBAC from Azure Policy?", options:["RBAC controls allowed actions; Policy evaluates resource compliance","Policy grants user permissions; RBAC chooses storage tiers","RBAC prevents all deletion; Policy creates invoices","They are two names for the same service"], correct:0, rationale:"RBAC is authorization, while Azure Policy evaluates and enforces resource standards.", source:sources.governance },
  { domain:D3, objectiveId:"monitoring-tools", skillId:"monitoring-tools", text:"Which tool should you check first for a platform incident affecting an Azure service in a region used by your subscription?", options:["Azure Service Health","Application Insights","Azure Advisor","Pricing Calculator"], correct:0, rationale:"Azure Service Health provides personalized notices for incidents and planned maintenance that affect used services and regions.", source:sources.monitoring },
];

export const az900Questions: Az900Question[] = [
  ...generatedQuestions,
  ...extras.map((item, index) => ({ ...item, id:`az900-q-${String(generatedQuestions.length + index + 1).padStart(3, "0")}`, courseId:"az900" as const, objectiveGroupId:item.objectiveId, objectiveId:`comparison-${index + 1}`, reviewStatus:"audited" as const, isOriginal:true as const, rationale:{ en:item.rationale, fa:item.rationale, de:item.rationale } })),
];

export const az900Stages = [
  { id:"cloud-computing", stage:1, domain:D1, title:"Cloud computing", objective:"Cloud models, shared responsibility, consumption pricing, and serverless", source:sources.cloud },
  { id:"cloud-benefits", stage:2, domain:D1, title:"Benefits of cloud services", objective:"Availability, scalability, reliability, predictability, security, governance, and manageability", source:sources.benefits },
  { id:"service-models", stage:3, domain:D1, title:"Cloud service types", objective:"IaaS, PaaS, SaaS, and choosing the appropriate model", source:sources.serviceTypes },
  { id:"azure-architecture", stage:4, domain:D2, title:"Core Azure architecture", objective:"Regions, zones, datacenters, resources, subscriptions, and management groups", source:sources.architecture },
  { id:"compute-networking", stage:5, domain:D2, title:"Azure compute and networking", objective:"VMs, containers, functions, hosting, VNets, hybrid connectivity, and endpoints", source:sources.compute },
  { id:"storage-services", stage:6, domain:D2, title:"Azure storage services", objective:"Storage services, tiers, redundancy, movement, and migration", source:sources.storage },
  { id:"identity-security", stage:7, domain:D2, title:"Identity, access, and security", objective:"Microsoft Entra, authentication, RBAC, Zero Trust, layered security, and Defender for Cloud", source:sources.identity },
  { id:"cost-management", stage:8, domain:D3, title:"Cost management", objective:"Cost factors, estimates, budgets, analysis, and tags", source:sources.cost },
  { id:"governance-compliance", stage:9, domain:D3, title:"Governance and compliance", objective:"Microsoft Purview, Azure Policy, and resource locks", source:sources.governance },
  { id:"management-deployment", stage:10, domain:D3, title:"Management and deployment", objective:"Portal, Cloud Shell, CLI, PowerShell, Azure Arc, IaC, and ARM", source:sources.management },
  { id:"monitoring-tools", stage:11, domain:D3, title:"Azure monitoring tools", objective:"Azure Advisor, Service Health, Azure Monitor, Log Analytics, alerts, and Application Insights", source:sources.monitoring },
].map((stage) => ({ ...stage, questionIds:az900Questions.filter((question) => question.objectiveGroupId === stage.id).map((question) => question.id) }));

export const az900Lessons = az900Stages.map((stage) => ({
  id:`az900-lesson-${stage.id}`,
  stageId:stage.id,
  title:stage.title,
  objective:stage.objective,
  body:`This lesson follows the current AZ-900 skills measured as of July 20, 2026. Learn the purpose, decision boundary, and common use case for ${stage.title.toLowerCase()}, then verify understanding with original scenario questions.`,
  estimatedMinutes:Math.max(15, Math.round(stage.questionIds.length * 0.8)),
  source:stage.source,
}));

export const az900Labs = [
  { id:"az900-lab-cost-estimate", title:"Build and tag a cost estimate", description:"Create a Pricing Calculator estimate for a small web workload, record assumptions, and define owner/environment/cost-center tags.", checklist:["Choose a region and services","Record usage assumptions","Export or summarize the estimate","Define three useful tags"], source:sources.cost },
  { id:"az900-lab-governance", title:"Design a governance hierarchy", description:"Sketch a management-group, subscription, resource-group, RBAC, Policy, and lock design for development and production.", checklist:["Draw the scope hierarchy","Place RBAC at least privilege","Add one Policy rule","Protect one critical resource with a lock"], source:sources.governance },
  { id:"az900-lab-monitoring", title:"Choose the correct monitoring signal", description:"Map an optimization recommendation, regional service incident, log query, alert, and application trace to the right Azure tool.", checklist:["Use Advisor for recommendations","Use Service Health for platform events","Use Log Analytics for log queries","Use Application Insights for app telemetry"], source:sources.monitoring },
];

export const az900Course = {
  id:"az900" as const,
  code:"AZ-900",
  title:"Microsoft Azure Fundamentals",
  subtitle:"Cloud concepts, Azure architecture and services, management, and governance",
  questionCount:az900Questions.length,
  sourceVersion:"Skills measured as of July 20, 2026",
  studyGuide:GUIDE,
  certification:CERTIFICATION,
  practiceAssessment:"https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/practice/assessment?assessment-type=practice&assessmentId=23&practice-assessment-type=certification",
  examSandbox:"https://mscertdemo.starttest.com/",
};

export const az900PracticalScenarios = az900Labs.map((lab) => ({ id:lab.id, title:{ fa:lab.title, en:lab.title, de:lab.title }, prompt:{ fa:lab.description, en:lab.description, de:lab.description }, skillId:az900Stages.find((stage) => lab.source === stage.source)?.id ?? "management-deployment", source:lab.source }));
