import type { LabQuestion, LabStep, LabTest, ServerLab } from "./server-labs";

/** Original foundation exercises, not Cisco exam items or a complete exam simulator.
 * Reviewed 2026-10-01 against the currently active 200-301 v1.1 blueprint.
 * Commands are learner instructions for isolated Packet Tracer files only.
 */
export const ccnaSources = {
  blueprint: "https://learningcontent.cisco.com/documents/marketing/exam-topics/200-301-CCNA-v1.1.pdf",
  exam: "https://www.cisco.com/site/us/en/learn/training-certifications/exams/ccna.html",
  packetTracer: "https://www.netacad.com/courses/getting-started-cisco-packet-tracer/1000",
  ipv4: "https://www.cisco.com/c/en/us/support/docs/ip/routing-information-protocol-rip/13788-3.html",
  ipv6: "https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipv6/configuration/15-2mt/ip6-15-2mt-book/ip6-uni-routing.html",
  vlan: "https://www.cisco.com/c/en/us/td/docs/switches/lan/c9000/lyr2-fwd/vlan/vlan-configuration-guide/configure-vlan-trunks.html",
  channel: "https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst3750/software/release/12-2_25_sea/configuration/guide/3750scg/swethchl.pdf",
  ospf: "https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_ospf/configuration/15-mt/iro-15-mt-book/iro-cfg.html",
  dhcp: "https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipaddr_dhcp/configuration/12-4/dhcp-12-4-book/config-dhcp-server.html",
  nat: "https://www.cisco.com/c/en/us/support/docs/ip/network-address-translation-nat/13772-12.html",
  acl: "https://www.cisco.com/c/en/us/support/docs/security/ios-firewall/23602-confaccesslists.html",
  ssh: "https://www.cisco.com/c/en/us/support/docs/security-vpn/secure-shell-ssh/4145-ssh.html",
  wifi: "https://www.cisco.com/c/en/us/support/docs/wireless-mobility/wireless-lan-wlan/116599-config-wpa-psk-00.html",
  rest: "https://developer.cisco.com/docs/nx-os/representational-state-transfer-rest/",
};
export const ccnaDomains = [
  { id: "1.0", title: "Network Fundamentals", weight: 20 },
  { id: "2.0", title: "Network Access", weight: 20 },
  { id: "3.0", title: "IP Connectivity", weight: 25 },
  { id: "4.0", title: "IP Services", weight: 10 },
  { id: "5.0", title: "Security Fundamentals", weight: 15 },
  { id: "6.0", title: "Automation and Programmability", weight: 10 },
] as const;

const before = [
  "Use a separate Packet Tracer file for each stage. Save a clean starting copy and a completed copy; never paste these commands into company equipment.",
  "Router CLI examples use a 2911 with GigabitEthernet0/0 and 0/1; switches use a 2960 with FastEthernet0/1–24. Check interface names first. Cisco documentation may describe newer platforms with different syntax.",
  "Type commands in the named device CLI. PC addressing and wireless settings use the simulator GUI. After configure terminal, end returns to privileged EXEC mode. The website does not execute commands or inspect your topology.",
  "Packet Tracer runs on a desktop computer, not a phone. You can read lessons, answer questions and save evidence on mobile. Cisco may require a separate free Networking Academy account for the simulator.",
];
const step = (title: string, instruction: string, explain: string, command?: string): LabStep => ({ title, instruction, explain, command });
const test = (id: string, title: string, procedure: string, expected: string): LabTest => ({ id, title, procedure, expected, points: 1 });
const q = (id: string, objective: string, text: string, options: string[], correct: number, explain: string, source: string): LabQuestion => ({ id, objective, text, options, correct, explain, source });
const references = (...keys: (keyof typeof ccnaSources)[]) => [...new Set(["blueprint" as const, "packetTracer" as const, ...keys])].map((key) => ({ title: `Cisco · ${key === "blueprint" ? "200-301 v1.1 objectives" : key === "packetTracer" ? "Get Packet Tracer" : key.toUpperCase()}`, url: ccnaSources[key] }));
const topology = (title: string, nodes: [string, string][], note: string): NonNullable<ServerLab["topology"]> => ({ title, nodes: nodes.map(([title, detail]) => ({ title, detail })), note });

export const ccnaLabs: ServerLab[] = [
  {
    id: "ccna-addressing", title: "IPv4, subnetting & IPv6", assignment: "Stage 1 · Network Fundamentals · 1.6 / 1.8 / 1.9 / 1.10", lessonId: "ccna-addressing", minutes: "35–50",
    goal: "Build one dual-stack LAN and prove which addresses belong to the same subnet.", prerequisites: before,
    topology: topology("One isolated dual-stack LAN", [["PC-A", "192.168.10.10/26 · 2001:db8:10::10/64"], ["SW1 → R1 G0/0", "Gateway 192.168.10.1/26 · 2001:db8:10::1/64"], ["PC-B", "192.168.10.20/26 · 2001:db8:10::20/64"]], "Connect PCs to SW1 F0/1 and F0/2; SW1 F0/24 to R1 G0/0. Use automatic cable selection. Documentation IPv6 prefixes are only for this lab."),
    steps: [
      step("Place and cable the LAN", "Create ccna-01.pkt with two PCs, one 2960 and one 2911. Connect the ports in the diagram and wait for switch links to converge.", "First verify the physical path; an IP change cannot repair an unplugged link."),
      step("Work out the /26 address plan", "Write the mask 255.255.255.192, network .0, usable .1–.62 and broadcast .63. Configure the two PCs in Desktop → IP Configuration with the addresses and gateway above.", "This exercise has 64 addresses in each /26 block, with 62 host addresses. The chosen PC addresses share the first block."),
      step("Configure the dual-stack gateway", "Run this on R1. Add each PC's IPv6 address with prefix 64 and IPv6 gateway 2001:db8:10::1 in its IP Configuration GUI.", "IPv4 and IPv6 have independent addresses. Enabling IPv6 routing is not a replacement for assigning addresses to an interface.", "enable\nconfigure terminal\ninterface gigabitEthernet0/0\n ip address 192.168.10.1 255.255.255.192\n ipv6 address 2001:db8:10::1/64\n no shutdown\nexit\nipv6 unicast-routing\nend\nshow ip interface brief\nshow ipv6 interface brief"),
      step("Capture the baseline", "Ping PC-B and both gateway addresses from PC-A. Record the actual replies after any initial ARP/neighbor discovery delay, then save the Packet Tracer file.", "A first failed echo can be caused by address resolution. Repeat the test and distinguish a temporary discovery delay from a persistent addressing problem.", "ping 192.168.10.20\nping 192.168.10.1\nping 2001:db8:10::1"),
    ],
    tests: [test("addr-v4", "IPv4 reachability", "From PC-A, ping PC-B and R1 after convergence; record addresses and received replies.", "Both IPv4 destinations reply with the stated /26 mask."), test("addr-v6", "IPv6 reachability", "From PC-A, ping PC-B's IPv6 address and the IPv6 gateway.", "Both IPv6 addresses reply; router G0/0 is up/up."), test("addr-plan", "Address boundary check", "Calculate whether .63 or .64 is an ordinary host address in 192.168.10.0/26; record your reasoning without assigning them.", ".63 is the broadcast address of this /26; .64 begins the next /26 and is not in this subnet.")],
    questions: [
      q("ccna-addr-q1", "1.6", "For the ordinary IPv4 LAN 192.168.10.0/26, how many usable host addresses are available?", ["62", "64", "30", "126"], 0, "Six host bits give 64 addresses. Reserving the network and broadcast addresses leaves 62; /31 point-to-point exceptions do not apply to this LAN.", ccnaSources.ipv4),
      q("ccna-addr-q2", "1.6", "Which address is in the same /26 subnet as PC-A at 192.168.10.10?", ["192.168.10.64", "192.168.10.62", "192.168.10.100", "192.168.11.10"], 1, "The first /26 spans .0 through .63. Only .62 is a usable host in that range; .64 and .100 belong to the next block.", ccnaSources.ipv4),
      q("ccna-addr-q3", "1.9", "Which address is an IPv6 link-local unicast address?", ["2001:db8:10::10", "ff02::1", "fe80::10", "::1"], 2, "fe80::10 is link-local unicast. ff02::1 has link-local multicast scope, but it is not unicast; ::1 is loopback, and 2001:db8:: is a documentation prefix, not link-local.", ccnaSources.ipv6),
      q("ccna-addr-q4", "1.10", "PC-A can ping PC-B on its local LAN but cannot reach another subnet. Which client setting should you check first?", ["OSPF process number", "Switch hostname", "Wi-Fi channel", "Default gateway"], 3, "Off-subnet traffic needs the client's gateway. The router's OSPF configuration can matter later, but first verify the client has a reachable gateway in its own subnet.", ccnaSources.ipv4),
    ], sources: references("ipv4", "ipv6"),
  },
  {
    id: "ccna-vlans", title: "VLANs, trunks & inter-VLAN routing", assignment: "Stage 2 · Network Access · 2.1 / 2.2", lessonId: "ccna-vlans", minutes: "45–60", goal: "Separate two departments and route between them through an 802.1Q trunk.", prerequisites: before,
    topology: topology("Router-on-a-stick", [["PC-A → SW1 F0/1", "VLAN 10 · 192.168.10.10/24"], ["SW1 F0/24 ↔ R1 G0/0", "Trunk allows VLANs 10 and 20"], ["PC-B → SW1 F0/2", "VLAN 20 · 192.168.20.10/24"]], "Gateways are 192.168.10.1 and 192.168.20.1 on router subinterfaces. This new file does not reuse Stage 1's /26 mask."),
    steps: [
      step("Build two department endpoints", "Create ccna-02.pkt with the pictured ports. Configure PC-A as 192.168.10.10/24, gateway .10.1; PC-B as 192.168.20.10/24, gateway .20.1.", "A VLAN is a separate Layer 2 broadcast domain. Inter-VLAN traffic requires a Layer 3 device, not simply a second access port."),
      step("Create access VLANs", "Run on SW1. Confirm the PC ports appear in the intended VLAN before configuring routing.", "Access ports place untagged client frames into one VLAN. The VLAN must exist as well as being assigned to the port.", "enable\nconfigure terminal\nvlan 10\n name STAFF\nvlan 20\n name LAB\ninterface fastEthernet0/1\n switchport mode access\n switchport access vlan 10\ninterface fastEthernet0/2\n switchport mode access\n switchport access vlan 20\nend\nshow vlan brief"),
      step("Enable the router uplink trunk", "On SW1 F0/24, configure the uplink to R1 as a trunk. Do not run switchport trunk encapsulation on a 2960; it uses 802.1Q.", "The allowed list must carry both department VLANs. Keeping the router uplink as an access port prevents the two tagged paths from operating.", "configure terminal\ninterface fastEthernet0/24\n switchport mode trunk\n switchport trunk allowed vlan 10,20\nend\nshow interfaces trunk"),
      step("Route with two subinterfaces", "On R1, add the VLAN gateways below. Run repeated cross-VLAN pings, save the file and capture both trunk status and interface status.", "The dot1Q VLAN ID associates each router subinterface with the matching tagged frames. No IP address is assigned to the parent interface here.", "enable\nconfigure terminal\ninterface gigabitEthernet0/0\n no shutdown\ninterface gigabitEthernet0/0.10\n encapsulation dot1Q 10\n ip address 192.168.10.1 255.255.255.0\ninterface gigabitEthernet0/0.20\n encapsulation dot1Q 20\n ip address 192.168.20.1 255.255.255.0\nend\nshow ip interface brief"),
    ],
    tests: [test("vlan-ports", "Access membership", "Inspect SW1 show vlan brief and compare F0/1 and F0/2 with the address plan.", "F0/1 is in VLAN 10 and F0/2 in VLAN 20."), test("vlan-trunk", "Trunk tagging", "Inspect show interfaces trunk and the R1 subinterface configuration.", "F0/24 trunks VLANs 10 and 20; router dot1Q IDs match."), test("vlan-route", "Cross-VLAN communication", "From each PC ping its gateway, then the other PC after address resolution.", "Gateway and cross-VLAN pings succeed; evidence names both endpoints.")],
    questions: [
      q("ccna-vlan-q1", "2.2.a", "The router must receive VLANs 10 and 20 through one switch uplink. Which mode is appropriate on that switch port?", ["Access VLAN 10 only", "Trunk carrying VLANs 10 and 20", "Shutdown", "Access VLAN 20 only"], 1, "A trunk carries multiple VLANs on the uplink. Either single-VLAN access choice leaves one department without its tagged router path.", ccnaSources.vlan),
      q("ccna-vlan-q2", "2.2.b", "What does encapsulation dot1Q 20 identify on R1 G0/0.20?", ["Twenty physical links", "The OSPF area", "The VLAN tag associated with that subinterface", "The subnet mask length"], 2, "The encapsulation argument identifies VLAN 20. The subinterface suffix is a naming convention; it is the dot1Q configuration that selects the tag.", ccnaSources.vlan),
      q("ccna-vlan-q3", "2.1.c", "PC-A reaches its VLAN 10 gateway, but PC-B cannot reach its VLAN 20 gateway. The router uplink allows only VLAN 10. What conflicts with the intended design?", ["Using two IP subnets", "Naming a VLAN STAFF", "Using a /24 client mask", "The trunk allowed-VLAN list omits VLAN 20"], 3, "VLAN 20 must cross the trunk to reach its router subinterface. Omitting it explains why the VLAN 10 path works while the VLAN 20 path fails; add VLAN 20 and verify both paths.", ccnaSources.vlan),
      q("ccna-vlan-q4", "2.1", "What is the primary Layer 2 effect of placing clients in different VLANs?", ["Separate broadcast domains", "Automatic encryption of all frames", "Automatic IP routing between clients", "Removal of the need for MAC addresses"], 0, "VLANs divide Layer 2 broadcast domains. They neither encrypt traffic nor automatically supply routing between IP subnets.", ccnaSources.vlan),
    ], sources: references("vlan"),
  },
  {
    id: "ccna-etherchannel", title: "LACP & spanning-tree observations", assignment: "Stage 3 · Network Access · 2.4 / 2.5", lessonId: "ccna-etherchannel", minutes: "35–50", goal: "Bundle two switch links and verify that one member can fail without losing the logical path.", prerequisites: before,
    topology: topology("Two physical links, one logical channel", [["PC-A → SW1 F0/1", "192.168.30.10/24 · VLAN 30"], ["SW1 ↔ SW2", "F0/23↔F0/23 + F0/24↔F0/24 · Po1"], ["SW2 F0/1 → PC-B", "192.168.30.20/24 · VLAN 30"]], "Use two 2960 switches. Shut both uplink ports before cabling/configuring; enable them only after both sides have consistent channel settings."),
    steps: [
      step("Prepare the endpoints and disabled uplinks", "Create ccna-03.pkt with two switches and two PCs. On each switch shut F0/23–24 first; cable the links shown, configure PC addresses and create VLAN 30.", "Parallel unbundled links can create a loop. Start with shut interfaces and let LACP plus spanning tree manage the final topology.", "enable\nconfigure terminal\ninterface range fastEthernet0/23 - 24\n shutdown\nexit\nvlan 30\ninterface fastEthernet0/1\n switchport mode access\n switchport access vlan 30\nend"),
      step("Configure LACP on both switches", "Apply the same channel and trunk settings on SW1 and SW2 while the member ports remain shut.", "Active mode initiates LACP negotiation. Matching trunk, speed and VLAN settings are necessary for the members to form one bundle.", "configure terminal\ninterface range fastEthernet0/23 - 24\n switchport mode trunk\n switchport trunk allowed vlan 30\n channel-group 1 mode active\nexit\ninterface port-channel 1\n switchport mode trunk\n switchport trunk allowed vlan 30\nend"),
      step("Enable and observe the channel", "After configuring both sides, enable the member ports on each switch. Inspect the channel and spanning-tree output after convergence.", "Spanning tree sees the channel as one logical connection. A member that is suspended or individual is not evidence of a healthy bundle.", "configure terminal\ninterface range fastEthernet0/23 - 24\n no shutdown\nend\nshow etherchannel summary\nshow spanning-tree vlan 30"),
      step("Test one failure and restore it", "Run repeated PC-to-PC pings; shut only SW1 F0/23, wait for convergence, repeat the ping, then restore it with no shutdown. Save a restored topology.", "A surviving member preserves connectivity, but not the original aggregate capacity. Do not claim that one flow doubles its throughput.", "configure terminal\ninterface fastEthernet0/23\n shutdown\nend\nshow etherchannel summary\n! After testing, restore this member:\nconfigure terminal\ninterface fastEthernet0/23\n no shutdown\nend"),
    ],
    tests: [test("lacp-bundle", "Member participation", "Inspect show etherchannel summary on both switches.", "Po1 is in use as a Layer 2 channel; both members show participation before failure."), test("lacp-fail", "Single-member failure", "Record pings before, during and after shutting one member; allow convergence.", "Connectivity resumes through the surviving member, with both links restored at the end."), test("lacp-stp", "Logical spanning-tree port", "Read show spanning-tree vlan 30 and identify the port-channel entry.", "The spanning-tree topology contains Po1 as a logical port; a loop is not created by treating members as independent forwarding paths.")],
    questions: [
      q("ccna-channel-q1", "2.4", "Both switch ends use LACP passive and no other negotiation initiator exists. What change can establish negotiation?", ["Set both ends to shutdown", "Replace VLAN 30 with VLAN 1", "Set at least one side to LACP active", "Change both sides to PAgP auto"], 2, "Passive responds but does not initiate LACP. Active on at least one end starts negotiation; PAgP is a different protocol.", ccnaSources.channel),
      q("ccna-channel-q2", "2.4", "A two-member Layer 2 EtherChannel loses one physical member. What is the expected result if the other member remains healthy?", ["All VLANs disappear", "Every flow must double its speed", "The port-channel always shuts down", "The logical channel can remain available with reduced capacity"], 3, "One surviving member can keep the channel operational. Capacity and redundancy decrease; a successful ping does not measure aggregate throughput.", ccnaSources.channel),
      q("ccna-channel-q3", "2.5", "How does spanning tree normally treat a correctly formed Layer 2 EtherChannel?", ["As one logical port", "As two unrelated forwarding loops", "As an OSPF neighbor", "As a NAT pool"], 0, "The channel is a logical spanning-tree port. Its member links are not independently used as separate STP paths in a correctly formed bundle.", ccnaSources.channel),
      q("ccna-channel-q4", "2.4", "One member is suspended after changing its allowed VLANs. What is the most appropriate first check?", ["The PC wallpaper", "Consistency of member and port-channel configuration", "The DNS search suffix", "The WLAN password"], 1, "EtherChannel members must have compatible Layer 2 settings. Inspect both ends and the bundle before changing unrelated endpoint services.", ccnaSources.channel),
    ], sources: references("channel"),
  },
  {
    id: "ccna-routing", title: "Static routing & single-area OSPF", assignment: "Stage 4 · IP Connectivity · 3.1 / 3.2 / 3.3 / 3.4", lessonId: "ccna-routing", minutes: "50–65", goal: "Connect two LANs, compare static routes with OSPF and test a reversible neighbor failure.", prerequisites: before,
    topology: topology("Two routed LANs", [["PC-A → R1 G0/0", "10.1.1.10/24 · gateway 10.1.1.1"], ["R1 G0/1 ↔ R2 G0/1", "10.0.12.1/30 ↔ 10.0.12.2/30 · area 0"], ["R2 G0/0 → PC-B", "10.2.2.10/24 · gateway 10.2.2.1"]], "Place a 2960 between each PC and its 2911 router. Use a new file with no prior VLAN, ACL or NAT configuration."),
    steps: [
      step("Address both routers and clients", "Create ccna-04.pkt. Set the PC addresses above. Apply the R1 commands, then repeat on R2 using 10.2.2.1/24 on G0/0 and 10.0.12.2/30 on G0/1.", "A route cannot repair an administratively down interface. First prove each PC reaches its gateway and each router reaches its link peer.", "enable\nconfigure terminal\ninterface gigabitEthernet0/0\n ip address 10.1.1.1 255.255.255.0\n no shutdown\ninterface gigabitEthernet0/1\n ip address 10.0.12.1 255.255.255.252\n no shutdown\nend\nshow ip interface brief"),
      step("Add a return-aware static path", "On R1 add the first route below. On R2 add the second. Ping across the LANs and capture show ip route on both routers.", "A request and its reply need routes in both directions. Each next hop is the adjacent router's address, not the remote PC.", "! R1:\nconfigure terminal\nip route 10.2.2.0 255.255.255.0 10.0.12.2\nend\n! R2:\nconfigure terminal\nip route 10.1.1.0 255.255.255.0 10.0.12.1\nend\nshow ip route"),
      step("Replace static routes with OSPF", "Remove the corresponding static route from each router. Use the R1 OSPF configuration below; on R2 use router-id 2.2.2.2 and network 10.2.2.0 0.0.0.255 area 0, keeping the same transit network.", "Removing the static paths makes the learned OSPF route visible. Passive LAN interfaces advertise their subnet without trying to form neighbors with PCs.", "! R1:\nconfigure terminal\nno ip route 10.2.2.0 255.255.255.0 10.0.12.2\nrouter ospf 1\n router-id 1.1.1.1\n network 10.1.1.0 0.0.0.255 area 0\n network 10.0.12.0 0.0.0.3 area 0\n passive-interface gigabitEthernet0/0\nend\n! R2: remove its static route and apply the equivalent OSPF settings.\nshow ip ospf neighbor\nshow ip route ospf"),
      step("Introduce and repair an area mismatch", "On R2 replace only the transit network's area 0 statement with area 1. Observe lost adjacency/routes, then restore area 0. Do not mark the lab complete while the fault remains.", "OSPF neighbors on this link must share an area. Restoring the original statement is a controlled repair, not a reason to disable routing globally.", "! R2 only, fault injection:\nconfigure terminal\nrouter ospf 1\n no network 10.0.12.0 0.0.0.3 area 0\n network 10.0.12.0 0.0.0.3 area 1\nend\n! Restore by removing the area 1 statement and adding area 0 again."),
    ],
    tests: [test("route-static", "Static forward and return routes", "Before replacing them, capture both static entries and successful PC-A-to-PC-B ping.", "Both remote /24 routes point at the adjacent /30 peer and end-to-end replies arrive."), test("route-ospf", "OSPF adjacency and learned LAN", "After removing static routes, inspect neighbor state and remote-LAN route codes on both routers.", "Neighbor reaches FULL and the remote /24 has an O route."), test("route-repair", "Area-mismatch repair", "Record the mismatch failure, then restore both transit statements to area 0 and repeat the tests.", "Adjacency and learned routes return; the saved final file has both transit interfaces in area 0.")],
    questions: [
      q("ccna-route-q1", "3.2.a", "A router has matching routes 10.2.0.0/16 and 10.2.2.0/24. Which is selected for destination 10.2.2.10?", ["The /16 because it covers more hosts", "Whichever was entered first", "Both must be discarded", "The /24 because it is the longer matching prefix"], 3, "Destination lookup favors the most specific matching prefix. Administrative distance compares competing sources for the same prefix, not a shorter matching prefix against a longer one.", ccnaSources.blueprint),
      q("ccna-route-q2", "3.3", "R1 has a static route to PC-B, but R2 has no route back to PC-A's LAN. What remains necessary?", ["A return route on R2", "Changing PC-A's MAC address", "A WLAN controller", "Disabling R1 G0/0"], 0, "Reachability is bidirectional. The reply needs a route to 10.1.1.0/24 through R1; a forward-only static path is not enough.", ccnaSources.blueprint),
      q("ccna-route-q3", "3.4.a", "Two otherwise compatible OSPF interfaces share a subnet but are configured in different areas. What is the likely result?", ["Automatic area renumbering", "Failure to establish the intended adjacency", "Creation of a VLAN trunk", "DHCP lease renewal"], 1, "An area mismatch prevents these interfaces from becoming neighbors. Verify area and other hello parameters before troubleshooting learned remote routes.", ccnaSources.ospf),
      q("ccna-route-q4", "3.4.d", "Which design avoids a router-ID conflict between these two OSPF routers?", ["Using 1.1.1.1 on both", "Making both transit interfaces passive", "Assigning distinct IDs such as 1.1.1.1 and 2.2.2.2", "Setting both gateways to the same LAN address"], 2, "OSPF router IDs identify routers and must be unique in the routing domain. They are not required to equal a physical interface address when explicitly configured.", ccnaSources.ospf),
    ], sources: references("ospf"),
  },
  {
    id: "ccna-services", title: "DHCP & static NAT", assignment: "Stage 5 · IP Services · 4.1 / 4.3", lessonId: "ccna-services", minutes: "40–55", goal: "Lease a client address and verify a one-to-one translation without connecting to the public Internet.", prerequisites: before,
    topology: topology("A simulated inside and outside", [["PC-A + inside server → SW1", "192.168.50.0/24 · server 192.168.50.20"], ["R1 G0/0 ↔ G0/1", "Inside .50.1/24 · outside 198.51.100.1/24"], ["SW2 → outside PC", "198.51.100.10/24 · gateway .100.1"]], "The inside server maps to 198.51.100.20. The entire outside network is simulated; 198.51.100.0/24 is documentation space, not a real ISP."),
    steps: [
      step("Build an isolated translation network", "Create ccna-05.pkt with one router, two switches, a DHCP client, an inside Server-PT and an outside PC. Give the server .50.20/24 with gateway .50.1; outside PC .100.10/24 with gateway .100.1.", "NAT uses distinct inside and outside roles; both networks remain in the simulator. The static server address must be kept outside the client lease pool."),
      step("Configure interfaces and a client pool", "On R1 configure the interfaces below, then set PC-A to DHCP. The exclusions protect the gateway and server; no Internet DNS resolver is required for these IP-only tests.", "A DHCP lease supplies the subnet mask and default gateway. This pool exercise teaches DHCP behavior; configuring an IOS DHCP server is supporting practice rather than a separate claimed official objective.", "enable\nconfigure terminal\ninterface gigabitEthernet0/0\n ip address 192.168.50.1 255.255.255.0\n ip nat inside\n no shutdown\ninterface gigabitEthernet0/1\n ip address 198.51.100.1 255.255.255.0\n ip nat outside\n no shutdown\nexit\nip dhcp excluded-address 192.168.50.1 192.168.50.30\nip dhcp pool CLIENTS\n network 192.168.50.0 255.255.255.0\n default-router 192.168.50.1\nend\nshow ip dhcp binding"),
      step("Publish the simulated server address", "On R1 create the static inside-source mapping. From the outside PC ping 198.51.100.20, not the private address. Recheck the inside server gateway if replies fail.", "Static NAT associates one private host with one outside-facing address. Translation is not encryption or an independent firewall policy.", "configure terminal\nip nat inside source static 192.168.50.20 198.51.100.20\nend\nshow ip nat translations\nshow ip nat statistics"),
      step("Verify services independently", "Record PC-A's lease, gateway ping and the outside-to-translated-server ping. Save output showing the translation. Do not describe this as public hosting or a tested Internet connection.", "A valid DHCP lease and a working NAT mapping are separate observations. Testing one does not prove the other succeeded."),
    ],
    tests: [test("svc-lease", "Correct client lease", "Use PC-A ipconfig and R1 show ip dhcp binding; record the assigned address, mask and gateway.", "PC-A receives an unexcluded 192.168.50.x/24 address with gateway 192.168.50.1."), test("svc-nat", "One-to-one translation", "Ping 198.51.100.20 from the outside PC and inspect R1's translation table.", "The table maps inside-local 192.168.50.20 to inside-global 198.51.100.20 and ping replies arrive."), test("svc-exclude", "Protect fixed addresses", "Inspect pool exclusions and compare the client lease with gateway/server addresses.", "No DHCP lease is assigned from .1 through .30; server .20 retains its static address.")],
    questions: [
      q("ccna-services-q1", "4.3", "Why exclude the gateway and static server addresses from the DHCP pool?", ["To avoid leasing an address already used by fixed devices", "To encrypt DHCP packets", "To enable OSPF area 0", "To make all clients use the same IP"], 0, "The exclusions prevent the pool from offering the addresses reserved for this gateway and server. A duplicate address can break an otherwise correct design.", ccnaSources.dhcp),
      q("ccna-services-q2", "4.1", "In this static mapping, which address is the inside-local address?", ["198.51.100.20", "192.168.50.20", "198.51.100.10", "198.51.100.1"], 1, "Inside-local is the server's address on the inside network. The mapped address 198.51.100.20 represents it to the outside network in this simulation.", ccnaSources.nat),
      q("ccna-services-q3", "4.1", "The outside ping fails and the server's default gateway is empty. What should be fixed first in this topology?", ["The switch hostname", "The wireless SSID", "The server gateway, 192.168.50.1", "The OSPF router ID"], 2, "The inside server must return off-subnet replies through R1. A mapping alone does not give the host its required return path.", ccnaSources.nat),
      q("ccna-services-q4", "4.3", "Which service resolves a hostname to an address, rather than assigning a client lease?", ["NAT", "LACP", "OSPF", "DNS"], 3, "DNS resolves names; DHCP supplies client configuration. A client can have a valid DHCP lease while name resolution is unavailable.", ccnaSources.blueprint),
    ], sources: references("dhcp", "nat"),
  },
  {
    id: "ccna-security", title: "SSH & an ordered access list", assignment: "Stage 6 · Security / IP Services · 5.3 / 5.6 / 4.8", lessonId: "ccna-security", minutes: "45–60", goal: "Use encrypted management and verify both an allowed and a deliberately denied traffic flow.", prerequisites: [...before, "Keep the router console open while changing ACLs. Replace the sample lab-only secret with your own throwaway value; never include it in evidence."],
    topology: topology("Manage one router; filter one server flow", [["PC-A → R1 G0/0", "192.168.60.10/24 · gateway .60.1"], ["R1", "G0/0 .60.1/24 · G0/1 .70.1/24"], ["R1 G0/1 → server", "192.168.70.20/24 · gateway .70.1"]], "Use switches on both LANs. Enable HTTP on Server-PT for the permitted flow. The ACL denies only ICMP echo to that server and permits other IP traffic."),
    steps: [
      step("Prepare the two reachable LANs", "Create ccna-06.pkt. Configure PC/server addressing and enable server HTTP in Services. On R1 assign .60.1/24 to G0/0 and .70.1/24 to G0/1, then no shutdown on both. Verify baseline ping and HTTP.", "Test before filtering so a later failure can be attributed to the rule rather than an unknown cabling or routing fault."),
      step("Enable lab-only SSH management", "Run the R1 configuration below. If the model prompts for RSA modulus after crypto key generate rsa, enter 2048 interactively. Connect from PC-A using ssh -l learner 192.168.60.1.", "SSH protects management transport. Local login and an SSH-only VTY policy are separate requirements; obfuscating a line password is not transport encryption.", "enable\nconfigure terminal\nhostname R1\nip domain-name ccna.lab\nusername learner secret LabOnly-ChangeMe-2026\ncrypto key generate rsa modulus 2048\nip ssh version 2\nline vty 0 4\n login local\n transport input ssh\nend\nshow ip ssh"),
      step("Apply an intentional echo denial", "Keep the console open. On R1 create and apply this inbound list on the client-facing G0/0. It denies only PC-A's echo request to the server and explicitly allows remaining IP traffic.", "ACLs evaluate in order. A specific denial must precede the broad permit; applying the list in the wrong direction may leave the intended flow unaffected.", "configure terminal\nip access-list extended LAB-FILTER\n deny icmp host 192.168.60.10 host 192.168.70.20 echo\n permit ip any any\nexit\ninterface gigabitEthernet0/0\n ip access-group LAB-FILTER in\nend\nshow access-lists\nshow ip interface gigabitEthernet0/0"),
      step("Verify a negative and positive result", "From PC-A ping the server (expected denial), open http://192.168.70.20 (expected success), and verify SSH to R1 still works. Save sanitized evidence without credentials.", "An expected denial is a passing security test when a permitted control flow still succeeds. Failure of every flow would not prove that this narrowly scoped policy is correct."),
    ],
    tests: [test("sec-ssh", "Encrypted management", "From PC-A connect with SSH and inspect R1 show ip ssh; do not put your secret in notes.", "SSHv2 login works; VTY transport accepts SSH only."), test("sec-deny", "Expected echo denial", "From PC-A ping 192.168.70.20 after applying the ACL; inspect counters where supported.", "Echo requests from the named client to the server fail as intended."), test("sec-allow", "Permitted control traffic", "Open the server's HTTP page from PC-A and repeat SSH to R1 after the ACL change.", "HTTP and router SSH still work, showing the policy is not a blanket outage.")],
    questions: [
      q("ccna-security-q1", "4.8", "Which VTY command restricts incoming remote management to SSH?", ["transport input telnet", "transport input ssh", "no ip routing", "switchport mode trunk"], 1, "transport input ssh allows SSH on the configured VTY lines. Telnet does not provide the intended encrypted transport, and interface/routing commands do not set VTY access.", ccnaSources.ssh),
      q("ccna-security-q2", "5.6", "What happens if permit ip any any is placed before this lab's specific ICMP deny?", ["The denial becomes stronger", "The router automatically reorders it", "The broad permit matches first and the intended denial is bypassed", "All traffic is always denied"], 2, "An extended ACL stops at the first matching entry. Place the specific denial before the broad permit to make it effective for the target flow.", ccnaSources.acl),
      q("ccna-security-q3", "5.6", "The requirement is to block only PC-A's echo to the server. Which evidence best demonstrates the intended result?", ["Both HTTP and SSH fail", "The hostname is R1", "The client received a DNS suffix", "Server ping fails but HTTP and router SSH still succeed"], 3, "A negative test plus positive controls shows the scoped restriction. A complete outage or unrelated naming observation does not validate the intended policy.", ccnaSources.acl),
      q("ccna-security-q4", "5.6", "What happens to traffic that matches no entry in an applied IP ACL?", ["It is denied by the implicit final denial", "It is always encrypted", "It becomes OSPF traffic", "It is sent to the DHCP server"], 0, "An applied ACL has an implicit denial after its configured entries. This lab uses an explicit permit for other traffic so the targeted denial does not block everything else.", ccnaSources.acl),
    ], sources: references("acl", "ssh"),
  },
  {
    id: "ccna-wireless", title: "WLAN connectivity & WPA2-PSK", assignment: "Stage 7 · Network / Security Fundamentals · 1.11 / 5.9 / 5.10", lessonId: "ccna-wireless", minutes: "30–45", goal: "Practice SSID, client association and WPA2-PSK with a simulated SOHO wireless router.", prerequisites: [...before, "Choose Packet Tracer's WRT300N and Laptop-PT. This introductory SOHO GUI exercise is not a Cisco WLC GUI lab or complete coverage of objective 2.9."],
    topology: topology("One simulated wireless LAN", [["Laptop-PT", "Wireless client · DHCP"], ["WRT300N · LAN", "SSID CertPath-Lab · WPA2 Personal / AES"], ["Wired PC → Ethernet 1", "192.168.0.20/24 · gateway 192.168.0.1"]], "Wireless router LAN is 192.168.0.1/24. Use DHCP range .100–.149 so the wired PC .20 is outside the pool. Leave the Internet port unconnected."),
    steps: [
      step("Prepare the router and clients", "Create ccna-07.pkt. Add WRT300N, a wired PC and Laptop-PT; cable the wired PC to Ethernet 1. Verify the laptop has a wireless module; power it off in Physical before swapping a module, then power it on.", "The client needs a compatible radio before any SSID or password setting can work. Do not confuse the router's Internet port with its LAN switch ports."),
      step("Configure LAN and SSID in the GUI", "On the router GUI Setup page set LAN 192.168.0.1/24, DHCP enabled with start .100 and 50 users; save. Under Wireless basic settings set SSID CertPath-Lab and channel 1 on this isolated 2.4 GHz lab.", "SSID names the wireless network. Channel selection is a radio setting, while the LAN and DHCP pool control IP addressing; they solve different problems."),
      step("Set and join WPA2 Personal", "In Wireless Security choose WPA2 Personal with AES and your own throwaway passphrase, then save. On Laptop-PT Desktop → PC Wireless join CertPath-Lab with the same passphrase. Set the wired PC to .20/24 and gateway .1.", "The SSID, security mode and pre-shared key must agree between client and router. Never publish the key in a screenshot or evidence note."),
      step("Test a wrong key and recover", "Record the laptop's DHCP address and ping the wired PC. Disconnect, try a deliberately wrong passphrase and record the failed association; reconnect with the correct key and save the repaired file.", "Authentication is different from receiving an IP lease. A wrong key prevents joining; changing DHCP is not the right repair for that failed authentication."),
    ],
    tests: [test("wifi-join", "Successful association", "Join with the correct lab key and inspect the laptop's IP configuration.", "Laptop associates with CertPath-Lab and receives an address in .100–.149."), test("wifi-lan", "Wireless-to-wired traffic", "From the associated laptop ping 192.168.0.20 after convergence.", "The wired host replies over the simulated LAN."), test("wifi-key", "Reject wrong authentication", "Try a wrong PSK, note failed association, then restore the correct key; omit keys from evidence.", "Wrong-key association fails; correct-key association and LAN reachability return.")],
    questions: [
      q("ccna-wifi-q1", "5.10", "The client has the correct SSID but an incorrect WPA2-PSK passphrase. Which fault should be fixed first?", ["OSPF area number", "Router static NAT mapping", "The client's PSK to match the WLAN", "EtherChannel passive mode"], 2, "An incorrect pre-shared key prevents successful WLAN authentication. Routing and DHCP changes do not fix that mismatch.", ccnaSources.wifi),
      q("ccna-wifi-q2", "1.11.b", "What does the SSID identify?", ["An IPv4 subnet mask", "An OSPF cost", "An ACL sequence number", "The wireless network name used by clients"], 3, "SSID identifies the wireless network for discovery and association. It is not itself an IP address, routing metric or access-list rule.", ccnaSources.blueprint),
      q("ccna-wifi-q3", "5.9", "Which setting matches this exercise's shared-key authentication design?", ["WPA2 Personal with a pre-shared key", "An open WLAN with no authentication", "WPA2 Enterprise requiring a RADIUS server", "A wired VLAN trunk only"], 0, "The lab uses WPA2 Personal, not Enterprise authentication. A shared key must match on the WLAN and client; the lab does not provide a RADIUS server.", ccnaSources.wifi),
      q("ccna-wifi-q4", "1.11", "A client authenticates to the WLAN but has no valid IPv4 lease. What should you check next in this lab?", ["The already-correct PSK only", "DHCP availability and the client IP configuration", "The OSPF router ID", "The switch EtherChannel group"], 1, "Successful association narrows the next check to addressing. Verify the pool and client DHCP selection instead of treating every wireless fault as a key mismatch.", ccnaSources.blueprint),
    ], sources: references("wifi"),
  },
  {
    id: "ccna-automation", title: "JSON, REST & automation decisions", assignment: "Stage 8 · Automation and Programmability · 6.1 / 6.3 / 6.4 / 6.5 / 6.7", lessonId: "ccna-automation", minutes: "25–40", goal: "Read a network inventory, distinguish safe reads from changes and review an AI recommendation against evidence.", prerequisites: ["Use a plain text editor. This is an offline automation worksheet, not a Packet Tracer API endpoint; no keys, cloud account or network calls are needed.", "Use the fictional JSON and request outline below. Do not send HTTP requests to production devices or paste real credentials into notes."],
    topology: topology("Controller-based workflow (conceptual)", [["Operator / application", "Northbound API · intended changes"], ["Controller", "Inventory, policy and validation"], ["Network devices", "Southbound communication · forwarding"]], "This is a conceptual diagram, not an implemented controller or running REST server. The worksheet explains the separation between applications, controller decisions and device forwarding."),
    steps: [
      step("Read a fictional inventory", "Create an offline worksheet. Identify the top-level object, devices array, hostname strings and up boolean values in the sample; count how many entries are down.", "JSON syntax and value types must be preserved. A quoted string such as \"false\" is not the boolean false.", '{\n  "devices": [\n    { "hostname": "R1", "up": true, "interfaces": 2 },\n    { "hostname": "SW1", "up": false, "interfaces": 24 }\n  ]\n}'),
      step("Classify a request without sending it", "Write the HTTP verb you would choose to read inventory, the need for authenticated HTTPS on a real service and how an unauthorized response differs from success. This outline is fictional, not a runnable API.", "A read uses GET; a real controller defines its endpoint, permissions and response schema. Never assume that adding a token to an invented URL makes it valid.", "GET /api/v1/devices\nAccept: application/json\n\nConceptual only: no hostname, credentials or live endpoint."),
      step("Plan a controlled configuration change", "Describe how to read the current configuration, validate a proposed change, apply it only with permission, check the result and roll back on failure. Identify which side of the controller faces your application.", "Automation repeats operations consistently but also repeats mistakes. A reviewed plan and verification are required before writing to device configuration."),
      step("Review an AI troubleshooting suggestion", "Your fictional inventory says SW1 is down. An AI suggestion says to disable every ACL. Explain why that suggestion is unsupported, list a safer first observation and write the evidence needed before making any change.", "A generated suggestion is not a verified diagnosis. Confirm device/link health and compare observations with the proposed cause before changing security controls."),
    ],
    tests: [test("auto-json", "Typed inventory interpretation", "Record the device count, the down hostname and whether up is a string or boolean.", "Two devices; SW1 is down; up values are booleans."), test("auto-rest", "Safe request classification", "State the read verb and describe an authorized successful response versus an unauthorized response.", "GET reads the resource; the real API requires valid authorization and an appropriate success status/schema."), test("auto-change", "Evidence-led automation", "Record a change plan with authorization, validation, result verification and rollback; reject the unsupported blanket ACL removal.", "Plan separates observations from assumptions and never treats an AI suggestion as permission to change production.")],
    questions: [
      q("ccna-auto-q1", "6.5", "Which HTTP method is intended to read the representation of an inventory resource?", ["DELETE", "POST to erase it", "PUT with a replacement document", "GET"], 3, "GET retrieves a representation. DELETE removes a resource, while PUT and POST can change server state according to the API contract.", ccnaSources.rest),
      q("ccna-auto-q2", "6.7", "In JSON, what is the type of the unquoted value false?", ["Boolean", "String", "Array", "Object"], 0, "The unquoted literal false is a boolean. Quoting it changes the value to a string; brackets and braces identify arrays and objects.", ccnaSources.rest),
      q("ccna-auto-q3", "6.3.b", "Which conceptual interface connects an application to a network controller?", ["The PC's power cable", "A northbound API", "The OSPF hello timer", "An access-port VLAN tag"], 1, "A northbound API exposes controller services to applications. Southbound communication connects the controller toward devices; the diagram is conceptual, not a live API.", ccnaSources.blueprint),
      q("ccna-auto-q4", "6.4", "An AI suggestion recommends removing every ACL because one device appears down. What is the responsible next step?", ["Apply it immediately to every router", "Assume generated output is verified evidence", "Check observed device/link state and validate the suggestion before any authorized change", "Publish the production passwords"], 2, "The inventory observation does not establish an ACL fault. AI assistance needs validation against actual evidence, scoped authorization and a rollback plan; it is not an automatic diagnosis.", ccnaSources.blueprint),
    ], sources: references("rest"),
  },
];
