/** Leveled index of the CCNA 200-301 lab topologies shown on this site.
 *
 * Source: the public lab catalog of NetSim 200-301 CCNA (Cisco CCNA 200-301), retrieved 2026-10-08
 * from https://api2.netsim.boson.com. Lab titles, catalog summaries and topology diagrams are the published
 * catalog metadata of a commercial simulator: they are indexed here for personal study, were not
 * written by this project, and are not covered by this project's license. See /ccna-topologies-attribution.txt.
 *
 * Levels follow the six official 200-301 v1.1 domains in blueprint order — the same order this
 * site teaches them — and every lab keeps its catalog summary unedited. A summary the source
 * catalog itself publishes for more than one lab is marked with summaryIssue instead of edited.
 * Level titles and weights were read from ./ccna.ts at generation time; scripts/validate-ccna-topologies.mjs
 * re-checks them. Generated by reference/boson-netsim-ccna/gen-klybit-topologies.mjs — edit that generator, not this file.
 */

export type CcnaTopologyDiagram = { src: string; width: number; height: number; bytes: number };
export type CcnaTopologyLab = { id: string; number: number; name: string; summary: string; summaryIssue?: string; diagram?: CcnaTopologyDiagram };

export const ccnaTopologySource = {
  catalog: "NetSim 200-301 CCNA",
  code: "CIS-NS-200301-01-02",
  exam: "Cisco CCNA 200-301",
  endpoint: "https://api2.netsim.boson.com",
  retrieved: "2026-10-08",
  notice: "/ccna-topologies-attribution.txt",
} as const;

export type CcnaTopologyLevel = {
  id: string; level: number; objective: string; title: string; weight: number;
  summary: string; labs: CcnaTopologyLab[]; withDiagram: number;
};

export const ccnaTopologyLevels: CcnaTopologyLevel[] = [
  {
    id: "ccna-topology-level-1", level: 1, objective: "1.0",
    title: "Network Fundamentals", weight: 20,
    summary: "Start with the parts: devices, interfaces, cabling, IPv4/IPv6 addressing and subnetting, and how a topology diagram is read.",
    labs: [
    { id: "ccna-topology-001", number: 1, name: "Explore Cisco Devices", summary: "In this lab, you will learn how to interpret a network topology diagram.", diagram: { src: "/ccna-topologies/network-fundamentals/001-explore-cisco-devices.png", width: 1233, height: 935, bytes: 102757 } },
    { id: "ccna-topology-002", number: 2, name: "Router Basics", summary: "In this lab, you will learn the basic operation of a router.", diagram: { src: "/ccna-topologies/network-fundamentals/002-router-basics.png", width: 1169, height: 942, bytes: 90264 } },
    { id: "ccna-topology-003", number: 3, name: "Switch Basics", summary: "In this lab, you will learn the basic operation of a switch.", diagram: { src: "/ccna-topologies/network-fundamentals/003-switch-basics.png", width: 1233, height: 935, bytes: 101497 } },
    { id: "ccna-topology-004", number: 4, name: "Configure a Cisco Device", summary: "In this lab, you will learn how to configure a Cisco IOS device from an unconfigured state.", diagram: { src: "/ccna-topologies/network-fundamentals/004-configure-a-cisco-device.png", width: 1233, height: 935, bytes: 101497 } },
    { id: "ccna-topology-005", number: 5, name: "Interpret Interface Errors", summary: "In this lab, you will learn how to interpret interface errors, including shutdown interfaces, duplex mismatches, and speed mismatches. You will also learn how to interpret the output of the show interfaces command.", diagram: { src: "/ccna-topologies/network-fundamentals/005-interpret-interface-errors.png", width: 787, height: 525, bytes: 32484 } },
    { id: "ccna-topology-006", number: 6, name: "Configure Global IPv4 Addressing", summary: "In this lab, you will configure global unicast IPv4 addressing on world-facing devices.", diagram: { src: "/ccna-topologies/network-fundamentals/006-configure-global-ipv4-addressing.png", width: 1233, height: 935, bytes: 101497 } },
    { id: "ccna-topology-007", number: 7, name: "Configure RFC 1918 IP Addressing", summary: "In this lab, you will configure an RFC 1918 IPv4 address range on devices that should not directly access the Internet.", diagram: { src: "/ccna-topologies/network-fundamentals/007-configure-rfc-1918-ip-addressing.png", width: 1233, height: 935, bytes: 101497 } },
    { id: "ccna-topology-008", number: 8, name: "Subnet an IPv4 Network", summary: "In this lab, you will learn how to subnet a network. You will also practice subnetting a network into a series of smaller networks.", diagram: { src: "/ccna-topologies/network-fundamentals/008-subnet-an-ipv4-network.png", width: 1233, height: 935, bytes: 101497 } },
    { id: "ccna-topology-009", number: 9, name: "Configure VLSM on an IPv4 Network", summary: "In this lab, create an IP addressing plan using the CIDR block you have been given.", diagram: { src: "/ccna-topologies/network-fundamentals/009-configure-vlsm-on-an-ipv4-network.png", width: 1300, height: 436, bytes: 70212 } },
    { id: "ccna-topology-010", number: 10, name: "Configure IPv6 Address Types", summary: "In this lab, you will learn about IPv6 address types and implement IPv6 addressing on the network.", diagram: { src: "/ccna-topologies/network-fundamentals/010-configure-ipv6-address-types.png", width: 1649, height: 1072, bytes: 149151 } },
    { id: "ccna-topology-011", number: 11, name: "Configure IPv6 by Using Modified EUI-64", summary: "In this lab, you will configure an automatic Internet Protocol version 6 (IPv6) addressing environment on Layer 3 switches by using modified extended unique identifier (EUI)-64.", diagram: { src: "/ccna-topologies/network-fundamentals/011-configure-ipv6-by-using-modified-eui-64.png", width: 2951, height: 2607, bytes: 224988 } },
    { id: "ccna-topology-012", number: 12, name: "Explore the MAC Address Table", summary: "In this lab, you will explore Switch1’s MAC address table.", diagram: { src: "/ccna-topologies/network-fundamentals/012-explore-the-mac-address-table.png", width: 1628, height: 564, bytes: 71854 } },
    { id: "ccna-topology-013", number: 13, name: "Implement IPv4 Addressing", summary: "In this lab, you will practice configuring Internet Protocol version 4 (IPv4) addressing on a complex network topology.", diagram: { src: "/ccna-topologies/network-fundamentals/013-implement-ipv4-addressing.png", width: 1431, height: 936, bytes: 114716 } },
    { id: "ccna-topology-014", number: 14, name: "Implement IPv6 Addressing", summary: "In this lab, you will practice configuring Internet Protocol version 6 (IPv6) addressing.", diagram: { src: "/ccna-topologies/network-fundamentals/014-implement-ipv6-addressing.png", width: 1060, height: 709, bytes: 135815 } },
    { id: "ccna-topology-015", number: 15, name: "Boson CCNA Challenge Lab 1", summary: "In this lab, you will configure a new, unconfigured network.", diagram: { src: "/ccna-topologies/network-fundamentals/015-boson-ccna-challenge-lab-1.png", width: 1248, height: 1298, bytes: 110645 } },
    ],
    withDiagram: 15,
  },
  {
    id: "ccna-topology-level-2", level: 2, objective: "2.0",
    title: "Network Access", weight: 20,
    summary: "Move to Layer 2: VLANs, trunks, inter-VLAN routing, spanning tree, EtherChannel and wireless access.",
    labs: [
    { id: "ccna-topology-016", number: 16, name: "Explore and Configure Switch Access Ports", summary: "In this lab, you will learn how to create, configure, examine, and delete virtual LANs (VLANs) on a switch.", diagram: { src: "/ccna-topologies/network-access/016-explore-and-configure-switch-access-ports.png", width: 1272, height: 525, bytes: 46820 } },
    { id: "ccna-topology-017", number: 17, name: "Explore and Configure Switch Trunk Ports", summary: "In this lab, you will learn how to configure and verify trunk ports on a switch.", diagram: { src: "/ccna-topologies/network-access/017-explore-and-configure-switch-trunk-ports.png", width: 1272, height: 525, bytes: 46820 } },
    { id: "ccna-topology-018", number: 18, name: "Configure InterVLAN Routing", summary: "In this lab, you will learn how to configure interVLAN routing by using a router-on-a-stick configuration.", diagram: { src: "/ccna-topologies/network-access/018-configure-intervlan-routing.png", width: 1272, height: 828, bytes: 64359 } },
    { id: "ccna-topology-019", number: 19, name: "Explore the Native VLAN", summary: "In this lab, you will learn how to view and modify the native VLAN.", diagram: { src: "/ccna-topologies/network-access/019-explore-the-native-vlan.png", width: 1272, height: 525, bytes: 46820 } },
    { id: "ccna-topology-020", number: 20, name: "Configure and Verify VTP", summary: "In this lab, you will learn how to configure a VTP domain name.", diagram: { src: "/ccna-topologies/network-access/020-configure-and-verify-vtp.png", width: 1064, height: 168, bytes: 28349 } },
    { id: "ccna-topology-021", number: 21, name: "Configure and Verify CDP", summary: "In this lab, you will learn how to use CDP to view connected neighbor devices.", diagram: { src: "/ccna-topologies/network-access/021-configure-and-verify-cdp.png", width: 800, height: 475, bytes: 37374 } },
    { id: "ccna-topology-022", number: 22, name: "Configure and Verify LLDP", summary: "In this lab, you will learn how to enable LLDP and use it to view connected neighbor devices.", diagram: { src: "/ccna-topologies/network-access/022-configure-and-verify-lldp.png", width: 800, height: 475, bytes: 37374 } },
    { id: "ccna-topology-023", number: 23, name: "Configure Layer 2 EtherChannel LACP", summary: "In this lab, you will learn how to create a Layer 2 EtherChannel by using LACP.", diagram: { src: "/ccna-topologies/network-access/023-configure-layer-2-etherchannel-lacp.png", width: 754, height: 191, bytes: 19187 } },
    { id: "ccna-topology-024", number: 24, name: "Configure Layer 3 EtherChannel LACP and Load Balancing", summary: "In this lab, you will learn how to create a Layer 3 EtherChannel by using LACP.", diagram: { src: "/ccna-topologies/network-access/024-configure-layer-3-etherchannel-lacp-and-load-balancing.png", width: 754, height: 191, bytes: 19187 } },
    { id: "ccna-topology-025", number: 25, name: "Explore Spanning Tree Protocol Port Roles", summary: "In this lab, you will learn how to determine the root bridge.", diagram: { src: "/ccna-topologies/network-access/025-explore-spanning-tree-protocol-port-roles.png", width: 748, height: 459, bytes: 42154 } },
    { id: "ccna-topology-026", number: 26, name: "Explore Spanning Tree Protocol Port States and PortFast", summary: "In this lab, you will watch a port transition through the STP port states.", diagram: { src: "/ccna-topologies/network-access/026-explore-spanning-tree-protocol-port-states-and-portfast.png", width: 748, height: 459, bytes: 42154 } },
    { id: "ccna-topology-027", number: 27, name: "Configure a Wireless LAN by Using the WLC GUI", summary: "In this lab, you will learn how to connect to the configuration interface of a Cisco 9800 wireless LAN controller (WLC).", diagram: { src: "/ccna-topologies/network-access/027-configure-a-wireless-lan-by-using-the-wlc-gui.png", width: 1086, height: 479, bytes: 108521 } },
    { id: "ccna-topology-028", number: 28, name: "Implement InterVLAN Routing", summary: "In this lab, you will implement interVLAN routing so that devices that are configured to operate in VLAN 100, VLAN 200, and VLAN 300 can communicate with each other.", diagram: { src: "/ccna-topologies/network-access/028-implement-intervlan-routing.png", width: 1136, height: 560, bytes: 147927 } },
    { id: "ccna-topology-029", number: 29, name: "Implement CDP and LLDP", summary: "In this lab, you will explore the differences between CDP and LLDP. In addition, you will configure both technologies.", diagram: { src: "/ccna-topologies/network-access/029-implement-cdp-and-lldp.png", width: 680, height: 1460, bytes: 72020 } },
    { id: "ccna-topology-030", number: 30, name: "Implement PVST+", summary: "In this lab, you will examine and configure a switched network that implements PVST+.", diagram: { src: "/ccna-topologies/network-access/030-implement-pvst.png", width: 1104, height: 982, bytes: 168786 } },
    { id: "ccna-topology-031", number: 31, name: "Boson CCNA Challenge Lab 2", summary: "In this lab, you will configure a network in which packets are routed between two separate virtual local area networks (VLANs).", diagram: { src: "/ccna-topologies/network-access/031-boson-ccna-challenge-lab-2.png", width: 757, height: 960, bytes: 52767 } },
    ],
    withDiagram: 16,
  },
  {
    id: "ccna-topology-level-3", level: 3, objective: "3.0",
    title: "IP Connectivity", weight: 25,
    summary: "Route between networks: routing-table behaviour, static and default routes, single-area OSPFv2/OSPFv3 and first-hop redundancy.",
    labs: [
    { id: "ccna-topology-032", number: 32, name: "Explore the Routing Table", summary: "In this lab, you will learn to interpret the output of an IPv4 routing table. In addition, you will learn how and why changes to routing tables occur.", diagram: { src: "/ccna-topologies/ip-connectivity/032-explore-the-routing-table.png", width: 4345, height: 4551, bytes: 338203 } },
    { id: "ccna-topology-033", number: 33, name: "Route Selection by Using Administrative Distance", summary: "In this lab, you will learn how trustworthiness as determined by AD affects route selection. You will also learn how to influence trustworthiness by modifying AD.", diagram: { src: "/ccna-topologies/ip-connectivity/033-route-selection-by-using-administrative-distance.png", width: 5226, height: 2826, bytes: 341778 } },
    { id: "ccna-topology-034", number: 34, name: "Route Selection by Using Routing Protocol Metric", summary: "In this lab, you will learn how Open Shortest Path First (OSPF) calculates a metric to determine the best path to a destination. You will also learn how to influence route selection by modifying the metric.", diagram: { src: "/ccna-topologies/ip-connectivity/034-route-selection-by-using-routing-protocol-metric.png", width: 5226, height: 2826, bytes: 341778 } },
    { id: "ccna-topology-035", number: 35, name: "Manually Configure Default Routes on IPv4 Networks", summary: "In this lab, you will learn to manually configure default routes on Cisco routers and switches.", diagram: { src: "/ccna-topologies/ip-connectivity/035-manually-configure-default-routes-on-ipv4-networks.png", width: 4345, height: 4551, bytes: 338203 } },
    { id: "ccna-topology-036", number: 36, name: "Manually Configure Default Routes on IPv6 Networks", summary: "In this lab, you will learn to manually configure IPv6 default routes on Cisco routers.", diagram: { src: "/ccna-topologies/ip-connectivity/036-manually-configure-default-routes-on-ipv6-networks.png", width: 2520, height: 2445, bytes: 131240 } },
    { id: "ccna-topology-037", number: 37, name: "Manually Configure Network Routes on IPv4 Networks", summary: "In this lab, you will learn to manually configure network routes on Cisco routers and Layer 3 switches.", diagram: { src: "/ccna-topologies/ip-connectivity/037-manually-configure-network-routes-on-ipv4-networks.png", width: 4345, height: 4551, bytes: 305651 } },
    { id: "ccna-topology-038", number: 38, name: "Manually Configure Network Routes on IPv6 Networks", summary: "In this lab, you will learn to manually configure IPv6 network routes on Cisco routers.", diagram: { src: "/ccna-topologies/ip-connectivity/038-manually-configure-network-routes-on-ipv6-networks.png", width: 2520, height: 2445, bytes: 131240 } },
    { id: "ccna-topology-039", number: 39, name: "Manually Configure Host Routes on IPv4 Networks", summary: "In this lab, you will learn to manually configure host routes on Cisco routers and Layer 3 switches.", diagram: { src: "/ccna-topologies/ip-connectivity/039-manually-configure-host-routes-on-ipv4-networks.png", width: 4345, height: 4551, bytes: 305651 } },
    { id: "ccna-topology-040", number: 40, name: "Manually Configure Host Routes on IPv6 Networks", summary: "In this lab, you will learn to manually configure IPv6 host routes on Cisco routers.", diagram: { src: "/ccna-topologies/ip-connectivity/040-manually-configure-host-routes-on-ipv6-networks.png", width: 2520, height: 2445, bytes: 131240 } },
    { id: "ccna-topology-041", number: 41, name: "Configure OSPFv2 Adjacencies", summary: "In this lab, you will implement, verify, and explore OSPF adjacencies.", diagram: { src: "/ccna-topologies/ip-connectivity/041-configure-ospfv2-adjacencies.png", width: 1144, height: 1263, bytes: 109137 } },
    { id: "ccna-topology-042", number: 42, name: "Configure Point-to-Point OSPFv2", summary: "In this lab, you will configure OSPF over point-to-point links.", diagram: { src: "/ccna-topologies/ip-connectivity/042-configure-point-to-point-ospfv2.png", width: 1144, height: 1263, bytes: 109310 } },
    { id: "ccna-topology-043", number: 43, name: "Explore OSPFv2 DR and BDR Router Selection", summary: "In this lab, you will explore OSPFv2 DR and BDR router selection on a broadcast network.", diagram: { src: "/ccna-topologies/ip-connectivity/043-explore-ospfv2-dr-and-bdr-router-selection.png", width: 1144, height: 1263, bytes: 108480 } },
    { id: "ccna-topology-044", number: 44, name: "Explore and Configure OSPFv2 Router IDs", summary: "In this lab, you will explore how OSPF chooses a router ID. In addition, you will manually configure an OSPF router ID.", diagram: { src: "/ccna-topologies/ip-connectivity/044-explore-and-configure-ospfv2-router-ids.png", width: 1144, height: 1263, bytes: 108480 } },
    { id: "ccna-topology-045", number: 45, name: "Plan and Configure Single-Area OSPF", summary: "Plan, implement, and verify Open Shortest Path First (OSPF) operation over local area network (LAN) interfaces and Frame Relay using point-to-point network type.", diagram: { src: "/ccna-topologies/ip-connectivity/045-plan-and-configure-single-area-ospf.png", width: 1110, height: 603, bytes: 72233 } },
    { id: "ccna-topology-046", number: 46, name: "Explore HSRP", summary: "In this lab, you will explore an HSRP configuration in order to learn how HSRP behaves.", diagram: { src: "/ccna-topologies/ip-connectivity/046-explore-hsrp.png", width: 1421, height: 770, bytes: 102867 } },
    { id: "ccna-topology-047", number: 47, name: "Explore VRRP", summary: "In this lab, you will explore a VRRP configuration in order to learn how VRRP behaves. You do not need to configure VRRP in this lab.", diagram: { src: "/ccna-topologies/ip-connectivity/047-explore-vrrp.png", width: 1421, height: 770, bytes: 102867 } },
    { id: "ccna-topology-048", number: 48, name: "Implement Route Selection", summary: "In this lab, you will influence route selection both by using AD and by manually configuring Open Shortest Path First version 2 (OSPFv2) metrics.", diagram: { src: "/ccna-topologies/ip-connectivity/048-implement-route-selection.png", width: 1104, height: 1320, bytes: 303334 } },
    { id: "ccna-topology-049", number: 49, name: "Implement Static and Default Routes", summary: "In this lab, you will manually configure default routes and network routes on Cisco routers and Layer 3 switches.", diagram: { src: "/ccna-topologies/ip-connectivity/049-implement-static-and-default-routes.png", width: 4274, height: 3699, bytes: 568036 } },
    { id: "ccna-topology-050", number: 50, name: "Implement Single-Area OSPFv2", summary: "In this lab, you will implement a single-area OSPFv2 configuration on five routers.", diagram: { src: "/ccna-topologies/ip-connectivity/050-implement-single-area-ospfv2.png", width: 6326, height: 4001, bytes: 510148 } },
    { id: "ccna-topology-051", number: 51, name: "Implement HSRP", summary: "In this lab, you will implement HSRP to learn how HSRP behaves.", diagram: { src: "/ccna-topologies/ip-connectivity/051-implement-hsrp.png", width: 3489, height: 2976, bytes: 406906 } },
    { id: "ccna-topology-052", number: 52, name: "Implement VRRP", summary: "In this lab, you will implement VRRP to learn how VRRP behaves.", diagram: { src: "/ccna-topologies/ip-connectivity/052-implement-vrrp.png", width: 3489, height: 2976, bytes: 406906 } },
    { id: "ccna-topology-053", number: 53, name: "Troubleshooting OSPF", summary: "In this lab, you will troubleshoot Open Shortest Path First (OSPF) operation over local area network (LAN) interfaces and wide area network (WAN) interfaces.", diagram: { src: "/ccna-topologies/ip-connectivity/053-troubleshooting-ospf.png", width: 1563, height: 1136, bytes: 220864 } },
    { id: "ccna-topology-054", number: 54, name: "Boson CCNA Challenge Lab 3", summary: "In this lab, you will configure Cisco IOS routing features on a network with multiple virtual local area networks (VLANs).", diagram: { src: "/ccna-topologies/ip-connectivity/054-boson-ccna-challenge-lab-3.png", width: 1443, height: 1678, bytes: 152470 } },
    ],
    withDiagram: 23,
  },
  {
    id: "ccna-topology-level-4", level: 4, objective: "4.0",
    title: "IP Services", weight: 10,
    summary: "Run the services: DHCPv4/DHCPv6, NAT, NTP, DNS, syslog, QoS handling, SSH, FTP and HTTP.",
    labs: [
    { id: "ccna-topology-055", number: 55, name: "Configure Static NAT", summary: "In this lab, you will configure static NAT to enable a specific host on a private LAN to communicate with an Internet host that is configured with a public IP address.", diagram: { src: "/ccna-topologies/ip-services/055-configure-static-nat.png", width: 1634, height: 699, bytes: 123118 } },
    { id: "ccna-topology-056", number: 56, name: "Configure Dynamic NAT", summary: "In this lab, you will configure dynamic NAT to enable a specified range of hosts on a private LAN to communicate with an Internet host that is configured with a public IP address.", diagram: { src: "/ccna-topologies/ip-services/056-configure-dynamic-nat.png", width: 1474, height: 608, bytes: 109732 } },
    { id: "ccna-topology-057", number: 57, name: "Configure PAT", summary: "In this lab, you will configure PAT to enable a specified range of hosts on a private LAN to communicate with an Internet host that is configured with a public IP address.", diagram: { src: "/ccna-topologies/ip-services/057-configure-pat.png", width: 1634, height: 699, bytes: 123118 } },
    { id: "ccna-topology-058", number: 58, name: "Configure an NTP Server", summary: "In this lab, you will learn how to configure client devices to authenticate NTP packets from the master NTP server and how to use access control lists (ACLs) and NTP access groups to restrict NTP synchronization from the master NTP server and to the NTP clients.", diagram: { src: "/ccna-topologies/ip-services/058-configure-an-ntp-server.png", width: 2301, height: 2164, bytes: 131787 } },
    { id: "ccna-topology-059", number: 59, name: "Configure an NTP Client", summary: "In this lab, you will learn how to configure routers and switches to use NTP for time synchronization.", diagram: { src: "/ccna-topologies/ip-services/059-configure-an-ntp-client.png", width: 2301, height: 2164, bytes: 131787 } },
    { id: "ccna-topology-060", number: 60, name: "Configure and Test a DNS Server", summary: "In this lab, you will configure and test a DNS server on a Cisco router.", diagram: { src: "/ccna-topologies/ip-services/060-configure-and-test-a-dns-server.png", width: 1021, height: 1144, bytes: 166498 } },
    { id: "ccna-topology-061", number: 61, name: "Explore Syslog Output", summary: "In this lab, you will learn about Cisco system log messages, the basic Syslog message format, and the relevant configuration options common across most Cisco devices.", diagram: { src: "/ccna-topologies/ip-services/061-explore-syslog-output.png", width: 3251, height: 2145, bytes: 340380 } },
    { id: "ccna-topology-062", number: 62, name: "Explore and Configure Syslog Levels", summary: "In this lab, you will learn how to configure and verify system message logging.", diagram: { src: "/ccna-topologies/ip-services/062-explore-and-configure-syslog-levels.png", width: 3251, height: 2151, bytes: 333731 } },
    { id: "ccna-topology-063", number: 63, name: "Configure DHCP for IPv4 Networks", summary: "In this lab, you will learn how to configure a VTP domain name.", summaryIssue: "The source catalog publishes another lab's summary for this entry; kept unedited and reported rather than guessed.", diagram: { src: "/ccna-topologies/ip-services/063-configure-dhcp-for-ipv4-networks.png", width: 8051, height: 6114, bytes: 840367 } },
    { id: "ccna-topology-064", number: 64, name: "Configure DHCP Relay for IPv4 Networks", summary: "In this lab, you will analyze the current DHCP configuration and then revise the configuration to use DHCP relay agents so that the DHCP servers can be managed from a central location.", diagram: { src: "/ccna-topologies/ip-services/064-configure-dhcp-relay-for-ipv4-networks.png", width: 8051, height: 6114, bytes: 840386 } },
    { id: "ccna-topology-065", number: 65, name: "Configure SSH", summary: "In this lab, you will configure and verify SSH on Router1.", diagram: { src: "/ccna-topologies/ip-services/065-configure-ssh.png", width: 957, height: 939, bytes: 57961 } },
    { id: "ccna-topology-066", number: 66, name: "Explore and Configure TFTP", summary: "Backup and restore a router's configuration to a Trivial File Transfer Protocol (TFTP) server.", diagram: { src: "/ccna-topologies/ip-services/066-explore-and-configure-tftp.png", width: 399, height: 977, bytes: 41839 } },
    { id: "ccna-topology-067", number: 67, name: "Explore and Configure FTP", summary: "In this lab, you will explore how FTP differs from TFTP." },
    { id: "ccna-topology-068", number: 68, name: "Implement NAT", summary: "In this lab, you will configure dynamic NAT to provide Internet access to hosts on multiple virtual local area networks (VLANs) and you will configure static NAT to enable a specific host on a private local area network (LAN) to be accessible from the Internet through a specific public IP address.", diagram: { src: "/ccna-topologies/ip-services/068-implement-nat.png", width: 4457, height: 2745, bytes: 463606 } },
    { id: "ccna-topology-069", number: 69, name: "Implement NTP", summary: "In this lab, you will configure Network Time Protocol (NTP) on several NTP client devices.", diagram: { src: "/ccna-topologies/ip-services/069-implement-ntp.png", width: 1378, height: 1667, bytes: 289741 } },
    { id: "ccna-topology-070", number: 70, name: "Implement DNS", summary: "In this lab, you will implement DNS on Cisco routers.", diagram: { src: "/ccna-topologies/ip-services/070-implement-dns.png", width: 5109, height: 3280, bytes: 502355 } },
    { id: "ccna-topology-071", number: 71, name: "Implement DHCP", summary: "In this lab, you will implement Dynamic Host Configuration Protocol (DHCP) relay agents to consolidate the DHCP configurations in an existing network installation.", diagram: { src: "/ccna-topologies/ip-services/071-implement-dhcp.png", width: 3982, height: 3901, bytes: 624806 } },
    { id: "ccna-topology-072", number: 72, name: "Implement SSH", summary: "In this lab, you will replace the existing Telnet configuration with a more secure SSH configuration.", diagram: { src: "/ccna-topologies/ip-services/072-implement-ssh.png", width: 957, height: 939, bytes: 57961 } },
    { id: "ccna-topology-073", number: 73, name: "Boson CCNA Challenge Lab 4", summary: "In this lab, you will configure some common Cisco Internet Protocol (IP) services on routers and switches.", diagram: { src: "/ccna-topologies/ip-services/073-boson-ccna-challenge-lab-4.png", width: 1057, height: 909, bytes: 105692 } },
    ],
    withDiagram: 18,
  },
  {
    id: "ccna-topology-level-5", level: 5, objective: "5.0",
    title: "Security Fundamentals", weight: 15,
    summary: "Protect the network: device hardening, password and AAA policy, access control lists, Layer 2 attacks and security features.",
    labs: [
    { id: "ccna-topology-074", number: 74, name: "Configure the Enable Password", summary: "In this lab, you will learn how to configure the enable password on a Cisco device.", diagram: { src: "/ccna-topologies/security-fundamentals/074-configure-the-enable-password.png", width: 704, height: 191, bytes: 24152 } },
    { id: "ccna-topology-075", number: 75, name: "Configure the Enable Secret Password", summary: "In this lab, you will learn how to configure an encrypted enable secret password on a Cisco device by using the enable secret command.", diagram: { src: "/ccna-topologies/security-fundamentals/075-configure-the-enable-secret-password.png", width: 704, height: 191, bytes: 24152 } },
    { id: "ccna-topology-076", number: 76, name: "Configure Local User Accounts", summary: "In this lab, you will learn how to configure local user accounts.", diagram: { src: "/ccna-topologies/security-fundamentals/076-configure-local-user-accounts.png", width: 704, height: 191, bytes: 24152 } },
    { id: "ccna-topology-077", number: 77, name: "Secure the Console and VTY Ports", summary: "In this lab, you will learn how to configure console port and VTY line passwords.", diagram: { src: "/ccna-topologies/security-fundamentals/077-secure-the-console-and-vty-ports.png", width: 704, height: 191, bytes: 24152 } },
    { id: "ccna-topology-078", number: 78, name: "Encrypt Passwords on a Cisco Device", summary: "In this lab, you will learn how to use the service password-encryption command to encrypt passwords on a Cisco device.", diagram: { src: "/ccna-topologies/security-fundamentals/078-encrypt-passwords-on-a-cisco-device.png", width: 703, height: 191, bytes: 23229 } },
    { id: "ccna-topology-079", number: 79, name: "Explore Password Complexity", summary: "In this lab, you will learn how to recognize vulnerable passwords as well as how to improve password security.", diagram: { src: "/ccna-topologies/security-fundamentals/079-explore-password-complexity.png", width: 704, height: 191, bytes: 24152 } },
    { id: "ccna-topology-080", number: 80, name: "Explore and Configure Standard Numbered ACLs", summary: "In this lab, you will learn to configure standard access control lists (ACLs).", diagram: { src: "/ccna-topologies/security-fundamentals/080-explore-and-configure-standard-numbered-acls.png", width: 1117, height: 1055, bytes: 105730 } },
    { id: "ccna-topology-081", number: 81, name: "Explore and Configure Extended Numbered ACLs", summary: "In this lab, you will learn to configure extended access control lists (ACLs).", diagram: { src: "/ccna-topologies/security-fundamentals/081-explore-and-configure-extended-numbered-acls.png", width: 1117, height: 1041, bytes: 106501 } },
    { id: "ccna-topology-082", number: 82, name: "Explore and Configure Numbered IP ACLs", summary: "In this lab, you will build standard and extended IP access lists to filter inbound traffic on Router1s Serial 0/0 interface.", diagram: { src: "/ccna-topologies/security-fundamentals/082-explore-and-configure-numbered-ip-acls.png", width: 1078, height: 766, bytes: 86869 } },
    { id: "ccna-topology-083", number: 83, name: "Configure Standard Named ACLs", summary: "In this lab, you will learn how to configure and verify named standard ACLs.", diagram: { src: "/ccna-topologies/security-fundamentals/083-configure-standard-named-acls.png", width: 1188, height: 789, bytes: 145914 } },
    { id: "ccna-topology-084", number: 84, name: "Configure Extended Named ACLs", summary: "In this lab, you will learn to configure extended named ACLs.", diagram: { src: "/ccna-topologies/security-fundamentals/084-configure-extended-named-acls.png", width: 1112, height: 1052, bytes: 103416 } },
    { id: "ccna-topology-085", number: 85, name: "Explore and Configure Port Security", summary: "In this lab, you will learn how to configure and troubleshoot port security on a switch.", diagram: { src: "/ccna-topologies/security-fundamentals/085-explore-and-configure-port-security.png", width: 701, height: 635, bytes: 33962 } },
    { id: "ccna-topology-086", number: 86, name: "Explore AAA", summary: "In this lab, you will explore AAA on Cisco devices.", diagram: { src: "/ccna-topologies/security-fundamentals/086-explore-aaa.png", width: 682, height: 516, bytes: 36576 } },
    { id: "ccna-topology-087", number: 87, name: "Implement Passwords", summary: "In this lab, you will configure an enable password, an enable secret password, and passwords to protect user EXEC mode on Cisco devices.", diagram: { src: "/ccna-topologies/security-fundamentals/087-implement-passwords.png", width: 1914, height: 2076, bytes: 162907 } },
    { id: "ccna-topology-088", number: 88, name: "Implement Local User Accounts", summary: "In this lab, you will configure local user accounts. You will configure the console port and VTY port to require local user account authentication.", diagram: { src: "/ccna-topologies/security-fundamentals/088-implement-local-user-accounts.png", width: 805, height: 1004, bytes: 120376 } },
    { id: "ccna-topology-089", number: 89, name: "Implement Standard ACLs", summary: "In this lab, you will configure and verify both named and numbered standard ACLs. You will verify your configuration by using Ping and Telnet.", diagram: { src: "/ccna-topologies/security-fundamentals/089-implement-standard-acls.png", width: 761, height: 945, bytes: 54614 } },
    { id: "ccna-topology-090", number: 90, name: "Implement Extended ACLs", summary: "In this lab, you will configure and verify both named and numbered extended ACLs. You will verify your configuration by using Ping and Telnet.", diagram: { src: "/ccna-topologies/security-fundamentals/090-implement-extended-acls.png", width: 761, height: 945, bytes: 54614 } },
    { id: "ccna-topology-091", number: 91, name: "Implement Port Security", summary: "In this lab, you will configure port security on Switch1 and Switch2.", diagram: { src: "/ccna-topologies/security-fundamentals/091-implement-port-security.png", width: 1060, height: 945, bytes: 62641 } },
    { id: "ccna-topology-092", number: 92, name: "Troubleshoot Port Security", summary: "In this lab, you will learn how to configure and verify port security on a switch.", diagram: { src: "/ccna-topologies/security-fundamentals/092-troubleshoot-port-security.png", width: 701, height: 635, bytes: 33962 } },
    { id: "ccna-topology-093", number: 93, name: "Troubleshoot ACLs", summary: "In this lab, you will learn to identify configuration issues and use access control lists (ACLs) to fix problems throughout the example.com network. Ensure that all virtual local area networks (VLANs) with networks on Switch2 can ping all devices on the network by IP address, by host name, and by fully qualified domain name (FQDN).", diagram: { src: "/ccna-topologies/security-fundamentals/093-troubleshoot-acls.png", width: 3939, height: 2614, bytes: 304400 } },
    { id: "ccna-topology-094", number: 94, name: "Troubleshooting ACLs 1 - Extended ACLs", summary: "In this lab, you will troubleshoot extended access control lists (ACLs) on Cisco routers and verify ACLs using show commands and network connectivity tests.", diagram: { src: "/ccna-topologies/security-fundamentals/094-troubleshooting-acls-1-extended-acls.png", width: 2614, height: 1730, bytes: 190313 } },
    { id: "ccna-topology-095", number: 95, name: "Troubleshooting ACLs 2 - Standard ACLs", summary: "In this lab, you will roubleshoot standard access control lists (ACLs) on Cisco routers and verify ACLs using show commands and network connectivity tests.", diagram: { src: "/ccna-topologies/security-fundamentals/095-troubleshooting-acls-2-standard-acls.png", width: 2614, height: 1730, bytes: 190313 } },
    { id: "ccna-topology-096", number: 96, name: "Troubleshooting ACLs 3 - Named ACLs", summary: "In this lab, you will troubleshoot named access control lists (ACLs) on Cisco routers and verify ACLs using show commands and network connectivity tests.", diagram: { src: "/ccna-topologies/security-fundamentals/096-troubleshooting-acls-3-named-acls.png", width: 2614, height: 1730, bytes: 190313 } },
    { id: "ccna-topology-097", number: 97, name: "Boson CCNA Challenge Lab 5", summary: "In this lab, you will configure Cisco security features on routers and switches.", diagram: { src: "/ccna-topologies/security-fundamentals/097-boson-ccna-challenge-lab-5.png", width: 1057, height: 909, bytes: 105692 } },
    ],
    withDiagram: 24,
  },
  {
    id: "ccna-topology-level-6", level: 6, objective: "6.0",
    title: "Automation and Programmability", weight: 10,
    summary: "Describe and automate the modern network: controller-based and SDN architectures, REST APIs, JSON data and configuration tools.",
    labs: [
    { id: "ccna-topology-098", number: 98, name: "Compare a Traditional Network to a Controller-Based Network", summary: "In this lab, you will learn how to differentiate between a traditional network and a controller-based network." },
    { id: "ccna-topology-099", number: 99, name: "Explore HTTP Server Verbs", summary: "In this lab, you will learn about the specific HTTP verbs that REST APIs use." },
    { id: "ccna-topology-100", number: 100, name: "Submit and Explore Ansible, Chef, and Puppet Queries", summary: "In this lab, you will learn the differences between three common configuration management mechanisms: Ansible, Chef, and Puppet." },
    { id: "ccna-topology-101", number: 101, name: "Obtain and Interpret JSON Output", summary: "In this lab, you will learn how JSON output is obtained and how to interpret JSON output." },
    ],
    withDiagram: 0,
  },
];

export const ccnaTopologyStats = {
  levels: ccnaTopologyLevels.length,
  labs: ccnaTopologyLevels.reduce((sum, level) => sum + level.labs.length, 0),
  diagrams: ccnaTopologyLevels.reduce((sum, level) => sum + level.withDiagram, 0),
  summaryIssues: ccnaTopologyLevels.reduce((sum, level) => sum + level.labs.filter((lab) => lab.summaryIssue).length, 0),
} as const;

export const ccnaTopologyLabs: CcnaTopologyLab[] = ccnaTopologyLevels.flatMap((level) => level.labs);
