import type { LabQuestion, LabTest, ServerLab } from "./server-labs";

/** Original Docker learning scenarios. No certification question dumps. */
export const dockerSources = {
  install: "https://docs.docker.com/desktop/setup/install/windows-install/",
  engine: "https://docs.docker.com/engine/install/",
  containers: "https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-container/",
  run: "https://docs.docker.com/reference/cli/docker/container/run/",
  logs: "https://docs.docker.com/reference/cli/docker/container/logs/",
  dockerfile: "https://docs.docker.com/get-started/docker-concepts/building-images/writing-a-dockerfile/",
  volumes: "https://docs.docker.com/engine/storage/volumes/",
  bind: "https://docs.docker.com/engine/storage/bind-mounts/",
  network: "https://docs.docker.com/engine/network/drivers/bridge/",
  compose: "https://docs.docker.com/compose/gettingstarted/",
  down: "https://docs.docker.com/reference/cli/docker/compose/down/",
  readiness: "https://docs.docker.com/compose/how-tos/startup-order/",
};
const S = dockerSources;
const q = (id: string, text: string, options: string[], correct: number, explain: string, source: string): LabQuestion => ({ id: `docker-q-${id}`, text, options, correct, explain, source });
const test = (id: string, title: string, procedure: string, expected: string): LabTest => ({ id, title, procedure, expected, points: 1 });
const refs = (...entries: Array<[string, string]>) => entries.map(([title, url]) => ({ title, url }));
const safe = "Use a learner-owned machine or disposable Linux VM. Keep production data, credentials and the Docker socket out of containers. Never use global prune commands for these labs.";
export const dockerDockerfile = `FROM python:3.13-alpine
WORKDIR /app
COPY index.html .
USER 10001:10001
EXPOSE 8080
CMD ["python", "-m", "http.server", "8080", "--bind", "0.0.0.0"]`;
export const dockerIndex = '<!doctype html><html lang="en"><meta charset="utf-8"><title>CertPath Docker lab</title><h1>My Docker lab works</h1></html>';
export const dockerCompose = `name: certpath-lab
services:
  app:
    build: .
    restart: unless-stopped
  gateway:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8082:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app`;
export const dockerNginx = `server {
  listen 80;
  location / {
    proxy_pass http://app:8080;
  }
}`;

export const dockerLabs: ServerLab[] = [
  {
    id: "docker-setup", title: "Understand containers and prepare Docker", assignment: "Docker Foundations · 1 / 6", lessonId: "docker-setup", minutes: "30–45",
    goal: "Distinguish an image from a container and verify a working Linux-container engine before starting the labs.",
    prerequisites: [safe, "Internet access for trusted image downloads. Check current Docker Desktop eligibility and licensing before installation; no paid plan or Docker Hub account is required by this course."],
    steps: [
      { title: "Choose the correct environment", instruction: "On a supported Windows 10/11 client, follow Docker's official Desktop instructions and choose Linux containers. A disposable Linux VM with Docker Engine is another option. Docker Desktop is not supported on Windows Server. Do not install anything on a production domain controller.", explain: "A Linux container needs a Linux kernel. On Windows clients, Desktop provides that environment; an image is not a complete virtual machine with its own independently booted kernel." },
      { title: "Verify the client and engine", instruction: "Start the engine, then run these read-only checks. docker version must show both Client and Server. The selected context must point to your intended lab engine, and the server OS must be linux. Stop here if it points to a remote production engine.", command: "docker context show\ndocker version\ndocker info --format '{{.OSType}}'\ndocker compose version", explain: "Having a CLI installed does not prove the daemon is running. A client-only version report or a connection error must be resolved before running containers." },
      { title: "Run a disposable first container", instruction: "Run the official hello-world image and save its successful output. This container prints a message and exits normally; it is not meant to stay running.", command: "docker run --rm hello-world", explain: "The engine pulls an image if it is absent, creates a container and runs its process. --rm removes this disposable container after exit; the downloaded image can remain." },
      { title: "Read image and container inventory", instruction: "Compare the downloaded image inventory with the container inventory. Explain why hello-world appears as an image but its --rm container does not remain in the container list.", command: "docker image ls\ndocker ps -a", explain: "The reusable image and each runtime container are different objects. Containers do not need to be running for their images to remain available." },
    ],
    tests: [test("engine", "Engine is reachable", "Capture docker version, the selected context and the server OS, with secrets removed.", "Client and Server are present; the intended lab engine reports linux."), test("hello", "First container exits normally", "Run docker run --rm hello-world and capture its output and successful exit status.", "The welcome output is shown and the process exits successfully."), test("objects", "Image versus runtime", "Compare docker image ls and docker ps -a after hello-world. Explain the difference in your own words.", "The image remains; the disposable hello-world container is absent.")],
    questions: [
      q("image", "You need to create three independent instances of the same application. Which object is the reusable template?", ["A stopped terminal", "A Docker image", "A published host port", "A container log"], 1, "An image provides the application filesystem and configuration used to create containers. Three containers can be created from one image; their runtime state is separate.", S.containers),
      q("kernel", "Several ordinary Linux containers run on the same Docker Engine. Which statement about their kernel is correct?", ["Each container boots an unrelated kernel", "The image always contains a full Windows kernel", "The containers use the engine host's Linux kernel", "Containers cannot run inside a VM"], 2, "Process isolation does not mean each container boots its own operating system kernel. Linux containers share the kernel of the environment running the engine, which may itself be a VM.", S.containers),
      q("daemon", "docker version shows Client information and an error connecting to Server. What should you check first?", ["Engine availability and the selected Docker context", "The app's HTML title", "Whether every image is public", "A firewall rule inside a nonexistent container"], 0, "First establish that the CLI can reach the intended daemon. Checking a container's application port cannot fix a client-to-engine connection problem.", S.run),
      q("server", "A learner wants to install Docker Desktop directly on a Windows Server domain controller. What is the appropriate course setup?", ["Install Desktop on the DC and disable AD DS", "Enable --privileged for every container", "Use a shared administrator password", "Use a supported client or isolated Linux Engine VM instead"], 3, "Docker Desktop's Windows support targets supported client editions, not Windows Server. Keep these beginner Linux-container exercises separate from the domain-controller lab.", S.install),
    ], sources: refs(["Windows installation and supported systems", S.install], ["Docker Engine installation", S.engine], ["Containers and VMs", S.containers], ["Client-to-engine execution", S.run]),
  },
  {
    id: "docker-lifecycle", title: "Run, inspect and troubleshoot a web container", assignment: "Docker Foundations · 2 / 6", lessonId: "docker-lifecycle", minutes: "30–45", goal: "Publish a local-only web port and explain running, stopped and removed container states.", prerequisites: [safe, "Complete setup. Host port 8080 must be free. All commands below operate only on the named cp-web container."],
    steps: [
      { title: "Start a local-only web service", instruction: "Create cp-web from the official nginx image. Open http://127.0.0.1:8080 on this same machine. In this mapping, 8080 belongs to the host and 80 belongs to the container. Loopback binding is intentional.", command: "docker run -d --name cp-web -p 127.0.0.1:8080:80 nginx:alpine\ndocker ps", explain: "A host port mapping makes the service reachable outside the container. Binding to 127.0.0.1 avoids intentionally publishing this lab service on every host interface." },
      { title: "Inspect before changing settings", instruction: "Capture the port mapping, recent stdout/stderr logs and container state. An application timeout should lead to checking process state, mapping and logs before changing firewall policy.", command: "docker port cp-web\ndocker logs --tail 20 cp-web\ndocker inspect cp-web", explain: "These commands answer different questions: where traffic goes, what the process logged, and how the runtime is configured." },
      { title: "Stop and restart the same container", instruction: "Stop cp-web, verify the browser connection fails, then start the same container and verify the page returns. Compare docker ps with docker ps -a while it is stopped.", command: "docker stop cp-web\ndocker ps -a\ndocker start cp-web", explain: "Stopping a container stops its main process but retains the container object. Starting it again differs from docker run, which creates a new container." },
      { title: "Remove only the lab container", instruction: "After saving evidence, stop and remove cp-web. Confirm the object is absent. This does not require deleting the image or any unrelated workload.", command: "docker stop cp-web\ndocker rm cp-web", explain: "Cleanup is deliberately scoped by exact name. A global system prune could remove someone else's stopped containers, cached images or data." },
    ],
    tests: [test("http", "Local HTTP works", "Open 127.0.0.1:8080 and record docker port cp-web.", "An nginx page loads and the mapping is host loopback 8080 to container 80."), test("restart", "Lifecycle is understood", "Check HTTP and inventory during stop, then after start.", "Stopped cp-web is in ps -a, not ps; HTTP returns after start."), test("cleanup", "Scoped cleanup", "Record inventories after removing cp-web.", "cp-web is absent and unrelated workloads are unchanged.")],
    questions: [
      q("ports", "For -p 127.0.0.1:8080:80, which URL should the learner open on the Docker host?", ["http://127.0.0.1:80", "http://cp-web:8080 on every LAN device", "http://127.0.0.1:8080", "https://127.0.0.1:443"], 2, "The host-side port is 8080. Docker forwards traffic arriving at the host's loopback address to port 80 in the container; this does not configure HTTPS.", S.run),
      q("stopped", "cp-web was stopped and disappeared from docker ps. Which check distinguishes a stopped object from a removed one?", ["docker ps -a", "docker image pull", "docker network prune", "docker compose version"], 0, "docker ps lists running containers by default; -a includes stopped ones. Absence from the running list alone does not prove removal.", S.run),
      q("logs", "A running container's application is returning errors. Which command reads its recent stdout/stderr output?", ["docker volume create cp-web", "docker logs --tail 20 cp-web", "docker image rm cp-web", "docker context create cp-web"], 1, "docker logs reads the container process output collected by its logging mechanism. It does not open every arbitrary application file or repair the application.", S.logs),
      q("name", "docker run --name cp-web fails because that name is already in use. What should you do first?", ["Delete every volume", "Publish the Docker socket", "Disable all isolation", "Inspect the existing cp-web object before reusing or removing it"], 3, "Container names are unique within an engine, including stopped containers. Identify the existing object and whether its data matters before choosing a deliberate start, rename or scoped removal.", S.run),
    ], sources: refs(["Run options and port publishing", S.run], ["Container logs", S.logs]),
  },
  {
    id: "docker-images", title: "Build your own non-root application image", assignment: "Docker Foundations · 3 / 6", lessonId: "docker-images", minutes: "40–60", goal: "Create a small Dockerfile, build a versioned image and verify what is actually running.", prerequisites: [safe, "Use a new empty folder named certpath-docker-lab. The examples use Linux containers, Docker CLI and plain text files; no local Python installation is needed."],
    steps: [
      { title: "Create the application file", instruction: "In certpath-docker-lab, create a plain UTF-8 file named index.html with the following content. Make sure the editor has not added a .txt extension. Keep this folder as the build context for later Compose lessons.", command: dockerIndex, explain: "The application content is deliberately tiny, so you can focus on how files move from the build context into an image." },
      { title: "Write the Dockerfile", instruction: "Create a plain text file named Dockerfile with no extension, next to index.html. FROM sets the base; COPY includes your page; USER makes the runtime non-root; CMD starts the server. This development HTTP server is a teaching example, not a production web deployment.", command: dockerDockerfile, explain: "RUN, if used, executes during a build; CMD supplies the default runtime command. EXPOSE documents port 8080 but does not publish a host port." },
      { title: "Build and run the image", instruction: "Open your terminal in the lab folder. Build cp-page:1.0 using the dot as the current build context, then publish it only on loopback. Open http://127.0.0.1:8081 and capture the page and process identity.", command: "docker build -t cp-page:1.0 .\ndocker run -d --name cp-page -p 127.0.0.1:8081:8080 cp-page:1.0\ndocker exec cp-page id", explain: "COPY only sees files in the build context unless a separately configured feature supplies them. A version tag helps identify the intended image, but tags can still be reassigned." },
      { title: "Change content and rebuild deliberately", instruction: "Change the heading in index.html, build cp-page:1.1, then stop/remove only cp-page and recreate it using 1.1. Verify the new page. Keep the image for the networking exercise; remove the runtime after tests.", command: "docker build -t cp-page:1.1 .\ndocker stop cp-page\ndocker rm cp-page\ndocker run -d --name cp-page -p 127.0.0.1:8081:8080 cp-page:1.1", explain: "Changing a host source file does not rewrite an existing image's COPY layer. Building a new tag also does not replace an already running container; recreation is a separate operation." },
    ],
    tests: [test("custom", "Custom image serves the page", "Record build success, cp-page image identity and the page at 127.0.0.1:8081.", "The intended page is served from the version you built."), test("nonroot", "Runtime is non-root", "Run docker exec cp-page id and record output.", "The runtime user is UID 10001, not root."), test("rebuild", "Update is reproducible", "Show the changed heading after rebuilding 1.1 and recreating cp-page; then stop/remove cp-page.", "The new heading appears and only the lab container is cleaned up.")],
    questions: [
      q("expose", "The Dockerfile says EXPOSE 8080, but no host port was published. Does EXPOSE alone make the page available at host localhost:8080?", ["Yes, on every interface", "Yes, if the image has a tag", "Only when USER is root", "No; create an appropriate runtime port mapping"], 3, "EXPOSE records the intended container port. A runtime publishing option such as -p supplies the host-to-container mapping; the two are not interchangeable.", S.dockerfile),
      q("cmd", "Which instruction supplies this image's default HTTP-server process when a container starts?", ["COPY", "CMD", "WORKDIR", "A README heading"], 1, "CMD defines the default runtime command. COPY includes files and WORKDIR chooses a directory; neither of them independently starts the service.", S.dockerfile),
      q("copy", "You edited index.html on the host, but the existing cp-page container still serves the old heading. No bind mount is used. Why?", ["A copied image file is not a live connection to the host file", "Docker automatically ignores all HTML", "Every tag is an immutable checksum", "EXPOSE caches the page forever"], 0, "COPY placed a snapshot of the file into the image at build time. Rebuild with the changed source and recreate the runtime, or deliberately use a development bind mount.", S.bind),
      q("user", "docker exec cp-page id reports uid=10001. Which Dockerfile instruction configured the default runtime identity?", ["EXPOSE", "COPY", "USER", "FROM always sets UID 10001"], 2, "USER selects the runtime user. Non-root execution reduces some risks but does not by itself make an image or its application secure.", S.dockerfile),
    ], sources: refs(["Dockerfile instructions", S.dockerfile], ["Bind mounts versus copied files", S.bind]),
  },
  {
    id: "docker-storage", title: "Keep data across container replacement", assignment: "Docker Foundations · 4 / 6", lessonId: "docker-storage", minutes: "30–45", goal: "Prove named-volume persistence and distinguish it from a container's writable layer.", prerequisites: [safe, "Use only the new cp-notes volume. Never put host root folders or actual business data into this test."],
    steps: [
      { title: "Create a named volume", instruction: "Create cp-notes and inspect its metadata. This lesson stores one harmless note. Do not edit Docker's internal volume directories manually.", command: "docker volume create cp-notes\ndocker volume inspect cp-notes", explain: "A named volume is managed separately from any individual container, so multiple short-lived containers can use the same data." },
      { title: "Write through a disposable container", instruction: "Run this one-line command from PowerShell or a Linux shell. The sh command executes inside Alpine, not on the host. Record the note, not any secrets.", command: "docker run --rm --mount type=volume,source=cp-notes,target=/data alpine:3.22 sh -c 'echo first-note > /data/note.txt'", explain: "The disposable runtime is removed after exit, but the named volume is not. Its mounted /data path stores the note outside that runtime's writable layer." },
      { title: "Read from a replacement container", instruction: "Start a new disposable Alpine container with the same named volume mounted read-only. Read the note. Compare this with data written only into a removed container's writable layer.", command: "docker run --rm --mount type=volume,source=cp-notes,target=/data,readonly alpine:3.22 cat /data/note.txt", explain: "Read-only applies to this mount in this container. Recreating the runtime does not delete the volume; deleting the volume is a different, destructive action." },
      { title: "Record retention and cleanup", instruction: "Inspect cp-notes after the reader exits. Keep it until your evidence is saved. If it contains only this disposable test note and no container uses it, you may explicitly remove just cp-notes. Record that the removal destroys this test data.", command: "docker volume inspect cp-notes\n# Optional, only after confirming this is your disposable test volume:\ndocker volume rm cp-notes", explain: "A volume is not automatically a backup. Deletion, corruption or host failure can still lose its data. Never use volume prune as a shortcut here." },
    ],
    tests: [test("retained", "Note survives writer removal", "Run the writer and reader commands and capture first-note in the new reader.", "The replacement container reads first-note."), test("readonly", "Read-only mount is enforced", "Using a reader mount with readonly, try writing a second harmless note through sh -c.", "The write is rejected; the original note is still readable."), test("inventory", "Retention decision is explicit", "Record whether cp-notes is retained or deliberately removed, and why.", "No unrelated volume is changed; the learner identifies the data-loss consequence of removal.")],
    questions: [
      q("persist", "A --rm container wrote a note into the named cp-notes volume and exited. What happens to that named volume?", ["It is always erased", "It becomes a network", "It remains until deliberately removed", "It is automatically uploaded to Docker Hub"], 2, "Removing this disposable container does not remove its named volume. A replacement container can mount cp-notes and read the same note.", S.volumes),
      q("bind", "You want a development container to see edits to a particular host source folder. Which storage mechanism fits that requirement?", ["A bind mount of that specific folder", "A tag rename", "An EXPOSE instruction", "A fresh unrelated named volume with no copied files"], 0, "A bind mount maps a chosen host path into a container. Scope it carefully; a writable bind mount can let a container change files on the host.", S.bind),
      q("readonly", "A reader should inspect a note without changing it. Which mount configuration expresses that intent?", ["--privileged", "Mount cp-notes with readonly", "Publish port 443", "Delete the note first"], 1, "A read-only mount prevents writes through that mount. It does not encrypt the note or prevent a separate writer from changing the same volume.", S.volumes),
      q("backup", "A team says a named volume means they no longer need backups. What is the best response?", ["Correct; volumes cannot be corrupted", "Correct; every volume is replicated automatically", "Correct; rm always moves data to a recycle bin", "Persistence across replacement is not an independent backup"], 3, "A volume survives a container replacement, but that is different from having a recoverable independent copy. Plan and test backups for data that matters.", S.volumes),
    ], sources: refs(["Named volumes and lifecycle", S.volumes], ["Bind mount safety", S.bind]),
  },
  {
    id: "docker-network", title: "Connect containers using service names", assignment: "Docker Foundations · 5 / 6", lessonId: "docker-network", minutes: "30–45", goal: "Test container-to-container HTTP on a user-defined network without exposing the server to the host.", prerequisites: [safe, "Complete the image lesson so cp-page:1.1 exists. Ensure cp-net and cp-internal are names reserved for your own lab."],
    steps: [
      { title: "Create a scoped bridge network", instruction: "Create the user-defined cp-net network. Keep the default driver for this local exercise; do not modify existing organizational networks.", command: "docker network create cp-net\ndocker network inspect cp-net", explain: "A user-defined bridge provides name resolution between its containers. Treat membership and published ports as distinct configuration choices." },
      { title: "Start an unpublished backend", instruction: "Run your built page as cp-internal on cp-net without -p. Check that docker port cp-internal has no host mapping. The backend still listens on its container port 8080.", command: "docker run -d --name cp-internal --network cp-net cp-page:1.1\ndocker port cp-internal", explain: "Containers on the same network can reach the application without publishing a port on the host. Lack of a host mapping is not an application listener failure." },
      { title: "Test name resolution and HTTP", instruction: "Use a disposable Alpine client on the same network. It should fetch the page by the server's name. The command below runs wget inside the client container.", command: "docker run --rm --network cp-net alpine:3.22 wget -qO- http://cp-internal:8080", explain: "cp-internal is resolved in this network's DNS scope. Inside a client container, localhost would mean that client itself, not another container." },
      { title: "Compare another network and clean up", instruction: "Try the same fetch from a disposable client without --network cp-net. Name resolution should fail there. Save both results, then remove only cp-internal and the now-unused cp-net.", command: "docker run --rm alpine:3.22 wget -qO- http://cp-internal:8080\ndocker stop cp-internal\ndocker rm cp-internal\ndocker network rm cp-net", explain: "The negative test concerns this scoped service name, not a claim that Docker networks are a complete security boundary or that every route between networks is impossible." },
    ],
    tests: [test("same-network", "Same-network HTTP", "Run the client on cp-net and capture its page response.", "The page is retrieved by cp-internal:8080."), test("other-network", "DNS scope negative test", "Run a default-network client and capture its failed name lookup.", "cp-internal is not resolved through cp-net's scoped DNS."), test("unpublished", "No host port needed", "Capture docker port cp-internal before cleanup, then verify named cleanup.", "There is no host mapping; the same-network client still worked and only lab objects are removed.")],
    questions: [
      q("dns", "Two containers on cp-net need stable addressing while container IPs may change. What should the client use?", ["The other container's localhost", "The other container's network-scoped name", "A saved IP from last month", "The host's Windows username"], 1, "User-defined bridge networking supplies scoped DNS. Use the backend's name and container port rather than hard-coding its current IP.", S.network),
      q("localhost", "Inside a disposable client container, http://localhost:8080 fails although cp-internal works. What does localhost refer to?", ["Every container simultaneously", "The Docker registry", "The client container's own network namespace", "The host's browser tab"], 2, "The client's loopback address is not the backend's loopback address. Address cp-internal:8080 over the shared user-defined network.", S.network),
      q("internal-port", "cp-internal listens on 8080 and the client shares cp-net. No host port is published. What is the intended request target?", ["http://cp-internal:8080", "http://cp-internal:80 because all containers use 80", "http://127.0.0.1:8082 inside the client", "No communication is possible without -p"], 0, "Container-to-container traffic uses the backend's application listener port. -p is for publishing a host-side entry point, not a prerequisite for traffic within this network.", S.network),
      q("scope", "The name cp-internal resolves from a cp-net client but not from a default bridge client. What is the likely explanation?", ["Every failed DNS query means Docker is stopped", "The image tag must be renamed", "A named volume has expired", "The service name belongs to the user-defined network's DNS scope"], 3, "A network-scoped name is not automatically a globally resolvable host or DNS record. Compare network memberships before changing application code.", S.network),
    ], sources: refs(["User-defined bridge and DNS", S.network], ["Runtime network selection", S.run]),
  },
  {
    id: "docker-compose", title: "Build a two-service Compose project", assignment: "Docker Foundations · 6 / 6 · practical capstone", lessonId: "docker-compose", minutes: "45–60", goal: "Bring up your page and an nginx gateway together, diagnose dependencies and safely tear down only this project.", prerequisites: [safe, "Complete image and networking lessons. Work in certpath-docker-lab with Dockerfile and index.html from stage 3. Host port 8082 must be available. Use the current docker compose command, not the legacy docker-compose binary."],
    steps: [
      { title: "Define the application stack", instruction: "Next to Dockerfile and index.html, create compose.yaml with this exact content. app is built locally and has no published host port; gateway is the only browser entry point. The project name scopes this exercise's resources.", command: dockerCompose, explain: "Compose describes services and their relationships in one file. Both services join its project network and gateway can resolve the app service name." },
      { title: "Create the gateway configuration", instruction: "Create default.conf in the same folder with this content. This file is mounted read-only over nginx's default server configuration. Verify that it is a file, not a directory, before starting the stack.", command: dockerNginx, explain: "The gateway receives browser traffic on port 80 and proxies it to app:8080. That target uses Compose service DNS and the backend's actual listener port." },
      { title: "Validate, build and observe", instruction: "Run from the lab folder. Open http://127.0.0.1:8082. Capture both services and recent logs. depends_on starts app before gateway, but this simple form does not wait for application readiness; retry a brief startup failure and investigate persistent errors.", command: "docker compose config\ndocker compose up -d --build\ndocker compose ps\ndocker compose logs --tail 20", explain: "Syntax validation, image building, process startup and application readiness are separate checkpoints. A running status does not prove the HTTP request succeeds." },
      { title: "Test failure and recovery, then tear down", instruction: "Stop only app and refresh the gateway: a proxy error is expected. Start app and verify the page returns. Save evidence, then run compose down from this folder. Do not add -v to projects with data you intend to retain. No database is included in this small capstone.", command: "docker compose stop app\ndocker compose start app\ndocker compose down", explain: "A backend failure can leave the gateway running but unable to serve a successful request. down removes this project's containers and networks; explicit volume deletion is a separate destructive choice." },
    ],
    tests: [test("stack", "Two services serve the custom page", "Capture docker compose config, ps and the page at 127.0.0.1:8082.", "app and gateway run and the custom page is returned through the gateway."), test("recovery", "Controlled outage and recovery", "Record browser results and logs while app is stopped and after app starts.", "Gateway returns a proxy error during the outage; the page returns after backend recovery."), test("down", "Project-only cleanup", "Run compose down from the lab folder and inspect this project's containers and networks.", "The project runtime is removed without global pruning or unrelated changes.")],
    questions: [
      q("compose-dns", "In the Compose gateway configuration, which target reaches the app service?", ["http://app:8080", "http://localhost:8080", "http://127.0.0.1:8082", "http://Dockerfile:80"], 0, "The gateway and app share the Compose project network. The app service name resolves there and its Python server listens on 8080, not on the gateway's port 80.", S.compose),
      q("readiness", "The simple depends_on list includes app. Does that guarantee the app can already answer HTTP when gateway starts?", ["Yes, it tests every URL", "Yes, it waits for any database automatically", "No; startup ordering alone is not an application-readiness check", "No, because Compose has no service ordering"], 2, "The simple dependency sets startup order but does not perform the app's readiness check. A healthcheck and an appropriate dependency condition are needed when readiness must gate startup.", S.readiness),
      q("compose-rebuild", "You changed source files included by COPY. Which command builds the updated app image and brings up the Compose stack?", ["docker compose logs", "docker compose up -d --build", "docker volume prune", "docker compose version"], 1, "The --build option asks Compose to build the app image before starting services. Logs and version commands do not build changed sources.", S.compose),
      q("down-volumes", "For a later project with a named database volume, what is the risk of adding -v to docker compose down?", ["It only changes log verbosity", "It automatically encrypts the database", "It guarantees a cloud backup", "It can remove project volumes and destroy stored data"], 3, "The -v option requests volume removal, unlike an ordinary project teardown that retains named volumes. Check ownership, retention and backups before deleting data.", S.down),
    ], sources: refs(["Compose quickstart", S.compose], ["Startup order versus readiness", S.readiness], ["Project teardown and volume removal", S.down]),
  },
];
