const source = "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-802";
const questionBank = [
  { id:"ad-ds-redundancy", domain:"Active Directory Domain Services", text:"A domain controller must remain available if a single on-premises host fails. Which design best addresses this requirement?", options:["Deploy a second domain controller and ensure DNS replication", "Install Remote Desktop Services on the same host", "Disable the SYSVOL share", "Move the PDC emulator to a member server"], correct:0, source:"https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview", rationale:{fa:"استقرار domain controller دوم با replication و DNS افزونگی هویت را فراهم می‌کند.",en:"A second domain controller with replication and DNS availability provides redundancy for the identity service.",de:"Ein zweiter Domänencontroller mit Replikation und verfügbarem DNS stellt Redundanz für den Identitätsdienst bereit."}},
  { id:"hyperv-internal-switch", domain:"Windows Server virtualization", text:"You need to isolate a test VM network from the production LAN while allowing controlled outbound access through a host. Which Hyper-V switch type is the correct starting point?", options:["External switch", "Internal switch", "Private switch", "Fibre Channel switch"], correct:1, source:"https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-hyper-v-networking-in-windows-server", rationale:{fa:"Internal switch ارتباط بین VM و host را فراهم می‌کند و شبکهٔ مستقیم VMها به production را جدا نگه می‌دارد.",en:"An internal switch connects VMs to the host without directly attaching them to the production network.",de:"Ein interner Switch verbindet VMs mit dem Host, ohne sie direkt an das Produktionsnetz anzuschließen."}},
  { id:"dfs-namespace", domain:"Storage and file services", text:"Users must access a file share through a namespace while the underlying server can change. Which Windows Server technology provides this abstraction?", options:["DFS Namespace", "Windows Deployment Services", "Hyper-V Replica", "Task Scheduler"], correct:0, source:"https://learn.microsoft.com/en-us/windows-server/storage/dfs-namespaces/dfs-overview", rationale:{fa:"DFS Namespace یک مسیر منطقی مستقل از سرور فیزیکی برای shareها ایجاد می‌کند.",en:"DFS Namespace presents a logical path for shares that can remain stable when the underlying server changes.",de:"DFS Namespaces stellt einen stabilen logischen Pfad bereit, auch wenn sich der zugrunde liegende Server ändert."}},
  { id:"azure-backup-recovery", domain:"Disaster recovery", text:"A workload must be restored after accidental deletion, with point-in-time recovery and policy-based retention. Which service should you evaluate first?", options:["Azure Backup", "Windows Firewall", "Azure Bastion", "DNS Server"], correct:0, source:"https://learn.microsoft.com/en-us/azure/backup/backup-overview", rationale:{fa:"Azure Backup برای backup، retention و point-in-time recovery طراحی شده است.",en:"Azure Backup is designed for policy-based retention and point-in-time recovery after data loss.",de:"Azure Backup unterstützt richtlinienbasierte Aufbewahrung und Point-in-Time-Wiederherstellung nach Datenverlust."}},
  { id:"arc-management", domain:"Hybrid administration", text:"You need to manage an on-premises Windows Server from Azure without exposing a public RDP endpoint. Which approach best matches the requirement?", options:["Azure Arc-enabled servers with secure management tooling", "Open TCP 3389 to the internet", "Disable Windows Update", "Use a local USB console only"], correct:0, source:"https://learn.microsoft.com/en-us/azure/azure-arc/servers/overview", rationale:{fa:"Azure Arc سرور on-premises را به Azure متصل می‌کند تا مدیریت و policy بدون public RDP انجام شود.",en:"Azure Arc-enabled servers support Azure-based management of on-premises machines without requiring a public RDP endpoint.",de:"Azure Arc-fähige Server ermöglichen Azure-Verwaltung lokaler Maschinen ohne öffentliches RDP-Endpunkt."}},
  { id:"ipsec-connection-rule", domain:"Secure Windows Server networking", text:"You need to require IPsec authentication between members of the finance domain while allowing standard traffic for all other devices. Which Windows Defender Firewall with Advanced Security rule type should you configure?", options:["Inbound rule", "Outbound rule", "Connection security rule", "Program rule"], correct:2, source, rationale:{fa:"Connection security rules برای الزام احراز هویت و محافظت IPsec بین endpointها استفاده می‌شوند. این سؤال تألیفی است و به هدف رسمی امنیت شبکه در AZ-802 متصل است.",en:"Connection security rules define authentication and protection requirements such as IPsec between endpoints. This original question maps to the AZ-802 network security objective.",de:"Verbindungssicherheitsregeln definieren Authentifizierungs- und Schutzanforderungen wie IPsec zwischen Endpunkten."}},
  { id:"cloud-witness", domain:"High availability", text:"A two-node failover cluster runs across two sites. You need a resilient quorum vote hosted outside both sites. Which witness should you configure?", options:["Disk witness", "File share witness in Site A", "Cloud witness", "USB witness"], correct:2, source, rationale:{fa:"Cloud witness یک رأی quorum خارج از هر دو سایت فراهم می‌کند و برای سناریوهای چندسایتی مناسب است.",en:"A cloud witness provides a quorum vote outside both sites, making it appropriate for a multi-site cluster.",de:"Ein Cloud Witness stellt eine Quorumstimme außerhalb beider Standorte bereit und eignet sich für Multi-Site-Cluster."}},
  { id:"azure-monitor-agent", domain:"Monitoring & troubleshooting", text:"Which tool should you use to collect Windows Server event data and correlate it with alerts in a cloud-based monitoring workspace?", options:["Windows Memory Diagnostic", "Azure Monitor Agent", "Disk Cleanup", "Local Users and Groups"], correct:1, source, rationale:{fa:"Azure Monitor Agent داده‌های مانیتورینگ را جمع‌آوری و به Azure Monitor ارسال می‌کند.",en:"Azure Monitor Agent collects monitoring data from Windows Server and sends it to Azure Monitor.",de:"Der Azure Monitor Agent sammelt Überwachungsdaten von Windows Server und sendet sie an Azure Monitor."}},
];
const questionSkill: Record<string, string> = { "ad-ds-redundancy":"ha", "hyperv-internal-switch":"security", "dfs-namespace":"migration", "azure-backup-recovery":"dr", "arc-management":"migration", "ipsec-connection-rule":"security", "cloud-witness":"ha", "azure-monitor-agent":"monitoring" };
export const questions = questionBank.map((question) => ({ ...question, skillId: questionSkill[question.id] ?? "security", reviewStatus: "approved" as const, isOriginal: true }));
