/** Original English teaching adaptation of the supplied Windows Server lab assignments.
 * Classroom files, student work, credentials and personal class metadata are not published.
 * Commands are instructions for disposable learner-owned VMs, never for the host or production.
 */
export type LabStep = { title: string; instruction: string; command?: string; explain: string };
export type LabTest = { id: string; title: string; procedure: string; expected: string; points: number };
export type LabQuestion = { id: string; text: string; options: string[]; correct: number; explain: string; source: string };
export type ServerLab = { id: string; title: string; assignment: string; lessonId: string; minutes: string; goal: string; prerequisites: string[]; steps: LabStep[]; tests: LabTest[]; questions: LabQuestion[]; sources: { title: string; url: string }[] };

export const serverLabSources = {
  switch: "https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/create-a-virtual-switch-for-hyper-v-virtual-machines",
  ad: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/install-active-directory-domain-services--level-100-",
  groups: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-groups",
  user: "https://learn.microsoft.com/en-us/powershell/module/activedirectory/new-aduser?view=windowsserver2022-ps",
  acl: "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/icacls",
  smb: "https://learn.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2025-ps",
  gpo: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/group-policy/group-policy-modeling-results",
  gpresult: "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/gpresult",
  firewall: "https://learn.microsoft.com/en-us/windows/security/operating-system-security/network-security/windows-firewall/",
  defender: "https://learn.microsoft.com/en-us/defender-endpoint/validate-antimalware",
  audit: "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/advanced-audit-policy-configuration",
};
const S = serverLabSources;
const question = (id: string, text: string, options: string[], correct: number, explain: string, source: string): LabQuestion => ({ id, text, options, correct, explain, source });
const test = (id: string, title: string, procedure: string, expected: string, points = 1): LabTest => ({ id, title, procedure, expected, points });

/** Fictional training identities from the exercise, not actual Classroom members. */
export const labEmployees = [
  { login: "petra.sommer", department: "Management", group: "GG_Geschaeftsfuehrung", ou: "Benutzer" },
  { login: "jonas.weber", department: "Accounting", group: "GG_Buchhaltung", ou: "Benutzer" },
  { login: "lena.koch", department: "Accounting", group: "GG_Buchhaltung", ou: "Benutzer" },
  { login: "murat.yilmaz", department: "Sales", group: "GG_Verkauf", ou: "Benutzer" },
  { login: "sarah.becker", department: "Sales", group: "GG_Verkauf", ou: "Benutzer" },
  { login: "tom.fischer", department: "Workshop", group: "GG_Werkstatt", ou: "Benutzer" },
  { login: "ali.hassan", department: "Workshop", group: "GG_Werkstatt", ou: "Benutzer" },
  { login: "nina.wolf", department: "Intern", group: "GG_Praktikanten", ou: "Benutzer/Praktikanten" },
];
export const labPermissionMatrix = [
  { folder: "Allgemein", rights: ["Modify", "Modify", "Modify", "Modify", "Read"] },
  { folder: "Allgemein/Vorlagen", rights: ["Modify", "Read", "Read", "Read", "Read"] },
  { folder: "Verkauf", rights: ["Read", "No access", "Modify", "Read", "No access"] },
  { folder: "Werkstatt", rights: ["Read", "No access", "Read", "Modify", "Read"] },
  { folder: "Buchhaltung", rights: ["Modify", "Modify", "No access", "No access", "No access"] },
  { folder: "Buchhaltung/Lohn", rights: ["Modify", "No access", "No access", "No access", "No access"] },
];
export const serverLabs: ServerLab[] = [
  {
    id: "ws-lab-foundation", title: "Build your independent server lab", assignment: "Foundation for the Hyper-V and server exercises", lessonId: "virtual-machines", minutes: "60–90", goal: "Create an isolated domain controller and member server that you own and can safely test.",
    prerequisites: ["Windows Server evaluation/licensed media and a virtualization-capable host with sufficient RAM and disk space.", "Hyper-V on a supported Windows edition, or the existing VMware lab. Do not mix both networking instructions.", "Use VM console access. Do not change the physical host network, production DNS, or a real organizational domain."],
    steps: [
      { title: "Choose an isolated network", instruction: "In Hyper-V Manager, create an Internal switch named Kettenblatt-Lab. This connects the host and VMs, not the physical LAN. For an existing VMware lab, retain the instructor-provided VMnet configuration and verify the actual subnet first.", command: "New-VMSwitch -Name Kettenblatt-Lab -SwitchType Internal", explain: "Internal supports the host-as-test-client role. A Private switch does not connect the host. Neither supplies DHCP or internet access by itself." },
      { title: "Install two separate VMs", instruction: "Create Generation 2 Windows Server VMs with Desktop Experience: SERVER-DC and SERVER-APP01. Attach both to the same lab switch. Install from official media and choose unique local administrator passwords. Do not clone an already-promoted domain controller with ordinary Sysprep.", explain: "Two machines separate identity/DNS from file and application services. Keep enough memory available to the physical host; a checkpoint is not a backup." },
      { title: "Configure the lab addresses", instruction: "Use SERVER-DC 192.168.100.10/24 and SERVER-APP01 192.168.100.100/24 only if this subnet does not conflict with your existing network. On Hyper-V, set only the lab vEthernet host adapter to 192.168.100.1/24. Leave the gateway blank for the isolated Internal network. Point both VM DNS clients to SERVER-DC; never use public DNS as the member server's AD DNS server.", command: "Get-NetIPConfiguration\nGet-DnsClientServerAddress -AddressFamily IPv4", explain: "Domain discovery depends on AD DNS records. Internet access is not needed for domain join; temporarily obtain updates separately without exposing this lab." },
      { title: "Create the training domain", instruction: "On SERVER-DC, rename and reboot first. In Server Manager, add AD DS with management tools. Promote it as the first DC of kurs.intern, install DNS and set a unique DSRM password. Allow the required reboot. This name is for reproducing the existing isolated exercise only, not a production naming recommendation.", command: "Install-WindowsFeature AD-Domain-Services -IncludeManagementTools\nInstall-ADDSForest -DomainName kurs.intern -DomainNetbiosName KURS -InstallDns", explain: "Installing the role does not itself create a domain. Promotion creates AD, SYSVOL and DNS; the command prompts securely for DSRM rather than embedding a password." },
      { title: "Join and establish a baseline", instruction: "On SERVER-APP01 set DNS to 192.168.100.10, join kurs.intern with a lab administrator and reboot. On the DC create a Server OU and move only the APP01 computer into it, never the DC. Record names, addresses, OS versions and switch type. Create a named pre-exercise checkpoint/snapshot of both disposable VMs.", command: "Add-Computer -DomainName kurs.intern -Credential (Get-Credential) -Restart", explain: "User GPOs and computer GPOs follow different OU locations. Keep the DC in Domain Controllers so its baseline policies remain intact." },
    ],
    tests: [test("dns", "AD DNS lookup", "On APP01 run Resolve-DnsName -Type SRV _ldap._tcp.dc._msdcs.kurs.intern.", "The SRV records identify SERVER-DC."), test("join", "Domain trust", "On APP01 run Test-ComputerSecureChannel and Get-NetConnectionProfile.", "Secure channel is True; the lab NIC is DomainAuthenticated."), test("topology", "Isolation and recovery baseline", "Inspect both VM NICs, addresses and checkpoint/snapshot lists. Record the results, not passwords.", "Both VMs share the isolated lab network and have recognizable baseline snapshots.")],
    questions: [question("foundation-dns", "APP01 can reach the DC by IP but cannot join kurs.intern. It uses a public DNS resolver. What should you correct first?", ["Disable the firewall", "Use the domain controller as APP01's DNS resolver", "Make APP01 a domain controller", "Give every user local administrator rights"], 1, "A reachable IP address is not enough: domain join uses AD DNS discovery. Correct the DNS client first, then verify the SRV lookup before joining.", S.ad), question("foundation-switch", "The host must test the VMs without bridging the lab to the physical LAN. Which Hyper-V switch fits?", ["External", "Private", "Internal", "An empty VM NIC configuration"], 2, "Internal connects VMs to each other and the host. Private excludes the host; External connects to the physical network.", S.switch)], sources: [{ title: "Hyper-V virtual switches", url: S.switch }, { title: "Install AD DS", url: S.ad }],
  },
  {
    id: "ws-lab-identities", title: "Create eight users and the AGDLP group model", assignment: "Radhaus Kettenblatt · Day 1 · tasks 1–3", lessonId: "ad-ds", minutes: "40–60", goal: "Organize fictional staff accounts and assign departmental membership without privileged shortcuts.", prerequisites: ["Complete the independent lab foundation; SERVER-DC and SERVER-APP01 are running.", "Use only fictional lab accounts. Choose unique lab passwords; the source exercise's shared demonstration password is deliberately not published or recommended here."],
    steps: [
      { title: "Create the OU tree", instruction: "In Active Directory Users and Computers on SERVER-DC create Kettenblatt under kurs.intern, then Benutzer and Gruppen beneath it, and Praktikanten under Benutzer. Keep accidental deletion protection enabled.", command: "Get-ADOrganizationalUnit -Filter * -SearchBase 'OU=Kettenblatt,DC=kurs,DC=intern' | Select-Object Name,DistinguishedName", explain: "An OU is a policy and delegation boundary; it is not a file-system folder or a security group." },
      { title: "Create the eight training accounts", instruction: "Use the roster below. Put nina.wolf in Praktikanten and all other staff in Benutzer. Set department values, enable each test account and securely choose a password. If immediate first-logon password change is disabled to reproduce the classroom test, keep that exception in this disposable lab only.", command: "Get-ADUser -Filter * -SearchBase 'OU=Benutzer,OU=Kettenblatt,DC=kurs,DC=intern' -Properties Department | Select-Object SamAccountName,Enabled,Department", explain: "Ordinary staff must not join Domain Admins or local Administrators just to make a file-access test succeed." },
      { title: "Create departmental global security groups", instruction: "Create the five GG_ groups from the roster in Gruppen, scope Global and type Security. Add each account to its matching group. nina.wolf belongs only to GG_Praktikanten, not GG_Werkstatt.", command: "Get-ADGroupMember GG_Praktikanten\nGet-ADGroupMember GG_Buchhaltung", explain: "Department groups describe who a person is. The next lab nests them in domain-local resource-permission groups: Accounts → Global → Domain Local → Permissions." },
      { title: "Verify ordinary sign-in", instruction: "Using the VM console on APP01, sign in as KURS\\lena.koch, inspect whoami /groups and sign out fully. Do not grant ordinary staff logon to the domain controller or enable RDP just for this test.", command: "whoami\nwhoami /groups", explain: "A new sign-in refreshes the user's token after a membership change. Folder access and local/DC/RDP logon rights are separate checks." },
    ],
    tests: [test("roster", "Eight identities", "Count users in Benutzer recursively and inspect each OU path.", "Eight roster users exist; only nina.wolf is in Praktikanten."), test("membership", "Correct group membership", "Inspect the five global security groups and all eight memberships.", "Membership matches the roster; the intern is not in the workshop group."), test("token", "Standard-user token", "Log on to APP01 as lena.koch and inspect whoami /groups.", "The accounting group appears without granting administrator membership.")],
    questions: [question("identity-scope", "Which group should collect employees of the same department before nesting into a resource group?", ["A global security group", "A distribution group", "Domain Admins", "A local administrator account"], 0, "A global security group is suitable for same-domain department membership. A distribution group cannot be used as a security principal in a DACL; privileged groups are unrelated to this need.", S.groups), question("identity-token", "tom.fischer was added to a resource group but his existing desktop session still has the old rights. What is the appropriate next test?", ["Delete the folder", "Disable Kerberos", "Grant Everyone Full Control", "Sign out, sign back in, and verify the new token"], 3, "Group memberships are represented in a logon token. A fresh sign-in and SMB connection are necessary before evaluating the changed membership; broadening the ACL conceals the issue.", S.groups)], sources: [{ title: "AD security group scopes", url: S.groups }, { title: "Creating AD users", url: S.user }],
  },
  {
    id: "ws-lab-permissions", title: "Build file services and prove the permission matrix", assignment: "Radhaus Kettenblatt · Day 1 · tasks 4–6", lessonId: "storage", minutes: "60–90", goal: "Implement least-privilege SMB and NTFS access, including inheritance exceptions and negative tests.", prerequisites: ["Complete the identities lab and keep an administrator console available on APP01.", "Create test files only in C:\\Firma on the disposable member server. Do not edit OS or host-drive permissions."],
    steps: [
      { title: "Create the company folder tree", instruction: "On APP01 create C:\\Firma with Allgemein (and Vorlagen), Verkauf, Werkstatt, Buchhaltung (and Lohn). Put a harmless text document in each folder. Share the root as Firma, remove Everyone from the share ACL and grant Authenticated Users Change; preserve administrator access.", command: "Get-SmbShare -Name Firma\nGet-SmbShareAccess -Name Firma", explain: "The share ACL is the first gate for network access. NTFS provides the finer per-folder restrictions; both gates must allow an operation." },
      { title: "Build domain-local permission groups", instruction: "Create a DL_<folder>_R and/or DL_<folder>_RW security group for every required Read or Modify combination in the matrix. Nest the corresponding GG_ groups, not individual users. Example: DL_Verkauf_RW contains GG_Verkauf; DL_Verkauf_R contains GG_Geschaeftsfuehrung and GG_Werkstatt. Create DL_Firma_Anzeigen containing all five GG_ groups.", explain: "Accounts → GG department → DL resource/right → folder ACL keeps changes auditable and prevents scattered per-user ACEs." },
      { title: "Protect the root before child ACLs", instruction: "On C:\\Firma open Security → Advanced. Disable inheritance by converting existing inherited ACEs, not removing all permissions. Keep SYSTEM and Administrators, remove unrelated broad grants, then give DL_Firma_Anzeigen List folder contents for This folder only. Never remove your administrator recovery access.", command: "icacls C:\\Firma", explain: "Root listing lets a user see folder names without granting access to their contents. Avoid Explorer's Continue shortcut adding unexpected per-user permissions." },
      { title: "Apply the matrix, including exceptions", instruction: "On each folder add the relevant DL groups as Read & execute or Modify. On Vorlagen and Lohn disable inheritance, convert ACEs, then remove the inherited department Modify grants that violate the matrix. Preserve SYSTEM and Administrators and apply only the intended resource groups.", command: "icacls C:\\Firma\\Allgemein\\Vorlagen\nicacls C:\\Firma\\Buchhaltung\\Lohn", explain: "An explicit Read allow does not cancel an inherited Modify allow. Remove the unwanted inherited grant at the exception folder rather than introducing a broad Deny that can also affect management." },
      { title: "Test through the share as real users", instruction: "Use fresh non-admin sign-ins or isolated SMB sessions for each test. Record account, UNC path, operation, expected outcome, actual outcome and time. Close the previous connection before changing credentials to avoid error 1219. Effective Access helps inspect NTFS, but does not replace a real SMB test of both ACL layers.", command: "net use X: \\\\SERVER-APP01\\Firma /user:KURS\\lena.koch\n# Enter the password at the prompt; do not put it in notes.\nnet use X: /delete", explain: "Successful and denied tests are both evidence. An administrator's successful access says nothing about a staff member's access." },
    ],
    tests: [test("account-write", "Accounting can write", "As lena.koch create, read and delete your own test file in Buchhaltung over SMB.", "All three operations succeed."), test("salary-denied", "Salary exception", "As lena.koch try opening Buchhaltung/Lohn; as petra.sommer create a test file there.", "Accounting is denied; management can modify."), test("templates", "Read-only templates", "As murat.yilmaz read a template, then try creating or editing a file in Vorlagen.", "Read succeeds; write is denied."), test("intern", "Intern boundary", "As nina.wolf read Allgemein and Werkstatt, then try opening Verkauf and writing Allgemein.", "Allowed reads succeed; both prohibited operations are denied."), test("all-matrix", "All 30 permission cells", "Check all five group roles across all six folders using fresh staff tokens. Attach a result table.", "Every matrix cell agrees with the expected rights; No access never means only hidden by the UI.", 2)],
    questions: [question("acl-inheritance", "Sales inherits Modify on Allgemein/Vorlagen but should only read templates. Adding an explicit Read allow did not prevent edits. Why?", ["Read always denies edits", "Share permissions override every NTFS permission", "The inherited Modify allow still applies", "The folder must be made public"], 2, "Allow permissions are cumulative here. At the exception folder, stop inheritance, retain recovery principals and remove the inappropriate inherited Modify grant, then apply the intended Read group.", S.acl), question("acl-two-gates", "SMB share permissions allow Change but a user's NTFS permission is Read. What can the user do over the share?", ["Always modify files", "Read within the allowed NTFS scope", "Change ownership", "Bypass NTFS with the UNC path"], 1, "Network file operations must satisfy both share and NTFS access checks. Share Change does not grant write when NTFS only allows Read.", S.smb), question("acl-listing", "lena.koch can see the Verkauf folder name at the root but cannot open it. Is this necessarily a misconfiguration?", ["Yes, visible always means readable", "Yes, grant Full Control to fix it", "Yes, domain join failed", "No; root listing and child access are different permissions"], 3, "The design explicitly grants root-only listing through DL_Firma_Anzeigen, with no Sales content permission for accounting. Seeing a name is not evidence of being able to read its contents.", S.acl)], sources: [{ title: "SMB share access", url: S.smb }, { title: "NTFS ACL inspection", url: S.acl }, { title: "Group scopes", url: S.groups }],
  },
  {
    id: "ws-lab-policy", title: "Apply user GPOs and separate logon rights", assignment: "Radhaus Kettenblatt · Day 1 · task 7 and extension", lessonId: "ad-ds", minutes: "40–60", goal: "Map the company drive, target the intern OU, and distinguish local sign-in from network file access.", prerequisites: ["Complete identities and permissions. Record existing inherited GPOs before adding more.", "Use APP01's VM console for staff tests, not the DC. Keep an administrator recovery console open."],
    steps: [
      { title: "Inspect policy inheritance", instruction: "In GPMC select Kettenblatt/Benutzer → Group Policy Inheritance. Record existing links, source OUs and precedence. Do not edit Default Domain Controllers Policy or move the DC.", explain: "An effective policy can come from a parent even when no GPO is linked directly to a child OU." },
      { title: "Map F: with a user preference", instruction: "Create and link Benutzer - Laufwerk F Firma to Benutzer. Edit User Configuration → Preferences → Windows Settings → Drive Maps. Create a mapped drive with Update, path \\\\SERVER-APP01\\Firma, reconnect enabled, label Firma and letter F:.", explain: "The preference follows the user's OU, not the member-server computer OU. A drive mapping does not grant any new NTFS permission." },
      { title: "Target only interns", instruction: "Link Benutzer - Systemsteuerung gesperrt to Praktikanten. Enable User Configuration → Policies → Administrative Templates → Control Panel → Prohibit access to Control Panel and PC settings. Refresh policy and sign in separately as nina.wolf and lena.koch.", command: "gpupdate /force\ngpresult /r\ngpresult /h \"$env:TEMP\\lab-policy.html\"", explain: "Nina inherits the drive mapping from Benutzer and receives the extra restriction from Praktikanten. Lena does not receive the child-OU restriction." },
      { title: "Optional: deny local sign-in without denying SMB", instruction: "Do this only after Nina's console tests. Link Computer - Praktikanten nicht lokal anmelden to the Server OU containing APP01. Under Computer Configuration → Policies → Windows Settings → Security Settings → Local Policies → User Rights Assignment, define Deny log on locally for GG_Praktikanten only. Never select Everyone, Authenticated Users or Administrators. From the host-as-client test Nina's allowed SMB reads with explicit credentials.", command: "net use X: \\\\192.168.100.100\\Firma /user:KURS\\nina.wolf\nnet use X: /delete", explain: "Interactive logon and network logon are different rights. Do not enable unsafe DC sign-in or remote desktop access to make this exercise work; undo only this lab GPO if you need to repeat Nina's console test." },
    ],
    tests: [test("drive", "Inherited drive mapping", "Sign in as Lena and Nina before the optional local-logon denial and inspect F: and gpresult.", "Both receive F:, and Lena still cannot access Lohn."), test("control-panel", "Child-OU restriction", "Compare Control Panel access in Lena's and Nina's fresh sessions.", "Nina is restricted; Lena is not."), test("network-vs-console", "Local logon versus network access", "If you perform the optional task, test Nina's console logon and allowed SMB access from the host. Otherwise document the expected distinction.", "Console logon is denied by that user right, while allowed SMB reads remain subject to the share and NTFS rules.")],
    questions: [question("gpo-inherit", "Nina's account is in Benutzer/Praktikanten. Why can she receive F: from a GPO linked to Benutzer?", ["Normal parent-OU inheritance includes her child OU", "A mapped drive ignores every GPO link", "She must be Domain Admin", "Every GPO automatically applies to every domain user"], 0, "Without blocking/enforcing/filtering exceptions, user policy linked at a parent OU is inherited by users in nested OUs. The child restriction adds to that path; it does not remove the parent's drive preference.", S.gpo), question("gpo-proof", "Which evidence shows the GPOs applied to the current lab user instead of merely showing configured links?", ["The folder name", "The DC desktop background", "gpresult output from the relevant user's session", "An administrator's group list"], 2, "gpresult reports resultant policy for the user and computer. Capture it in the right session; configured links alone do not prove successful client application.", S.gpresult)], sources: [{ title: "Group Policy results", url: S.gpo }, { title: "gpresult", url: S.gpresult }],
  },
  {
    id: "ws-lab-firewall", title: "Test application ports and firewall policy", assignment: "Radhaus Kettenblatt · Day 2 · tasks 0–6", lessonId: "network-security", minutes: "60–90", goal: "Validate the four-port access plan from two separate clients, repair a profile mismatch and correlate blocked traffic.", prerequisites: ["Foundation completed; keep DC running and APP01 DomainAuthenticated.", "Use the instructor-provided dienst.ps1 and start-dienste.ps1 only after reviewing them, or your own disposable test listeners on 15001–15004. No real business services or internet exposure.", "Host 192.168.100.1 represents the guest client; DC 192.168.100.10 represents accounting only in this isolated exercise."],
    steps: [
      { title: "Confirm the listeners independently", instruction: "Create a pre-firewall snapshot. Start the reviewed demo services inside APP01 only. Confirm TCP listeners for website 15001, payroll 15002, booking 15003 and database 15004. Keep firewall enabled, note its effective defaults and inspect any existing allow rules before testing.", command: "Get-NetTCPConnection -State Listen | Where-Object LocalPort -in 15001,15002,15003,15004\nGet-NetConnectionProfile\nGet-NetFirewallProfile -PolicyStore ActiveStore", explain: "A timeout can also mean no listener, a routing error or DNS failure. Establish each layer before blaming the firewall. Localhost is only a listener baseline, not proof of remote firewall access." },
      { title: "Implement the access plan", instruction: "On APP01 in wf.msc create Domain-profile inbound TCP rules: payroll 15002 allows only remote IP 192.168.100.10; booking 15003 allows only the actual host lab IP. Inspect and narrow overlapping allow rules; add a scoped block for the DC on 15003 if needed by the exercise. No remote client should reach database 15004. Avoid an allow-all plus block-all pair: an explicit matching block wins.", command: "New-NetFirewallRule -DisplayName 'Radhaus - Payroll' -Direction Inbound -Action Allow -Protocol TCP -LocalPort 15002 -RemoteAddress 192.168.100.10 -Profile Domain", explain: "RemoteAddress identifies the caller; LocalAddress is APP01. IP restrictions express this lab's network roles, not authentication of the employee who uses that IP." },
      { title: "Repair the website ticket", instruction: "Reproduce or inspect the exercise's enabled Public-only rule for website 15001. APP01 is DomainAuthenticated, so that rule is inactive there. Edit the existing rule to the intended Domain profile; do not create a duplicate. Verify website access from DC and host.", explain: "The destination server's active network profile determines which inbound rule applies. The host's own Public profile does not make APP01 use a Public rule." },
      { title: "Predict and run all eight remote checks", instruction: "Write your expected results before testing. Test each of the four ports from DC and host using fresh TCP connections. Use the hostname from DC and the lab IP from the non-domain host. Close old browser or PowerShell connections after changing policy.", command: "Test-NetConnection 192.168.100.100 -Port 15002\n# Repeat on each client for all four ports.\nInvoke-RestMethod 'http://192.168.100.100:15002/?text=Lab-test' -TimeoutSec 5", explain: "Existing stateful connections can outlive a rule change. A negative test must target a verified listener from a different machine." },
      { title: "Centralize baseline, ping and logging", instruction: "In Server-OU computer GPOs enforce firewall On, inbound Block default and outbound Allow default for all three profiles. Retain local rule merging for the locally-authored exercise rules. Add Domain ICMPv4 Echo Request allow scoped to 192.168.100.0/24. Enable failure auditing for Filtering Platform Connection, apply policy and find time-correlated 5157 entries for the prohibited flows.", command: "gpupdate /force\nGet-NetFirewallProfile -PolicyStore ActiveStore | Select-Object Name,Enabled,DefaultInboundAction\nGet-WinEvent -FilterHashtable @{LogName='Security';Id=5157} -MaxEvents 20", explain: "Server-OU policy does not automatically apply to the DC kept in Domain Controllers. If the assignment requires DC ping as well, use a separate narrowly-scoped approved GPO for Domain Controllers. A blocked-flow record requires the appropriate audit policy; do not disable protection to test enforcement." },
    ],
    tests: [test("web", "Website from both clients", "Use fresh connections from DC and host to TCP 15001.", "Both clients receive the website response."), test("payroll", "Payroll is DC-only", "Test TCP 15002 from DC and host, recording actual source addresses.", "DC succeeds; host is denied."), test("booking", "Booking is host-only", "Test TCP 15003 from DC and host.", "Host succeeds; DC is denied."), test("database", "Database is local-only", "Verify listener locally, then test TCP 15004 from DC and host.", "Local application works; both remote clients are denied."), test("policy-audit", "Effective policy and denied-flow evidence", "Inspect ActiveStore and find Security 5157 matching a prohibited test's source IP, destination port and time.", "Firewall remains enabled for all profiles; the matching blocked-flow record is identified.")],
    questions: [question("firewall-profile", "APP01 uses DomainAuthenticated but its website allow rule applies only to Public. The non-domain host cannot connect. Which profile matters for this inbound rule?", ["Only the host client's profile", "APP01's active profile", "Only the user's AD group", "The browser language"], 1, "An inbound rule's profile is evaluated on the receiving server. APP01's Domain profile does not activate a Public-only allow rule, regardless of the caller's network category.", S.firewall), question("firewall-test", "A request to localhost:15002 succeeds. What does that prove about the DC-only inbound rule?", ["Every remote client is blocked", "Every remote client is allowed", "The rule's RemoteAddress is correct", "Only that the local service responds; test remotely to validate the rule"], 3, "Loopback is not a representative remote inbound path. Validate policy from both authorized and unauthorized remote clients with a known listening service.", S.firewall)], sources: [{ title: "Windows Firewall", url: S.firewall }, { title: "Security auditing", url: S.audit }],
  },
  {
    id: "ws-lab-defender", title: "Verify Defender without real malware", assignment: "Radhaus Kettenblatt · Day 3 · antivirus tasks", lessonId: "network-security", minutes: "30–45", goal: "Observe real-time detection, inspect protection history and finish with protection intact.", prerequisites: ["Use only your disposable APP01 VM with Microsoft Defender Antivirus available.", "Never create the EICAR string on the host, paste it into this site, or attach the test file as evidence. Use screenshots or benign text summaries instead."],
    steps: [
      { title: "Record protection status", instruction: "Take a VM snapshot. In Windows Security → Virus & threat protection → Manage settings, record real-time, cloud-delivered and sample-submission status. Do not change cloud data-sharing preferences just to satisfy this lab.", command: "Get-MpComputerStatus | Select-Object AntivirusEnabled,RealTimeProtectionEnabled,AntivirusSignatureLastUpdated", explain: "Detection state and cloud/sample-sharing settings are different. A disabled or passive antivirus needs investigation; do not report a pass from a missing alert alone." },
      { title: "Use the harmless vendor test inside the VM", instruction: "On APP01 only, open the official Microsoft detection-test reference or the EICAR website. Follow its harmless test-file procedure in C:\\Demo. Real-time protection should block, quarantine or remove the test file. Do not restore it or allow it on the device.", explain: "EICAR is a detection test, not real malware. An editor save error can be a successful protection result; verify the associated event rather than repeatedly retrying blindly." },
      { title: "Inspect history and a custom scan", instruction: "Open Protection history and record threat label, action and timestamp, without reproducing the EICAR bytes. Run a custom scan of C:\\Demo. Keep real-time protection enabled. The classroom's disabled-protection and exclusion variations are optional instructor-supervised disposable-VM experiments, not requirements here.", command: "Start-MpScan -ScanType CustomScan -ScanPath C:\\Demo\nGet-MpThreatDetection", explain: "A scan of a folder already cleaned by real-time protection may find nothing new. That does not invalidate an earlier time-correlated detection." },
      { title: "Finish in a protected state", instruction: "Confirm real-time protection remains on. Remove only temporary exclusions you personally introduced for this exercise; do not erase existing organizational exclusions. Remove/quarantine test detections, close the vendor test page and capture a benign final-status screenshot.", command: "Get-MpPreference | Select-Object ExclusionPath\nGet-MpComputerStatus | Select-Object RealTimeProtectionEnabled", explain: "A lab is not complete if its final state leaves protection disabled or a test exception active. Never run these experiments on a managed production endpoint." },
    ],
    tests: [test("status", "Protected baseline", "Capture Defender state inside APP01 before the test.", "Antivirus and real-time protection are enabled, or a documented blocker prevents claiming completion."), test("detection", "Detection and action", "Create the official harmless test only in the VM and inspect Protection history.", "A time-correlated detection and block/quarantine/removal action are documented."), test("cleanup", "Protected final state", "Inspect real-time state, temporary exclusions and history after cleanup.", "Protection is on and no exercise-created exclusion or allowed test threat remains.")],
    questions: [question("defender-safe-test", "Which material should be used to test antivirus detection in this lab?", ["The official harmless EICAR test inside the disposable VM", "A live ransomware sample", "An unknown executable from a forum", "The lab user's real credentials"], 0, "The vendor-supported harmless test validates detection without using real malware. Keep its bytes and files away from the host and from uploaded evidence.", S.defender), question("defender-final-state", "The test produced a detection, but real-time protection remains off afterward. Is the lab safely finished?", ["Yes, detection once is sufficient", "Yes, if the VM has a password", "No; restore protection and remove only the exercise's temporary exceptions", "No; disable the firewall too"], 2, "The final safety state matters as much as the detection. The required completion checklist includes enabled protection and cleanup of lab-specific exceptions; it does not authorize changing production settings.", S.defender)], sources: [{ title: "Microsoft antivirus detection test", url: S.defender }],
  },
  {
    id: "ws-lab-events", title: "Investigate events on the member server and DC", assignment: "Day 25 · Event Viewer exercises", lessonId: "monitoring", minutes: "60–90", goal: "Trigger controlled test events and explain which machine, log, account and time prove each action.", prerequisites: ["Use both disposable servers, an administrator recovery account and a separate test.mueller account.", "Enable the appropriate audit subcategories before each task. Do not assume every Windows version logs every event by default.", "The event exercise uses lockout threshold 3, while the firewall extension uses 5. Record the effective value and choose one lab policy; do not layer conflicting domain policies."],
    steps: [
      { title: "Prepare domain-scoped lockout and auditing", instruction: "Check Get-ADDefaultDomainPasswordPolicy. In the isolated domain, configure the exercise's lockout threshold 3 at domain scope, with documented duration/reset interval and precedence. Enable failed Logon, Credential Validation/Kerberos auditing and account management success auditing as appropriate. Keep recovery admin separate; never test bad passwords against it.", command: "Get-ADDefaultDomainPasswordPolicy | Select-Object LockoutThreshold,LockoutDuration,LockoutObservationWindow\nauditpol /get /category:*", explain: "An OU computer policy is not a substitute for the default domain account policy. Actual failed authentication can produce multiple events, so observe the effective threshold rather than promising an exact fourth-click lockout." },
      { title: "Correlate failed logon, lockout and unlock", instruction: "Use test.mueller for controlled bad-password attempts on APP01. Find 4625 on APP01 and 4771 (Kerberos) or 4776 (NTLM) on the DC. Find 4740 for lockout on the DC, unlock the test account in ADUC, then find 4767. Record account, caller, protocol and timestamp for every finding.", command: "Get-WinEvent -FilterHashtable @{LogName='Security';Id=4625} -MaxEvents 20\n# On SERVER-DC:\nGet-WinEvent -FilterHashtable @{LogName='Security';Id=4771,4776,4740,4767} -MaxEvents 30", explain: "One action has different viewpoints: the member logs the logon attempt, while the DC validates domain credentials and changes domain-account lockout state." },
      { title: "Account and group lifecycle", instruction: "On the DC create the fictional test.mueller account if it is not already present, add it to an appropriate global security test group, reset its lab password, disable and re-enable it, and create a separate GG_Test group. Correlate events 4720, 4728, 4724, 4725, 4722 and 4727. Domain-local membership/creation instead uses 4732/4731.", explain: "Event IDs depend on the operation and group scope. If the account existed before auditing was enabled, create a separate disposable test account rather than claiming a historical event exists." },
      { title: "Network logon and service state", instruction: "Access APP01's Firma share from the other machine and find APP01 Security 4624 with logon type 3. Compare with console type 2 and RDP type 10. If Spooler exists and this lab does not require it for a live print job, restart only that lab service and inspect System 7036. Record an existing System 1074 intentional restart; do not force a crash for evidence.", command: "Get-WinEvent -FilterHashtable @{LogName='Security';Id=4624} -MaxEvents 20\nGet-WinEvent -FilterHashtable @{LogName='System';Id=7036,1074} -MaxEvents 20", explain: "A network logon is logged at the destination resource. Security, System and application operational logs are separate evidence sources. 41/6008 may indicate an unclean restart, not its unique cause." },
      { title: "Firewall and antivirus operational logs", instruction: "Review a narrowly-scoped temporary lab firewall rule in Windows Firewall With Advanced Security/Firewall and find 2004 (creation), 2005 (change) or 2006 (removal). Run a Defender Quick scan on APP01 and locate 1000/1001 in Microsoft-Windows-Windows Defender/Operational. Remove only the temporary rule you created.", command: "Start-MpScan -ScanType QuickScan\nGet-WinEvent -LogName 'Microsoft-Windows-Windows Defender/Operational' -MaxEvents 20", explain: "Not every relevant record lives in Security. Select the exact log and time range instead of treating an absent event in the wrong log as a system failure." },
      { title: "File deletion evidence and optional sensitive tasks", instruction: "Enable Audit File System success and a narrowly-scoped SACL for Delete on a dedicated lab test folder, then create/delete a harmless test file there and correlate 4663/4660. Export needed logs before any optional log-clear experiment; event 1102 records clearing Security. Time changes (4616), forced VM power-off and log clearing from the source exercise are optional, not required; do not do them on the host, a real DC or before preserving evidence.", explain: "Audit policy enables a category; the SACL selects the objects and operations. Both are required for targeted file auditing. Prefer reviewing existing 4616/1102 records to changing time or destroying the investigation trail." },
    ],
    tests: [test("failed", "Two viewpoints of authentication", "Find an APP01 4625 and corresponding DC credential-validation failure in the same time window.", "Account, computer and protocol explain the differing IDs."), test("lockout", "Lockout and unlock", "Use only the disposable account and collect DC 4740 and 4767.", "The effective policy and both state transitions are documented."), test("lifecycle", "Account/group changes", "Collect creation, membership, reset, disable/enable and group-creation records for your test principals.", "Recorded IDs match each operation and actual group scope."), test("logon-service", "Destination and System evidence", "Find APP01 network logon type 3 and a relevant System service/restart entry.", "The account, provider and timestamp match the performed or documented action."), test("operational", "Operational channels", "Inspect firewall changes and Defender scan start/completion in their correct channels.", "The corresponding records are identified without assuming Security contains everything."), test("sacl", "Targeted file audit", "Enable policy plus folder SACL and delete only a harmless disposable test file.", "The object path, account and access operation appear in correlated audit evidence.")],
    questions: [question("event-destination", "A user on the DC opens APP01's SMB share. Where should a successful network logon (type 3) be investigated?", ["Only in the browser history", "Only in the source machine's System log", "Only in DNS Manager", "In APP01's Security log, where the network access arrives"], 3, "The destination machine accepts the network logon. Correlate account, source address and logon type 3 on APP01; credential-validation events on the DC are a separate viewpoint.", S.audit), question("event-sacl", "Audit File System is enabled, but deletion of a test file has no matching targeted audit entry. What configuration should you inspect?", ["Change every NTFS allow to Deny", "The test folder's SACL and audited operation", "The user's desktop theme", "Disable all event logs"], 1, "The audit subcategory permits auditing; a matching SACL defines which objects and access operations are audited. Verify both and correlate records rather than broadening permissions.", S.audit)], sources: [{ title: "Windows security auditing", url: S.audit }, { title: "Group Policy results", url: S.gpo }],
  },
];
