"use client";

import { BilingualText } from "@/app/components/learning-views";
import { trainingStages } from "@/lib/course-data";

type Language = "fa" | "en" | "de";
type Copy = { lang: Language; [key: string]: unknown };
type Stage = typeof trainingStages[number];

const localized = (lang: Language, fa: string, en: string, de: string) => lang === "fa" ? fa : lang === "de" ? de : en;

export function FontSizeControl({ t, scale, onChange }: { t: Copy; scale: number; onChange: (next: number) => void }) {
  const label = localized(t.lang, "اندازهٔ متن", "Text size", "Textgröße");
  return <div className="flex items-center gap-1 rounded-xl border border-white/10 bg-black/15 p-1" aria-label={label}><button type="button" onClick={() => onChange(Math.max(0.85, Number((scale - 0.05).toFixed(2))))} className="grid h-7 w-7 place-items-center rounded-lg text-base text-cyan-100 hover:bg-white/10" aria-label={localized(t.lang, "کوچک‌کردن متن", "Decrease text size", "Text verkleinern")}>−</button><span className="min-w-10 text-center text-xs text-slate-300">{Math.round(scale * 100)}%</span><button type="button" onClick={() => onChange(Math.min(1.3, Number((scale + 0.05).toFixed(2))))} className="grid h-7 w-7 place-items-center rounded-lg text-base text-cyan-100 hover:bg-white/10" aria-label={localized(t.lang, "بزرگ‌کردن متن", "Increase text size", "Text vergrößern")}>+</button></div>;
}

export function TrainingHub({ t, progress, selectedStageId, onSelectStage, onPractice, onOpenLesson }: { t: Copy; progress: Record<string, number>; selectedStageId: string; onSelectStage: (id: string) => void; onPractice: (domain: string) => void; onOpenLesson: (lessonId: string) => void }) {
  const selected = trainingStages.find((stage) => stage.id === selectedStageId) ?? trainingStages[0];
  const stageProgress = (stage: Stage) => progress[stage.id] ?? 0;
  const isUnlocked = (stage: Stage) => stage.stage === 1 || stageProgress(trainingStages[stage.stage - 2]) >= 70;
  return <section className="mx-auto max-w-6xl space-y-5">
    <div className="rounded-3xl border border-cyan-300/20 bg-gradient-to-br from-[#173147] to-[#111a28] p-6 sm:p-8">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-cyan-200">{localized(t.lang, "مسیر مرحله‌ای AZ-802", "AZ-802 staged learning path", "AZ-802-Lernpfad in Stufen")}</p><h2 className="mt-2 text-2xl font-bold">{localized(t.lang, "از درس تا تمرین، مرحله‌به‌مرحله", "Move from lesson to practice, one stage at a time", "Von der Lektion zur Übung, Stufe für Stufe")}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300">{localized(t.lang, "هر مرحله سؤال‌های رسمی این بانک را به درس، تمرین و مرور لایتنر وصل می‌کند.", "Every stage connects its question bank to a lesson, practice set, and Leitner review.", "Jede Stufe verbindet ihren Fragenpool mit Lektion, Übung und Leitner-Wiederholung.")}</p></div><span className="rounded-full bg-white/10 px-3 py-2 text-xs text-cyan-100">{trainingStages.length} {localized(t.lang, "مرحله", "stages", "Stufen")}</span></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{trainingStages.map((stage) => { const value = stageProgress(stage); const unlocked = isUnlocked(stage); return <button type="button" key={stage.id} disabled={!unlocked} onClick={() => onSelectStage(stage.id)} className={`rounded-2xl border p-4 text-start transition ${selected.id === stage.id ? "border-cyan-300/70 bg-cyan-300/10" : "border-white/10 bg-black/10"} ${!unlocked ? "cursor-not-allowed opacity-50" : "hover:border-cyan-300/50"}`}><div className="flex items-center justify-between gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/5 text-sm font-bold text-cyan-200">{stage.stage}</span><span className="text-xs text-slate-400">{unlocked ? `${value}%` : "🔒"}</span></div><p className="mt-3 text-sm font-semibold"><BilingualText lang={t.lang} value={stage.title} /></p><p className="mt-2 text-xs text-slate-500">{stage.questionIds.length} {localized(t.lang, "سؤال", "questions", "Fragen")}</p><div className="mt-3 h-1.5 rounded bg-white/5"><div className="h-full rounded bg-cyan-300" style={{ width: `${value}%` }} /></div></button>; })}</div>
    </div>
    <article className="rounded-3xl border border-white/10 bg-[#111a28] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-cyan-200">{localized(t.lang, `مرحلهٔ ${selected.stage}`, `Stage ${selected.stage}`, `Stufe ${selected.stage}`)}</p><h3 className="mt-2 text-2xl font-bold"><BilingualText lang={t.lang} value={selected.title} /></h3><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300"><BilingualText lang={t.lang} value={selected.body} /></p></div><div className="flex gap-2"><button type="button" onClick={() => onPractice(selected.domain)} className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-bold text-[#071016]">{localized(t.lang, "تمرین مرحله", "Practice stage", "Stufe üben")} →</button>{selected.lessonId && <button type="button" onClick={() => onOpenLesson(selected.lessonId!)} className="rounded-xl border border-white/15 px-4 py-2.5 text-sm font-semibold text-cyan-100">{localized(t.lang, "درس راهنما", "Guide lesson", "Lektionsguide")}</button>}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-black/15 p-4"><p className="text-xs text-slate-500">{localized(t.lang, "هدف مرحله", "Stage objective", "Stufenziel")}</p><p className="mt-2 text-sm leading-6 text-slate-200"><BilingualText lang={t.lang} value={selected.objective} /></p></div><div className="rounded-2xl bg-black/15 p-4"><p className="text-xs text-slate-500">{localized(t.lang, "بانک تمرین", "Practice bank", "Übungspool")}</p><p className="mt-2 text-2xl font-bold text-cyan-200">{selected.questionIds.length}</p><p className="text-xs text-slate-400">{localized(t.lang, "سؤال متصل به این مرحله", "linked questions", "verknüpfte Fragen")}</p></div><div className="rounded-2xl bg-black/15 p-4"><p className="text-xs text-slate-500">{localized(t.lang, "پیشرفت", "Progress", "Fortschritt")}</p><p className="mt-2 text-2xl font-bold text-cyan-200">{stageProgress(selected)}%</p><p className="text-xs text-slate-400">{stageProgress(selected) >= 70 ? localized(t.lang, "مرحله آمادهٔ بعدی است", "Ready for the next stage", "Bereit für die nächste Stufe") : localized(t.lang, "با تمرین کامل کنید", "Practice to unlock the next stage", "Üben, um die nächste Stufe freizuschalten")}</p></div></div></article>
  </section>;
}

export function StageProgressStrip({ t, progress, onOpen }: { t: Copy; progress: Record<string, number>; onOpen: () => void }) {
  return <section className="rounded-3xl border border-white/10 bg-[#111a28] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-cyan-200">{localized(t.lang, "نقشهٔ پیشرفت آموزش", "Learning progress map", "Lernfortschrittskarte")}</p><h2 className="mt-1 text-lg font-bold">{localized(t.lang, "هشت مرحلهٔ AZ-802", "Eight AZ-802 stages", "Acht AZ-802-Stufen")}</h2></div><button type="button" onClick={onOpen} className="rounded-xl border border-cyan-300/30 px-3 py-2 text-xs font-semibold text-cyan-100">{localized(t.lang, "باز کردن مسیر آموزش", "Open learning path", "Lernpfad öffnen")} →</button></div><div className="mt-5 grid grid-cols-4 gap-2 sm:grid-cols-8">{trainingStages.map((stage) => <button type="button" key={stage.id} onClick={onOpen} className="rounded-xl border border-white/10 bg-black/10 p-2 text-start hover:border-cyan-300/50"><span className="text-xs font-bold text-cyan-200">{stage.stage}</span><span className="mt-1 block truncate text-[10px] text-slate-400">{stage.questionIds.length} Q</span><div className="mt-2 h-1 rounded bg-white/5"><div className="h-full rounded bg-cyan-300" style={{ width: `${progress[stage.id] ?? 0}%` }} /></div></button>)}</div></section>;
}
