"use client";

import { useMemo, useState } from "react";
import { copy, questions, skills } from "@/lib/course-data";

type Language = "fa" | "en" | "de";
type View = "home" | "graph" | "quiz" | "labs" | "cards";

export default function Home() {
  const [language, setLanguage] = useState<Language>("fa");
  const [view, setView] = useState<View>("home");
  const [selected, setSelected] = useState(0);
  const [answer, setAnswer] = useState<number | null>(null);
  const [completedLab, setCompletedLab] = useState(false);
  const [cardKnown, setCardKnown] = useState(false);
  const t = copy[language];
  const question = questions[selected];
  const totalProgress = useMemo(() => Math.round(skills.reduce((n, skill) => n + skill.progress, 0) / skills.length), []);
  const navigation: { key: View; icon: string; label: string }[] = [
    { key: "home", icon: "◫", label: t.dashboard }, { key: "graph", icon: "⌘", label: t.graph }, { key: "quiz", icon: "✓", label: t.exams }, { key: "labs", icon: "▣", label: t.labs }, { key: "cards", icon: "▤", label: t.leitner },
  ];
  return <main dir={language === "fa" ? "rtl" : "ltr"} className="min-h-screen bg-[#0b1018] text-[#e8edf5] selection:bg-cyan-300 selection:text-[#071016]"><div className="mx-auto grid min-h-screen max-w-[1600px] grid-cols-1 lg:grid-cols-[250px_minmax(0,1fr)]">
    <aside className="border-b border-white/10 bg-[#0d1420] p-4 lg:border-b-0 lg:border-e"><div className="flex items-center justify-between gap-3 px-2 py-2 lg:block"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-300 text-lg font-black text-[#071016]">W</div><div><p className="font-semibold tracking-tight">WinCraft</p><p className="text-xs text-slate-400">AZ-802 learning space</p></div></div><div className="flex rounded-lg border border-white/10 bg-black/15 p-1 lg:mt-6">{(["fa", "en", "de"] as Language[]).map((lang) => <button key={lang} onClick={() => setLanguage(lang)} className={`rounded-md px-2 py-1 text-xs font-semibold uppercase ${language === lang ? "bg-white/10 text-cyan-200" : "text-slate-500"}`}>{lang}</button>)}</div></div>
      <nav className="mt-4 grid grid-cols-5 gap-1 lg:grid-cols-1">{navigation.map((item) => <button key={item.key} onClick={() => setView(item.key)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-start text-sm transition ${view === item.key ? "bg-cyan-300/10 text-cyan-200" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><span className="text-lg">{item.icon}</span><span className="hidden lg:block">{item.label}</span></button>)}</nav>
      <div className="mt-6 hidden rounded-2xl border border-white/10 bg-gradient-to-br from-[#14243a] to-[#101723] p-4 lg:block"><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">{t.target}</p><p className="mt-2 font-semibold">Windows Server Administrator</p><p className="mt-1 text-sm text-slate-400">AZ-802 · English exam</p><a href="https://learn.microsoft.com/en-us/credentials/certifications/practice-assessments-for-microsoft-certifications" target="_blank" rel="noreferrer" className="mt-4 block text-sm font-semibold text-cyan-200">{t.officialPractice} ↗</a></div>
    </aside>
    <section className="min-w-0 p-4 sm:p-7 lg:p-9"><header className="mb-7 flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-cyan-300">Microsoft Learn aligned · 2026</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">{t.greeting}, Alex.</h1></div><button className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-[#131d2c] text-sm">AL</button></header>
      {view === "home" && <Dashboard t={t} progress={totalProgress} onQuiz={() => setView("quiz")} onLabs={() => setView("labs")} />}{view === "graph" && <SkillGraph t={t} />}{view === "quiz" && <Quiz t={t} question={question} selected={selected} answer={answer} setAnswer={setAnswer} next={() => { setAnswer(null); setSelected((selected + 1) % questions.length); }} />}{view === "labs" && <Labs t={t} completed={completedLab} onComplete={() => setCompletedLab(true)} />}{view === "cards" && <Cards t={t} known={cardKnown} onReview={() => setCardKnown(!cardKnown)} />}
    </section></div></main>;
}

function Dashboard({ t, progress, onQuiz, onLabs }: { t: typeof copy.en; progress: number; onQuiz: () => void; onLabs: () => void }) { return <div className="space-y-6"><section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-white/10 bg-[#111a28] p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-slate-400">{t.overview}</p><h2 className="mt-1 text-xl font-bold">{t.courseTitle}</h2></div><div className="grid h-20 w-20 place-items-center rounded-full border-[7px] border-cyan-300/25 text-lg font-bold text-cyan-200">{progress}%</div></div><div className="mt-7 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-cyan-300" style={{ width: `${progress}%` }} /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat label={t.lessons} value="18 / 42"/><Stat label={t.correct} value="74%"/><Stat label={t.days} value="12"/></div></div><div className="rounded-3xl border border-cyan-300/20 bg-gradient-to-br from-[#173147] to-[#111a28] p-6"><p className="text-sm text-cyan-100">{t.nextLesson}</p><h2 className="mt-2 text-xl font-bold">Secure Windows Server networking</h2><p className="mt-3 text-sm leading-6 text-slate-300">Firewall rules, domain isolation & connection security rules.</p><button onClick={onQuiz} className="mt-6 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-bold text-[#071016]">{t.continue} →</button></div></section><section className="grid gap-4 lg:grid-cols-3"><Action title={t.examTitle} meta="12 questions · 18 min" icon="✓" button={t.startExam} onClick={onQuiz}/><Action title={t.labTitle} meta="Hyper-V · 45–60 min" icon="▣" button={t.openLab} onClick={onLabs}/><Action title={t.reviewTitle} meta="8 cards are due today" icon="↻" button={t.reviewNow} onClick={()=>{}}/></section><section className="rounded-3xl border border-white/10 bg-[#111a28] p-6"><div className="flex justify-between"><div><p className="text-sm text-slate-400">{t.skillMap}</p><h2 className="mt-1 text-lg font-bold">AZ-802 readiness</h2></div><span className="text-sm text-slate-500">updated Jan 2026</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{skills.map(s => <div key={s.id}><div className="mb-2 flex justify-between text-sm"><span>{s.short}</span><span className="text-slate-500">{s.progress}%</span></div><div className="h-1.5 rounded bg-white/5"><div className="h-full rounded bg-cyan-300" style={{width:`${s.progress}%`}}/></div></div>)}</div></section></div>; }
function Stat({ label, value }: {label:string;value:string}) { return <div className="rounded-xl bg-black/15 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function Action({title,meta,icon,button,onClick}:{title:string;meta:string;icon:string;button:string;onClick:()=>void}) { return <article className="rounded-2xl border border-white/10 bg-[#111a28] p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/5 text-cyan-200">{icon}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-500">{meta}</p><button onClick={onClick} className="mt-5 text-sm font-semibold text-cyan-200">{button} →</button></article>; }
function SkillGraph({ t }: { t: typeof copy.en }) { return <section className="rounded-3xl border border-white/10 bg-[#111a28] p-5 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">{t.graph}</p><h2 className="mt-1 text-xl font-bold">{t.learningGraph}</h2></div><span className="rounded-full bg-cyan-300/10 px-3 py-1 text-xs text-cyan-200">{t.clickNode}</span></div><div className="relative mt-8 min-h-[430px] overflow-hidden rounded-2xl border border-white/5 bg-[#0b1018] p-5"><svg viewBox="0 0 900 420" className="absolute inset-0 h-full w-full opacity-50" aria-hidden="true"><path d="M160 215 L340 95 M160 215 L340 300 M340 95 L570 145 M340 300 L570 275 M570 145 L760 215 M570 275 L760 215" fill="none" stroke="#2d6374" strokeWidth="2" strokeDasharray="5 6"/></svg><div className="relative grid min-h-[390px] grid-cols-3 items-center gap-2 text-center">{skills.map((s, i) => <button key={s.id} className={`rounded-2xl border p-3 text-start transition hover:-translate-y-1 ${i===0 ? "border-cyan-300/50 bg-cyan-300/10" : "border-white/10 bg-[#121d2c]"}`} style={{gridColumn: i===0?"1":i<3?"2":"3"}}><p className="text-xs text-slate-400">{s.progress}% complete</p><p className="mt-1 text-sm font-bold">{s.name}</p><div className="mt-3 h-1 rounded bg-white/5"><div className="h-full rounded bg-cyan-300" style={{width:`${s.progress}%`}}/></div></button>)}</div></div></section>; }
function Quiz({t,question,selected,answer,setAnswer,next}:{t:typeof copy.en;question:typeof questions[number];selected:number;answer:number|null;setAnswer:(n:number)=>void;next:()=>void}) { const answered = answer !== null; return <section className="mx-auto max-w-3xl rounded-3xl border border-white/10 bg-[#111a28] p-5 sm:p-8"><div className="flex justify-between text-sm text-slate-400"><span>{t.mixedExam}</span><span>{selected+1} / {questions.length}</span></div><div className="mt-4 h-1.5 rounded bg-white/5"><div className="h-full rounded bg-cyan-300" style={{width:`${((selected+1)/questions.length)*100}%`}}/></div><p className="mt-8 text-xs font-semibold uppercase tracking-[.13em] text-cyan-200">{question.domain}</p><h2 className="mt-3 text-xl font-semibold leading-8">{question.text}</h2><div className="mt-6 space-y-3">{question.options.map((option,i) => <button disabled={answered} onClick={()=>setAnswer(i)} key={option} className={`w-full rounded-xl border p-4 text-start text-sm transition ${answer === i ? (i === question.correct ? "border-emerald-400 bg-emerald-400/10" : "border-rose-400 bg-rose-400/10") : "border-white/10 bg-black/10 hover:border-cyan-300/50"}`}>{option}</button>)}</div>{answered && <div className={`mt-6 rounded-xl border p-4 ${answer === question.correct ? "border-emerald-400/30 bg-emerald-400/5" : "border-amber-300/30 bg-amber-300/5"}`}><p className="font-semibold">{answer === question.correct ? t.correctAnswer : t.addedLeitner}</p><p className="mt-2 text-sm leading-6 text-slate-300">{question.rationale[t.lang]}</p><a className="mt-3 inline-block text-sm font-semibold text-cyan-200" href={question.source} target="_blank" rel="noreferrer">{t.viewSource} ↗</a></div>}<button disabled={!answered} onClick={next} className="mt-6 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-[#071016] disabled:opacity-35">{t.nextQuestion} →</button></section>; }
function Labs({t,completed,onComplete}:{t:typeof copy.en;completed:boolean;onComplete:()=>void}) { return <section className="mx-auto max-w-4xl rounded-3xl border border-white/10 bg-[#111a28] p-5 sm:p-8"><span className="rounded-full bg-cyan-300/10 px-3 py-1 text-xs font-semibold text-cyan-200">{t.realLab}</span><h2 className="mt-4 text-2xl font-bold">{t.labName}</h2><p className="mt-3 max-w-2xl leading-7 text-slate-300">{t.labDescription}</p><div className="mt-8 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl bg-black/20 p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">{t.topology}</p><div className="mt-5 grid place-items-center gap-3 rounded-xl border border-dashed border-cyan-300/25 bg-[#0c1520] p-5 text-center"><div className="rounded-lg border border-cyan-300/40 p-3 text-sm">DC01<br/><span className="text-xs text-slate-400">AD DS · DNS</span></div><span className="text-cyan-300">↕</span><div className="rounded-lg border border-white/20 p-3 text-sm">SRV01<br/><span className="text-xs text-slate-400">File services</span></div></div><p className="mt-4 text-sm text-slate-400">Hyper-V · two Windows Server evaluation VMs</p></div><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">{t.steps}</p><ol className="mt-4 space-y-3">{t.labSteps.map((x,i)=><li key={x} className="flex gap-3 text-sm leading-6"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-white/5 text-xs text-cyan-200">{i+1}</span>{x}</li>)}</ol></div></div><div className="mt-7 rounded-2xl border border-white/10 p-5"><p className="font-semibold">{t.evidence}</p><p className="mt-1 text-sm text-slate-400">{t.evidenceHelp}</p><textarea className="mt-4 min-h-24 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none focus:border-cyan-300" placeholder="Paste commands, result summary, or evidence link…" /></div><button onClick={onComplete} className={`mt-5 rounded-xl px-5 py-3 text-sm font-bold ${completed ? "bg-emerald-400 text-[#071016]" : "bg-cyan-300 text-[#071016]"}`}>{completed ? t.completed : t.markComplete}</button></section>; }
function Cards({t,known,onReview}:{t:typeof copy.en;known:boolean;onReview:()=>void}) { return <section className="mx-auto max-w-2xl"><div className="mb-5 flex justify-between"><div><p className="text-sm text-slate-400">{t.leitner}</p><h2 className="mt-1 text-2xl font-bold">{t.dueCards}</h2></div><span className="rounded-full bg-cyan-300/10 px-3 py-1 text-sm text-cyan-200">3 / 8</span></div><article className="min-h-80 rounded-3xl border border-cyan-300/25 bg-gradient-to-br from-[#173147] to-[#111a28] p-8"><p className="text-xs font-semibold uppercase tracking-[.14em] text-cyan-200">Security · Box 2</p><h3 className="mt-10 text-2xl font-semibold leading-9">What is the main purpose of Windows Defender Credential Guard?</h3><p className="mt-6 border-t border-white/10 pt-5 text-sm leading-7 text-slate-300">It uses virtualization-based security to protect credential secrets from unauthorized access.</p></article><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={onReview} className="rounded-xl border border-rose-300/30 bg-rose-300/5 px-4 py-3 text-sm font-semibold text-rose-200">{t.again}</button><button onClick={onReview} className="rounded-xl bg-cyan-300 px-4 py-3 text-sm font-bold text-[#071016]">{known ? t.scheduled : t.gotIt}</button></div></section>; }
