export type Language = "fa" | "en" | "de";
export const skills = [
  { id:"security", name:"Security hardening", short:"Security", progress:62 }, { id:"ha", name:"High availability", short:"HA", progress:38 }, { id:"dr", name:"Disaster recovery", short:"DR", progress:54 }, { id:"migration", name:"Migration", short:"Migration", progress:46 }, { id:"monitoring", name:"Monitoring & troubleshooting", short:"Monitor", progress:31 },
];
const source = "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-802";
export const questions = [
  { domain:"Secure Windows Server networking", text:"You need to require IPsec authentication between members of the finance domain while allowing standard traffic for all other devices. Which Windows Defender Firewall with Advanced Security rule type should you configure?", options:["Inbound rule", "Outbound rule", "Connection security rule", "Program rule"], correct:2, source, rationale:{fa:"Connection security rules برای الزام احراز هویت و محافظت IPsec بین endpointها استفاده می‌شوند. این سؤال تألیفی است و به هدف رسمی امنیت شبکه در AZ-802 متصل است.",en:"Connection security rules define authentication and protection requirements such as IPsec between endpoints. This original question maps to the AZ-802 network security objective.",de:"Verbindungssicherheitsregeln definieren Authentifizierungs- und Schutzanforderungen wie IPsec zwischen Endpunkten."}},
  { domain:"High availability", text:"A two-node failover cluster runs across two sites. You need a resilient quorum vote hosted outside both sites. Which witness should you configure?", options:["Disk witness", "File share witness in Site A", "Cloud witness", "USB witness"], correct:2, source, rationale:{fa:"Cloud witness یک رأی quorum خارج از هر دو سایت فراهم می‌کند و برای سناریوهای چندسایتی مناسب است.",en:"A cloud witness provides a quorum vote outside both sites, making it appropriate for a multi-site cluster.",de:"Ein Cloud Witness stellt eine Quorumstimme außerhalb beider Standorte bereit und eignet sich für Multi-Site-Cluster."}},
  { domain:"Monitoring & troubleshooting", text:"Which tool should you use to collect Windows Server event data and correlate it with alerts in a cloud-based monitoring workspace?", options:["Windows Memory Diagnostic", "Azure Monitor Agent", "Disk Cleanup", "Local Users and Groups"], correct:1, source, rationale:{fa:"Azure Monitor Agent داده‌های مانیتورینگ را جمع‌آوری و به Azure Monitor ارسال می‌کند.",en:"Azure Monitor Agent collects monitoring data from Windows Server and sends it to Azure Monitor.",de:"Der Azure Monitor Agent sammelt Überwachungsdaten von Windows Server und sendet sie an Azure Monitor."}},
];
export const copy = {
  en:{lang:"en" as Language,greeting:"Ready for focused practice",dashboard:"Dashboard",graph:"Skill graph",exams:"Exams",labs:"Labs",leitner:"Leitner",target:"Current target",officialPractice:"Official Practice Assessment",overview:"Your learning overview",courseTitle:"Windows Server Administrator Associate",lessons:"Lessons",correct:"Correct",days:"Study days",nextLesson:"Continue learning",continue:"Open lesson",examTitle:"Mixed practice",labTitle:"Hands-on lab",reviewTitle:"Spaced review",startExam:"Start exam",openLab:"Open lab",reviewNow:"Review cards",skillMap:"Skill map",learningGraph:"Learning graph",clickNode:"Follow a node",mixedExam:"English practice · original question",correctAnswer:"Correct — objective reinforced",addedLeitner:"Added to your Leitner review",viewSource:"View official source",nextQuestion:"Next question",realLab:"Real Hyper-V lab",labName:"Harden a two-server domain",labDescription:"Build a small isolated lab, apply a security baseline, and document the verification result. Complete this in your own Hyper-V environment.",topology:"Topology",steps:"Steps",labSteps:["Create two Windows Server evaluation VMs on an isolated virtual switch.","Install AD DS and DNS on DC01; create a test domain.","Join SRV01 and configure a restrictive Windows Defender Firewall rule.","Verify domain authentication and record the resulting event or command output."],evidence:"Evidence",evidenceHelp:"Keep your command output or a private screenshot reference. Never upload credentials.",markComplete:"Mark lab complete",completed:"Lab completed",dueCards:"Cards due today",again:"Again · 1 day",gotIt:"Got it · 7 days",scheduled:"Scheduled · 7 days"},
  fa:{lang:"fa" as Language,greeting:"برای تمرین متمرکز آماده‌ای",dashboard:"میزکار",graph:"نقشهٔ مهارت",exams:"آزمون‌ها",labs:"لاب‌ها",leitner:"لایتنر",target:"هدف فعلی",officialPractice:"تمرین رسمی مایکروسافت",overview:"نمای یادگیری شما",courseTitle:"Windows Server Administrator Associate",lessons:"درس‌ها",correct:"پاسخ درست",days:"روز مطالعه",nextLesson:"ادامهٔ یادگیری",continue:"باز کردن درس",examTitle:"تمرین ترکیبی",labTitle:"لاب عملی",reviewTitle:"مرور فاصله‌دار",startExam:"شروع آزمون",openLab:"باز کردن لاب",reviewNow:"مرور کارت‌ها",skillMap:"نقشهٔ مهارت",learningGraph:"گراف یادگیری",clickNode:"یک گره را دنبال کنید",mixedExam:"تمرین انگلیسی · سؤال تألیفی",correctAnswer:"درست — هدف تقویت شد",addedLeitner:"به مرور لایتنر اضافه شد",viewSource:"مشاهدهٔ منبع رسمی",nextQuestion:"سؤال بعدی",realLab:"لاب واقعی Hyper-V",labName:"سخت‌سازی دامنهٔ دو سروره",labDescription:"یک لاب کوچک ایزوله بسازید، baseline امنیتی را اعمال و نتیجهٔ بررسی را ثبت کنید. این کار در Hyper-V خودتان انجام می‌شود.",topology:"توپولوژی",steps:"مراحل",labSteps:["دو VM ارزیابی Windows Server روی virtual switch ایزوله بسازید.","روی DC01، AD DS و DNS نصب و یک دامنهٔ آزمایشی ایجاد کنید.","SRV01 را join و یک قانون محدودکنندهٔ Firewall بسازید.","احراز هویت دامنه را بررسی و خروجی event یا command را ثبت کنید."],evidence:"شواهد",evidenceHelp:"خروجی فرمان یا مرجع screenshot خصوصی را ثبت کنید؛ هرگز credential را ارسال نکنید.",markComplete:"ثبت تکمیل لاب",completed:"لاب تکمیل شد",dueCards:"کارت‌های امروز",again:"دوباره · ۱ روز",gotIt:"بلدم · ۷ روز",scheduled:"زمان‌بندی شد · ۷ روز"},
  de:{lang:"de" as Language,greeting:"Bereit für konzentriertes Üben",dashboard:"Übersicht",graph:"Kompetenzkarte",exams:"Prüfungen",labs:"Labs",leitner:"Leitner",target:"Aktuelles Ziel",officialPractice:"Offizielles Practice Assessment",overview:"Dein Lernüberblick",courseTitle:"Windows Server Administrator Associate",lessons:"Lektionen",correct:"Richtig",days:"Lerntage",nextLesson:"Weiterlernen",continue:"Lektion öffnen",examTitle:"Gemischtes Training",labTitle:"Praxis-Lab",reviewTitle:"Spaced Repetition",startExam:"Prüfung starten",openLab:"Lab öffnen",reviewNow:"Karten wiederholen",skillMap:"Kompetenzkarte",learningGraph:"Lerngraph",clickNode:"Knoten verfolgen",mixedExam:"Englisches Training · eigene Frage",correctAnswer:"Richtig — Ziel gefestigt",addedLeitner:"Zur Leitner-Wiederholung hinzugefügt",viewSource:"Offizielle Quelle",nextQuestion:"Nächste Frage",realLab:"Echtes Hyper-V-Lab",labName:"Zwei-Server-Domäne absichern",labDescription:"Erstelle ein isoliertes Lab, wende eine Sicherheitsbaseline an und dokumentiere das Prüfergebnis in deiner Hyper-V-Umgebung.",topology:"Topologie",steps:"Schritte",labSteps:["Zwei Windows-Server-Evaluierungs-VMs auf einem isolierten virtuellen Switch erstellen.","AD DS und DNS auf DC01 installieren und eine Testdomäne erstellen.","SRV01 beitreten lassen und eine restriktive Firewallregel konfigurieren.","Domänenanmeldung prüfen und Ereignis- oder Befehlsausgabe dokumentieren."],evidence:"Nachweis",evidenceHelp:"Befehlsausgabe oder privaten Screenshot-Verweis speichern. Nie Anmeldedaten hochladen.",markComplete:"Lab als erledigt markieren",completed:"Lab abgeschlossen",dueCards:"Heute fällige Karten",again:"Erneut · 1 Tag",gotIt:"Gewusst · 7 Tage",scheduled:"Geplant · 7 Tage"},
};
