import { integer, primaryKey, sqliteTable, text } from "drizzle-orm/sqlite-core";

const audit = { createdAt: integer("created_at", { mode: "timestamp" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() };
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), passwordHash: text("password_hash").notNull(), preferredLanguage: text("preferred_language").notNull().default("fa"), ...audit });
export const passwordResetTokens = sqliteTable("password_reset_tokens", { id: text("id").primaryKey(), userId: text("user_id").notNull(), tokenHash: text("token_hash").notNull().unique(), expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(), usedAt: integer("used_at", { mode: "timestamp" }), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const skills = sqliteTable("skills", { id: text("id").primaryKey(), examCode: text("exam_code").notNull(), title: text("title").notNull(), sourceUrl: text("source_url").notNull(), sourceVersion: text("source_version").notNull(), reviewedAt: integer("reviewed_at", { mode: "timestamp" }).notNull() });
export const lessons = sqliteTable("lessons", { id: text("id").primaryKey(), skillId: text("skill_id").notNull(), contentKey: text("content_key").notNull(), sourceUrl: text("source_url").notNull(), estimatedMinutes: integer("estimated_minutes").notNull(), ...audit });
export const questions = sqliteTable("questions", { id: text("id").primaryKey(), skillId: text("skill_id").notNull(), contentKey: text("content_key").notNull(), sourceUrl: text("source_url").notNull(), reviewStatus: text("review_status").notNull().default("draft"), isOriginal: integer("is_original", { mode: "boolean" }).notNull().default(true), ...audit });
export const attempts = sqliteTable("attempts", { id: text("id").primaryKey(), userId: text("user_id").notNull(), questionId: text("question_id").notNull(), selectedAnswer: integer("selected_answer").notNull(), isCorrect: integer("is_correct", { mode: "boolean" }).notNull(), answeredAt: integer("answered_at", { mode: "timestamp" }).notNull() });
export const flashcards = sqliteTable("flashcards", { id: text("id").primaryKey(), userId: text("user_id").notNull(), questionId: text("question_id").notNull(), box: integer("box").notNull().default(1), dueAt: integer("due_at", { mode: "timestamp" }).notNull(), ...audit });
export const labs = sqliteTable("labs", { id: text("id").primaryKey(), skillId: text("skill_id").notNull(), contentKey: text("content_key").notNull(), sourceUrl: text("source_url").notNull(), ...audit });
export const labSubmissions = sqliteTable("lab_submissions", { id: text("id").primaryKey(), labId: text("lab_id").notNull(), userId: text("user_id").notNull(), evidenceText: text("evidence_text").notNull(), evidenceUrl: text("evidence_url"), score: integer("score"), completedAt: integer("completed_at", { mode: "timestamp" }), ...audit });
export const progress = sqliteTable("progress", { userId: text("user_id").notNull(), lessonId: text("lesson_id").notNull(), completionPercent: integer("completion_percent").notNull().default(0), ...audit }, (table) => ({ primaryKey: primaryKey({ columns: [table.userId, table.lessonId] }) }));
